### PR TITLE
fix(card): card component checkbox accessibility name and keyboard access #5168

### LINKED ISSUE #5168: [Bug][a11y]: Card component checkbox for selection has no accessibility name and is not keyboard accessible
### Code of conduct

- [x] I agree to follow this project's code of conduct.

### Impacted component(s)

Card, Grid

### Expected behavior

In a Card component, when the `toggles` boolean property is specified:
1. the checkbox that displays on hover must have an accessibility name.
2. the checkbox should be keyboard focusable

To fix these issues, remove  `tabIndex="-1"` and include the header text as a hidden accessible name for the sp-checkbox at:
https://github.com/adobe/spectrum-web-components/blob/e7d153e653da03fbceb0c5a605bc6e2f6d21ca3a/packages/card/src/Card.ts#L318-L323

```js
                          <sp-checkbox
                              class="checkbox"
                              @change=${this.handleSelectedChange}
                              ?checked=${this.selected}
                          >
                            <span class="sr-only">${this.heading}</span>
                          </sp-checkbox>
```

The `.sr-only` style, and a `--mod-checkbox-text-to-control` override to account for the fact that the text label is visually hidden, should be added to the [card.css](https://github.com/adobe/spectrum-web-components/blob/main/packages/card/src/card.css) file:

```css
.checkbox-toggle .checkbox {
    --mod-checkbox-text-to-control: 0;
}

.sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
}
```
At present, this is the only way to appropriately label a `sp-checkbox`.

3. Similarly, in the storybook examples using the Card with an action button, the action button should be keyboard focusable.

Again, we need to remove `tabIndex="-1"` from the `sp-action-menu`  in Card rendering for the Storybook example:
https://github.com/adobe/spectrum-web-components/blob/e7d153e653da03fbceb0c5a605bc6e2f6d21ca3a/tools/grid/stories/grid.stories.ts#L77-L83

```js
             <sp-action-menu 
                 label="File actions" 
                 slot="actions" 
                 placement="bottom-end" 
                 quiet 
             > 
```

### Actual behavior

In a Card component, when the `toggles` boolean property is specified:
1. the checkbox that displays on hover or focus does not have an accessibility name.
2. the checkbox cannot receive focus with a keyboard
3. Similarly, in the storybook examples using the Card with an action button, the action button is not keyboard focusable.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

Chrome, Firefox, Safari, Microsoft Edge

### Sample code or abstract reproduction which illustrates the problem

_No response_

### Severity

None

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by majornista**
## Description

In a Card component, when the `toggles` boolean property is specified:
1. the checkbox that displays on hover must have an accessibility name.
2. the checkbox should be keyboard focusable

To fix these issues, remove  `tabIndex="-1"` and include the header text as a hidden accessible name for the sp-checkbox at:
https://github.com/adobe/spectrum-web-components/blob/e7d153e653da03fbceb0c5a605bc6e2f6d21ca3a/packages/card/src/Card.ts#L318-L323

```js
                          <sp-checkbox
                              class="checkbox"
                              @change=${this.handleSelectedChange}
                              ?checked=${this.selected}
                          >
                            <span class="sr-only">${this.heading}</span>
                          </sp-checkbox>
```

The `.sr-only` style, and a `--mod-checkbox-text-to-control` override to account for the fact that the text label is visually hidden, should be added to the [card.css](https://github.com/adobe/spectrum-web-components/blob/main/packages/card/src/card.css) file:

```css
.checkbox-toggle .checkbox {
    --mod-checkbox-text-to-control: 0;
}

.sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
}
```
At present, this is the only way to appropriately label a `sp-checkbox`.

3. Similarly, in the storybook examples using the Card with an action button, the action button should be keyboard focusable.

Again, we need to remove `tabIndex="-1"` from the `sp-action-menu`  in Card rendering for the Storybook example:
https://github.com/adobe/spectrum-web-components/blob/e7d153e653da03fbceb0c5a605bc6e2f6d21ca3a/tools/grid/stories/grid.stories.ts#L77-L83

```js
             <sp-action-menu 
                 label="File actions" 
                 slot="actions" 
                 placement="bottom-end" 
                 quiet 
             > 
```

## Related issue(s)

resolves #5168

## Motivation and context

Currently, in a Card component, when the `toggles` boolean property is specified:
1. the checkbox that displays on hover or focus does not have an accessibility name.
2. the checkbox cannot receive focus with a keyboard
3. Similarly, in the storybook Grid examples using the Card with an action button, the action button is not keyboard focusable.

## How has this been tested?

-   [x] _Test case 1_
    1. Go here: https://5168-card-checkbox-a11y--spectrum-wc.netlify.app/storybook/?path=/story/card--toggles
    2. Tab into the Storybook story for the Card component with `toggles` boolean property added.
    3. First, the Action Menu button should receive keyboard focus, which will fade in the checkbox as well.
    4. Press Tab to focus the checkbox.
    5. Press Space bar to check the checkbox, which will change the Card state to selected.
-   [x] _Test case 2_
    1. Go here: https://5168-card-checkbox-a11y--spectrum-wc.netlify.app/storybook/?path=/story/card--default&args=toggles:!true, which is the Default story with the `toggles` control within Storybook set to `true`.
    2. Tab into the Storybook story for the Card component with `toggles` boolean property added.
    3. First, the checkbox button should receive keyboard focus, which will fade in the checkbox overlay.
    5. Press Space bar to check the checkbox, which will change the Card state to selected.
-  [x] _Test case 3_
    1. Go here: https://5168-card-checkbox-a11y--spectrum-wc.netlify.app/storybook/?path=/story/grid--default
    2. Tab into the Storybook story for the Grid component to first focus the text input before the grid containing cards as items.
    3. Press Tab again to move focus to the grid. The first card item should receive keyboard focus.
    4. Use ArrowDown or ArrowRight to move focus to an adjacent card.
    5. Press Tab, which will move focus to the action button within the card, and will fade in the checkbox for to select the Card.
    6. Press Tab again to focus the checkbox.
    7. Press Space to check the checkbox, which will change the Card state to selected.
    8. Press Tab to move focus to the action bar showing selected items and available actions that follows the grid.
    9. Press Shift+Tab to move focus back to the grid. The last Card that contained focus should receive focus again.

-   [x] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Screenshots (if appropriate)

https://github.com/user-attachments/assets/3640e420-66b3-4f3f-b4e7-3c4bf789ec95

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by majornista** [comment]
@adobe/swc-maintainers Can someone provide a review for this PR? These accessibility fixes are important to [PandoraUI/ims-connected-identities](https://git.corp.adobe.com/PandoraUI/ims-connected-identities/blob/6f793bd6d57d5aa153b00320b037e57430ef2133/packages/web-component-ims-connected-identity/package.json#L56), which is a dependency for [cai/cr-web](https://git.corp.adobe.com/cai/cr-web/blob/809f44378f351f916ba09e71c5c860b5433d21ec/package.json#L40).

The accessibility issue that I'm trying to fix is that the checkbox to select or deselect social media profiles for inclusion within Content Credentials cannot be focused or activated using either the keyboard or a screen reader.

File: packages/card/src/Card.ts [hunk 1]
```diff
@@ -78,6 +78,9 @@ export class Card extends LikeAnchor(
     set selected(selected: boolean) {
         if (selected === this.selected) return;
         this._selected = selected;
+        if (this.role === 'row' && this.toggles) {
```
Comment (nikkimk) [inline packages/card/src/Card.ts:81]: @majornista can you add some a11y notes and examples for this in `packages/card/EADMEN.md`?

File: tools/grid/test/grid.test.ts [hunk 2]
```diff
@@ -31,6 +31,12 @@ describe('Grid', () => {
                 <div>${Default()}</div>
             `)
     );
+    beforeEach(() => {
```
Comment (nikkimk) [inline tools/grid/test/grid.test.ts:34]: @majornista can you add some a11y notes for this in `packages/grid/README.md`?

File: packages/card/src/card.css [hunk 3]
```diff
@@ -97,3 +97,51 @@ sp-popover {
...
+    clip: rect(0, 0, 0, 0);
+    white-space: nowrap;
+    border: 0;
+}
+
+.wrapper {
+    display: contents;
+}
+
+@media (prefers-reduced-motion: reduce) {
```
Comment (nikkimk) [inline packages/card/src/card.css:133]: @majornista can you add some a11y notes for this in `packages/card/README.md`?

**Review by nikkimk — CHANGES_REQUESTED** [review]
Thanks for working on this. Can you add a few notes to the docs (and to the PR for posterity) before we approve?

**Comment by majornista** [comment]
> @majornista thanks for working on this. Can you please add more to the following sections of the description above:
> 
> * Motivation and context
> * How has this been tested?

I thought linking to the issue, "Per https://github.com/adobe/spectrum-web-components/issues/5168," would have been sufficient.

**Comment by nikkimk** [comment]
> I thought linking to the issue, "Per #5168," would have been sufficient.

@majornista  In particular "How has this been tested" helps us make sure we're testing the PR and getting the expected results.

Also, if you could update the documentation along with this PR, that would help us keep track of what was done and why as well as communicate to consumers what decisions were made in order to make the component accessible.

File: packages/card/src/Card.ts (hunk 1 above)
Comment (majornista) [reply packages/card/src/Card.ts:81]: I've added documentation for the `toggles` property in `packages/card/README.md`.  This code addresses how the selected state for a card gets communicated when it is used as a `row` item within a `grid`.

File: packages/card/src/card.css (hunk 3 above)
Comment (majornista) [reply packages/card/src/card.css:145]: How components support the `prefers-reduced-motion: reduce` media query preference is not something we normally cover in our component documentation, and in the case of the checkbox fading in subtly there is little accessibility impact. (See https://accessibility.corp.adobe.com/docs/visual_design/motion_graphics/) 

Emulating `prefers-reduced-motion: reduce` can be useful for eliminating flakiness when running [unit tests](https://github.com/adobe/spectrum-web-components/pull/5171/files#diff-fc3c3ac1c689025fe736b7e46f5f1b586f81772c71a9ebb737e888711c4eb970R37-R39), however in updating `tools/grid/test/grid.test.ts`, I discovered that when emulating `prefers-reduced-motion: reduce`, the new test emulate tabbing from the action button to the checkbox was failing because the checkbox would have `visibility: hidden` on blurring the action button, would be unavailable to receive focus, and focus would move to the next element after the grid.

I've added a code comment here to explain why this code was added.

File: tools/grid/test/grid.test.ts (hunk 2 above)
Comment (majornista) [reply tools/grid/test/grid.test.ts:34]: See my comment here: https://github.com/adobe/spectrum-web-components/pull/5171/files#r2014426185

**Comment by majornista** [comment]
@nikkimk One thing I can't quite figure out is why Card selection in the Grid example does not work in the docs. It seems like the entire grid gets redrawn when the checkbox is clicked to select, at which point selection and keyboard focus is lost: https://opensource.adobe.com/spectrum-web-components/tools/grid/#example. The storybook example seems to work: https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/grid--default.

File: tools/grid/README.md [hunk 4]
```diff
@@ -136,6 +150,10 @@ import { Grid } from '@spectrum-web-components/grid';
             card.value = `card-${index}`
             card.selected = selected;
             card.key = index;
+            card.role = 'row';
+            card.label = `Card Heading ${index}`;
+            card.ariaSelected = selected;
```
Comment (nikkimk) [inline tools/grid/README.md:155]:
```suggestion
            card.ariaSelected = grid.selectedItems.includes(card.value);
```

File: tools/grid/README.md [hunk 5]
```diff
@@ -136,6 +150,10 @@ import { Grid } from '@spectrum-web-components/grid';
             card.value = `card-${index}`
             card.selected = selected;
```
Comment (nikkimk) [inline tools/grid/README.md:151]:
```suggestion
            card.selected = grid.selectedItems.includes(card.value);
```

File: tools/grid/README.md [hunk 6]
```diff
@@ -78,6 +83,10 @@ import { Grid } from '@spectrum-web-components/grid';
...
```
Comment (nikkimk) [inline tools/grid/README.md:84]:
```suggestion
            card.selected = grid.selectedItems.includes(card.value);
```

File: tools/grid/README.md [hunk 7]
```diff
@@ -60,6 +60,11 @@ import { Grid } from '@spectrum-web-components/grid';
             width: 200,
             height: 300,
         };
+        grid.role = 'grid';
+        grid.ariaLabel = 'Select images';
+        grid.ariaMultiSelectable = 'true';
+        grid.ariaRowCount = `${grid.items.length}`;
+        grid.ariaColCount = 1;
```
Comment (nikkimk) [inline tools/grid/README.md:67]:
```suggestion
        grid.ariaColCount = 1;
        grid.selectedItems = [];
```

File: tools/grid/README.md [hunk 8]
```diff
@@ -118,6 +127,11 @@ import { Grid } from '@spectrum-web-components/grid';
...
```
Comment (nikkimk) [inline tools/grid/README.md:134]:
```suggestion
        grid.ariaColCount = 1;
        grid.selectedItems = [];
```

File: tools/grid/README.md [hunk 9]
```diff
@@ -78,6 +83,10 @@ import { Grid } from '@spectrum-web-components/grid';
             card.value = `card-${index}`
             card.selected = selected;
             card.key = index;
+            card.role = 'row';
+            card.label = `Card Heading ${index}`;
+            card.ariaSelected = selected;
+            card.ariaRowIndex = `${index + 1}`;
```
Comment (nikkimk) [inline tools/grid/README.md:89]:
```suggestion
            card.ariaRowIndex = `${index + 1}`;
            card.addEventListener('click', () => {
                console.log('clicked', card.value, grid.selectedItems);
                if(grid.selectedItems.includes(card.value)) {
                    grid.selectedItems = grid.selectedItems.filter(item => item !== card.value);
                } else {
                    grid.selectedItems.push(card.value);
                }
                console.log('updated', card.value, grid.selectedItems);
            });
```

File: tools/grid/README.md [hunk 10]
```diff
@@ -136,6 +150,10 @@ import { Grid } from '@spectrum-web-components/grid';
...
```
Comment (nikkimk) [inline tools/grid/README.md:156]:
```suggestion
            card.ariaRowIndex = `${index + 1}`;
            card.addEventListener('click', () => {
                console.log('clicked', card.value, grid.selectedItems);
                if(grid.selectedItems.includes(card.value)) {
                    grid.selectedItems = grid.selectedItems.filter(item => item !== card.value);
                } else {
                    grid.selectedItems.push(card.value);
                }
                console.log('updated', card.value, grid.selectedItems);
            });
```

**Review by nikkimk — CHANGES_REQUESTED** [review]

File: .circleci/config.yml [hunk 11]
```diff
@@ -1,4 +1,4 @@
-version: 2.1
+0version: 2.1
```
Comment (caseyisonit) [inline .circleci/config.yml:1]:
```suggestion
version: 2.1
```

**Review by caseyisonit — APPROVED** [review]
manual tests pass, vrt diff expected since there's a new story. i will update golden hash when I get a second approval.

File: tools/grid/README.md [hunk 12]
```diff
@@ -134,8 +159,21 @@ import { Grid } from '@spectrum-web-components/grid';
...
+            card.ariaSelected = grid.selectedItems.includes(card.value);
+            card.ariaRowIndex = `${index + 1}`;
+            card.addEventListener('click', () => {
+                console.log('clicked', card.value, grid.selectedItems);
+                if(grid.selectedItems.includes(card.value)) {
+                    grid.selectedItems = grid.selectedItems.filter(item => item !== card.value);
+                } else {
+                    grid.selectedItems.push(card.value);
+                }
+                console.log('updated', card.value, grid.selectedItems);
```
Comment (nikkimk) [inline tools/grid/README.md:175]:
```suggestion
```

File: tools/grid/README.md [hunk 13]
```diff
@@ -134,8 +159,21 @@ import { Grid } from '@spectrum-web-components/grid';
...
             card.style = 'contain: strict; padding: 1px;'
             card.value = `card-${index}`
-            card.selected = selected;
+            card.selected = grid.selectedItems.includes(card.value);
             card.key = index;
+            card.role = 'row';
+            card.label = `Card Heading ${index}`;
+            card.ariaSelected = grid.selectedItems.includes(card.value);
+            card.ariaRowIndex = `${index + 1}`;
+            card.addEventListener('click', () => {
```
Comment (nikkimk) [inline tools/grid/README.md:168]:
```suggestion
            card.addEventListener('change', () => {
```

File: tools/grid/README.md [hunk 14]
```diff
@@ -134,8 +159,21 @@ import { Grid } from '@spectrum-web-components/grid';
...
+                console.log('clicked', card.value, grid.selectedItems);
```
Comment (nikkimk) [inline tools/grid/README.md:169]:
```suggestion
```

File: tools/grid/README.md [hunk 15]
```diff
@@ -76,8 +82,21 @@ import { Grid } from '@spectrum-web-components/grid';
...
             card.style = 'contain: strict; padding: 1px;'
             card.value = `card-${index}`
-            card.selected = selected;
+            card.selected = grid.selectedItems.includes(card.value);
             card.key = index;
+            card.role = 'row';
+            card.label = `Card Heading ${index}`;
+            card.ariaSelected = grid.selectedItems.includes(card.value);
+            card.ariaRowIndex = `${index + 1}`;
+            card.addEventListener('click', () => {
```
Comment (nikkimk) [inline tools/grid/README.md:91]:
```suggestion
            card.addEventListener('change', () => {
```

File: tools/grid/README.md [hunk 16]
```diff
@@ -76,8 +82,21 @@ import { Grid } from '@spectrum-web-components/grid';
...
+                console.log('clicked', card.value, grid.selectedItems);
```
Comment (nikkimk) [inline tools/grid/README.md:92]:
```suggestion
```

File: tools/grid/README.md [hunk 17]
```diff
@@ -76,8 +82,21 @@ import { Grid } from '@spectrum-web-components/grid';
...
+                if(grid.selectedItems.includes(card.value)) {
+                    grid.selectedItems = grid.selectedItems.filter(item => item !== card.value);
+                } else {
+                    grid.selectedItems.push(card.value);
+                }
+                console.log('updated', card.value, grid.selectedItems);
```
Comment (nikkimk) [inline tools/grid/README.md:98]:
```suggestion
```

**Review by nikkimk — CHANGES_REQUESTED** [review]

**Comment by nikkimk** [comment]
> @nikkimk One thing I can't quite figure out is why Card selection in the Grid example does not work in the docs. It seems like the entire grid gets redrawn when the checkbox is clicked to select, at which point selection and keyboard focus is lost: https://opensource.adobe.com/spectrum-web-components/tools/grid/#example. The storybook example seems to work: https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/grid--default.

@majornista we've been trying to get the docs example working but to no avail. We updated the docs to show the storybook and we'll follow-up with a ticket to fix the docs rather than holding this up any longer.

**Review by nikkimk — APPROVED** [review]
LGTM

File: packages/card/src/Card.ts [hunk 18]
```diff
@@ -76,6 +76,9 @@ export class Card extends LikeAnchor(
...
+            this.setAttribute('aria-selected', String(this.selected));
```
Comment (Rajdeepc) [inline packages/card/src/Card.ts:80]: Why are we typecasting here on `this.selected`?

File: packages/card/src/Card.ts [hunk 19]
```diff
@@ -266,77 +272,105 @@ export class Card extends LikeAnchor(
...
         return html`
-            ${this.renderImage()}
-            <div class="body">
-                <div class="header">
-                    ${this.renderHeading}
-                    ${this.variant === 'gallery'
-                        ? this.renderSubtitleAndDescription
-                        : nothing}
-                    ${this.variant !== 'quiet' || this.size !== 's'
+            <div class="wrapper" role=${ifDefined(roleForWrapper)}>
```
Comment (Rajdeepc) [inline packages/card/src/Card.ts:281]: what would be the consequence of role="undefined"?

File: packages/card/src/Card.ts [hunk 20]
```diff
@@ -266,77 +272,105 @@ export class Card extends LikeAnchor(
...
+                    : nothing}
+                ${this.toggles
                     ? html`
-                          <div class="content">
-                              ${this.renderSubtitleAndDescription}
+                          <sp-popover
+                              class="checkbox-toggle"
+                              @pointerdown=${this.stopPropagationOnHref}
+                          >
+                              <sp-checkbox
```
Comment (Rajdeepc) [inline packages/card/src/Card.ts:325]: nit: I am not sure on the historical context of adding a direct element dependency of checkbox which reduces the flexibility and reusability. We should avoid this in future. Rather add slots and surface up extensibility should be a nicer way to move forward.

File: packages/card/src/Card.ts [hunk 21]
```diff
@@ -266,77 +272,105 @@ export class Card extends LikeAnchor(
...
 
     protected override firstUpdated(changes: PropertyValues): void {
         super.firstUpdated(changes);
+        if (changes.has('label')) {
+            if (this.label) {
+                this.setAttribute('aria-label', this.label);
+            } else {
+                this.removeAttribute('aria-label');
+            }
+        }
```
Comment (Rajdeepc) [inline packages/card/src/Card.ts:359]: this is redundant since update will be called during the initial update as well. We can remove this logic from firstUpdated and keep it only in update.

**Review by rubencarvalho — APPROVED** [review]
LGTM! Great fix to a rather severe bug! :) Left a non-blocking comment.

File: tools/grid/test/grid.test.ts [hunk 22]
```diff
@@ -128,9 +134,43 @@ describe('Grid', () => {
...
+        expect(el.tabIndex).to.equal(-1);
+
+        await sendKeys({
+            press: 'Tab',
+        });
+
+        await nextFrame();
+        await nextFrame();
+        await nextFrame();
+        await nextFrame();
```
Comment (castastrophe) [inline tools/grid/test/grid.test.ts:163]: Rather than relying on nextFrame, if we can connect the test to a certain thing we are waiting for, it ensures more stable test results.

**Review by castastrophe — CHANGES_REQUESTED** [review]

File: tools/grid/test/grid.test.ts (hunk 22 above)
Comment (Rajdeepc) [reply tools/grid/test/grid.test.ts]: Replaced all the brittle `nextFrame()` calls with robust `waitUntil()` calls that wait for actual state changes.

File: tools/grid/src/Grid.ts [hunk 23]
```diff
@@ -70,8 +70,25 @@ export class Grid extends LitVirtualizer {
         padding: () => this.padding || this.gap,
     });
 
+    private lastTargetForChange: HTMLElement | undefined;
+    private animationFrameId: number | undefined;
```
[the remark this answers is not in the document]
Comment (Rajdeepc) [reply tools/grid/src/Grid.ts]: Yes less verbose and clear

File: tools/grid/README.md [hunk 24]
```diff
@@ -96,7 +115,8 @@ import { Grid } from '@spectrum-web-components/grid';
 </script>
 ```
 
-<script type="module">
+<!-- @todo make the example work for a keyboard -->
```
[the remark this answers is not in the document]
Comment (Rajdeepc) [reply tools/grid/README.md]: tracking in https://github.com/adobe/spectrum-web-components/issues/5582

**Review by blunteshwar — APPROVED** [review]
LGTM!
