### PR TITLE
fix(overlay): move "escape" listener to "keydown"

### LINKED ISSUE #1844: [Bug]: SWC uses keyup handlers more often than it should
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay and many more

### Expected behavior

SWC should default to using keydown events unless there's a specific reason to use keyup.

### Actual behavior

There's many places where SWC handles events with keyup. This makes it difficult if you have another handler for that key registered to keydown. Rather than being able to use event bubbling you'd need to add specific logic based on the handling SWC is doing.

The example we hit was the escape key handling in the overlay implementation. We have a keydown handler that was triggering for a component under the overlay.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Move `Escape` listener to `keydown` to match native `<modal>` interaction.

## Related issue(s)

- fixes #1844

## How has this been tested?
-   [ ] _Test case 1_
    1. With updated unit tests.

## Types of changes
-   [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: packages/overlay/src/ActiveOverlay.ts [hunk 1]
```diff
@@ -223,7 +223,10 @@ export class ActiveOverlay extends SpectrumElement {
     }
 
     public feature(): void {
-        this.tabIndex = -1;
+        // eslint-disable-next-line spectrum-web-components/document-active-element
+        if (!this.contains(document.activeElement)) {
```
Comment (Westbrook) [inline packages/overlay/src/ActiveOverlay.ts:227]: Allows you to tab through https://overlay-escape--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-wrapped--tooltips in both forward and backward directions without getting blocked out of the Dialog after leaving the iframe...

**Review by najikahalsema — APPROVED** [review]
