### PR TITLE
Ship Overlay v2

### LINKED ISSUE #1853: [Feat]: Allow overlays to decide if they can be closed or not
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay

### Description of the requested feature

The main problem starts here https://github.com/adobe/spectrum-web-components/blob/main/packages/overlay/src/overlay-stack.ts#L495-L501

Pressing `Escape` will close the overlay no matter what, and this is problematic for some modals.

Imagine that we have an upload dialog, once the user clicks the "Upload" button the process begins, and a progress bar is
updated from 0% to 100% indicating the upload status. In this particular case the process is not cancellable, the user must wait until the upload is complete, otherwise the app will be (lets say) in some undefined state. Now, if the user accidentally hits `Escape` the dialog will close, and lots of errors will appear (because the progress bar no longer exists, but the async process tries to update it, or some other errors).

Currently the only option is to monkey-patch and set `handleKeyUp` method to nop, which completely disables the `Escape` close mode.

### Mockups or screenshots

_No response_

### Implementation notes or ideas

Maybe some `isClosable` property?

### LINKED ISSUE #1876: [Feat]: Overlay, manage "clicks" that do not effect the stack.
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay

### Description of the requested feature

In some cases there may be reason to allow for clicks on the page not to effect the overlay stack, for instance when placing synthetic `<input type="file" />` elements out of bound of overlays where `upload` interactions are starting due to those overlays being owned by other elements/teams. An escape hatch should be surfaced that would allow those clicks to be ignored without having to do something like: https://webcomponents.dev/edit/aEh5DWhJDDXuCnyOlD4Z/src/index.ts

Example: A synthetic click is handled the same way as a "real" click, and would close the overlay even if that's what you didn't mean to do. 

### Mockups or screenshots

_No response_

### Implementation notes or ideas

Simplest, though maybe weakest stability, approach to this would be to document a class or attribute that removed a target element from the processing done in the overlay stack. 

Overlay could surface a `ignoreElement()` API where we registered elements.

Overlay could surface a `root` API such that events outside of the root weren't listened to.

Thoughts?

### LINKED ISSUE #2026: Overlay: allow changing z-index
### Expected Behaviour

Overlay z-index is changeable via a css custom property

### Actual Behaviour

It's hard coded to 1000

### LINKED ISSUE #2086: [Feat]: Abstract Overlay API Review
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay

## openOverlay currently accepts:
```
{
    target: HTMLElement,
    interaction:
      | 'click'
      | 'longpress'
      | 'hover'
      | 'custom'
      | 'replace'
      | 'inline'
      | 'modal',
    content: HTMLElement,
    options: {
      delayed?: boolean;
      placement?: Placement;
      offset?: number;
      receivesFocus?: 'auto';
      notImmediatelyClosable?: boolean;
      abortPromise?: Promise<boolean>;
      virtualTrigger?: VirtualTrigger;
    }
}
```

A content element managed for overlay looks like:
```
interface ManagedOverlayContent {
    open: boolean;
    overlayWillOpenCallback?: (args: { trigger: HTMLElement }) => void;
    overlayOpenCallback?: (args: { trigger: HTMLElement }) => void;
    overlayOpenCancelledCallback?: (args: { trigger: HTMLElement }) => void;
    overlayCloseCallback?: (args: { trigger: HTMLElement }) => void;
}
```

## Important question
If we created a new API could we smooth transition by wrapping it with the old API for the initial term? 

## Things we might want instead:
`content` is required but `trigger` is not
  - points to a usage of the "Active Stack" concept where the "trigger" was the previous "active element" and that content would manage things like theme, focus return, etc.

tabOrder: 'none' | 'inline' | 'replace' | 'trap'
  - 'none' = tooltip and similar that are given `aria-*` based content relations
  - 'inline' = before trigger <=> trigger <=> overlay <=> after overlay
  - 'replace' = before trigger <=> trigger when closed, overlay when open <=> after overlay
  - 'trap' = modal
This should absolve the need for `receivedFocus` as all overlays need focus for the screen reader to step into them when `aria-*` attributes are not managing the content relations.

interaction:
  - likely the only interaction not managed by `tabOrder` is `longpress` which really only manages the first click event. 

backdrop management:
  - not all "modals" have a backdrop and we need to manage it somehow
  - it may be that backdrops need to be handled 100% of the time by the overlaid content and not by the overlay system

stack management:
  - overlays need access to the stack to prevent DOM based state resolution
  - adding/removing something from the stack should be synchronous
  - any new non-`tabOrder='none'` content should dismiss all preceeding `tabOrder='none'` content on the stack

overlay management:
  - (on or off the stack) should manage their own asyncrony
  - lifecycle should be both explicit and easy to apply

Does `abortPromise` belong on the overlay lifecycle? Does making the stack syncronous prevent needing to maintain this code path.

Configurable and re-configurable overlays:
- elements like `sp-picker` should be able to surface more options around the overlay they throw, see [coment](https://github.com/adobe/spectrum-web-components/pull/2082#discussion_r796751961) and [issue](https://github.com/adobe/spectrum-web-components/issues/2067)
- overlays thrown in this way should be "updatable", for instance when going between mobile and desktop so that the wrapper (Tray vs Popover) and placement (specific vs 'none') can be swapped

### LINKED ISSUE #2282: [Bug]: dialog and aria-modal are on different elements
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

dialog / dialog wrapper

### Expected behavior

aria-modal and role=dialog are on different elements.
These have to be on the same element per the aria spec https://w3c.github.io/aria/#aria-modal

### Actual behavior

When rendering a dialog using dialog wrapper the role=dialog gets rendered on the sp-dialog element but aria-modal=true gets rendered on the active-overlay element.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

1. Go to dialog wrapper https://opensource.adobe.com/spectrum-web-components/components/dialog-wrapper/
2. Click on toggle dialog
3. inspect the DOM

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### LINKED ISSUE #2359: [Bug]: Memory Leak when we remove sp-tooltip(self-managed) from dom but not its parent
### Code of conduct

- [x] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tooltip

### Expected behavior

When client conditionally render the `sp-tooltip`, when its removed from DOM it should remove the event listener from the parent. so that when we hover on the parent the active-overlay should not be added on the DOM.
See : [https://studio.webcomponents.dev/edit/dcmsShnRpGqlmmaBvPWy/src/index.ts?p=stories](https://studio.webcomponents.dev/edit/dcmsShnRpGqlmmaBvPWy/src/index.ts?p=stories)

**When the second time user hovers for 1.5secs on the card, it should look like this**
Screenshot 2022-06-14 at 9 51 23 PM

### Actual behavior

**When the second time user hovers for 1.5secs on the card, it looks like this**
Screenshot 2022-06-14 at 9 49 13 PM

### Screenshots

_No response_

### What browsers are you seeing the problem in?

Chrome, Safari

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

Please check the link in expected behaviour section

### Logs taken while reproducing problem

_No response_

### LINKED ISSUE #2625: [Bug]: sp-popover dismisses unexpectedly
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-popover

### Expected behavior

Include `sp-popover` with `overlay-trigger` and a `<div><sp-icon></sp-icon></div>` as the trigger.
Hover over the icon
`sp-popover` should remain visible on hover

### Actual behavior

Depending on angle of approach (e.g from the top or outside the icon content), `sp-popover` renders briefly then immediately dismisses

### Screenshots

_No response_

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

See sample code
Hover over icon from different approaches, especially from the top.

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/fbq8OMs9JW82nZ1YBVpP/
https://studio.webcomponents.dev/edit/KVdD0QHXejirkE1YNbi2/

### Logs taken while reproducing problem

_No response_

### LINKED ISSUE #2662: [Bug]: Inline and replace tab indexing does not work as expected
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-overlay

### Expected behavior

`inline` places the overlay after the trigger but before the next element in the logical tab order. This means the shift + tab keyboard stroke will return to the trigger.

`replace` will position the overlay directly in the position of the trigger in the logical tab order. This means the shift + tab keyboard stroke will return the focusable element immediately prior to the trigger.

### Actual behavior

Replace returns focus to the trigger after bouncing between the elements before/after it. Inline does not move the focus from the close button at all. 

### How can we reproduce this issue?

Replace:
1. Go to [here](https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/overlay--replace)
2. Tab into the "Open" button 
3. Open the overlay with `ENTER` key
4. Tab into the overlay element ("Close" button)
5. `Shift+Tab` into the previous element, which should be the element before the "Open" button. However, it jumps to that element before ultimately landing on the "Open" button. 

Inline: 
1. Go [here](https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/overlay--inline)
2. Tab into the "Open" button 
3. Open the overlay with `ENTER` key
4. Tab into the overlay element ("Close" button)
5. `Shift+Tab` into the previous element, which should be the "Open" button.
6. See that focus does not leave the "close" button.

### LINKED ISSUE #3079: [Bug]: Active-Overlay still in DOM when closing an overlay modal with Reduce Motion ON
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-dialog-base

### Expected behavior

`active-overlay` should be removed from the DOM

### Actual behavior

`active-overlay` stays in the DOM and you end up with an invisible overlay that captures clicks.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

Can be seen in the Dialog demo - https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/MLYDVWpWhNxJZDW3Ywqq/src/index.ts?p=stories

1. Turn "Reduce Motion" ON (bottom right)
2. Press "Toggle Dialog"
3. Check "Close on click" and press "Cancel" (or another button)
4. Attempt to re-open the dialog by pressing "Toggle Dialog"

You can no longer click anything else and the `active-overlay` is still in the DOM.

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/MLYDVWpWhNxJZDW3Ywqq/src/index.ts?p=stories

### Logs taken while reproducing problem

_No response_

### LINKED ISSUE #3184: [Feat]: Submenu of menu item should be open-able via `open` attribute
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

MenuItem

### Description of the requested feature

We have a use case to control the opening of a submenu of a `sp-menu-item`. Currently it seems it's been only use to reflect the current submenu "open" state. 
We'd like to set that attribute by the outer logic to let the menu-item open it's submenu, when `open` attribute is preset.

### Mockups or screenshots

_No response_

### Implementation notes or ideas

_No response_

### LINKED ISSUE #3199: [Bug]: Multiple active overlays are opened when using action menu
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-menu

### Expected behavior

only one action menu should be opened at a single time

### Actual behavior

Multiple action menu items are opened

### Screenshots

Screenshot 2023-05-11 at 3 26 19 PM

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

1. use the following code to create two action menu elements.
2. click on the first action menu element.
3. Navigate to the second action menu item using the tab.
4. Press the down arrow.
5. Observe that both the action menu items are opened at the same time.

### Sample code that illustrates the problem

// By Westbrook Johnson @westbrook

import { LitElement, html, customElement, TemplateResult } from "lit-element";
import "@spectrum-web-components/action-menu/sp-action-menu.js";
import "@spectrum-web-components/menu/sp-menu.js";
import "@spectrum-web-components/menu/sp-menu-item.js";
import "@spectrum-web-components/menu/sp-menu-divider.js";
import "@spectrum-web-components/menu/sp-menu-group.js";

@customElement("my-counter")
export default class MyCounter extends LitElement {
  protected render(): TemplateResult {
    return html`
      <sp-action-menu>
        <span slot="label">More Actions</span>
        <sp-menu-group>
          <span slot="header">These actions</span>
          <sp-menu-item disabled>
          Make work path
        </sp-menu-item>
      </sp-action-menu>
      <sp-action-menu>
        <span slot="label">More Actions</span>
        <sp-menu-group>
           <sp-menu-item disabled>
          Make work path
        </sp-menu-item>
      </sp-action-menu>
    `;
  }
}

### Logs taken while reproducing problem

_No response_

### LINKED ISSUE #3325: [Bug]: Overlay throws error when self-managed tooltip is removed from action-button
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay, Tooltip

### Expected behavior

When a tooltip with `self-managed` attribute has been added to an action-button and it's later removed - and the user hovers over that action-button - nothing should happen.

### Actual behavior

When a `self-managed` tooltip is removed from action-button and the user hovers over it later, overlay system throws error: 
``` 
TypeError: Cannot read properties of null (reading 'dispatchEvent')
    at n.open (https://srv.divriots.com/packd/@spectrum-web-components/action-button/sp-action-button.js,@spectrum-web-components/icon/sp-icon.js,@spectrum-web-components/icons-workflow,@spectrum-web-components/overlay/overlay-trigger.js,@spectrum-web-components/story-decorator/decorator.js,@spectrum-web-components/tooltip/sp-tooltip.js,lit-element,lit-html,lit/decorators.js,tslib:21073:6957)
    at n.open (https://srv.divriots.com/packd/@spectrum-web-components/action-button/sp-action-button.js,@spectrum-web-components/icon/sp-icon.js,@spectrum-web-components/icons-workflow,@spectrum-web-components/overlay/overlay-trigger.js,@spectrum-web-components/story-decorator/decorator.js,@spectrum-web-components/tooltip/sp-tooltip.js,lit-element,lit-html,lit/decorators.js,tslib:21073:6416)
    at openOverlay (https://srv.divriots.com/packd/@spectrum-web-components/action-button/sp-action-button.js,@spectrum-web-components/icon/sp-icon.js,@spectrum-web-components/icons-workflow,@spectrum-web-components/overlay/overlay-trigger.js,@spectrum-web-components/story-decorator/decorator.js,@spectrum-web-components/tooltip/sp-tooltip.js,lit-element,lit-html,lit/decorators.js,tslib:13762:14514)
    ``` 
   This is probably due to the fact, that removing the self-managed tooltip doesn't refresh/remove the related overlay functionality.
   This doesn't happen with wrapped action-button and tooltip inside `<overlay-trigger>` parent element as `slot="trigger"` and `slot="hover-content"` 

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/l0KvlnBLi53rKAFXgqMn/src/index.ts?p=stories
2. Wait 3 secs
3. Hover over first (left) action-button
4. Check console
5. See error

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/l0KvlnBLi53rKAFXgqMn/src/index.ts?p=stories

### Logs taken while reproducing problem

_No response_

### LINKED ISSUE #3418: [Bug]: Closing tooltip causes complete overlay chain to close too
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay, Tooltip

### Expected behavior

When we have chained overlays (example: overlay in an overlay) with an action-button in the inner overlay, that has an self-managed tooltip - clicking this action-button should close the tooltip BUT should not close the complete overlay chain.

### Actual behavior

Closing the tooltip causes closing the whole overlay chain.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

1. Go to webcomponents example
2. Click on button to trigger first level overlay
3. Click on button inside that first level overlay to trigger second level
4. Hover over 1st action-button to reveal tooltip
5. Click action-button
6. See tooltip dimissing, AND all overlays too

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/KJk8hzeTyHX3yVtDCkQP/src/index.ts?p=stories

### Logs taken while reproducing problem

_No response_

### LINKED ISSUE #3453: [Bug]: Popover closes when mouse clicked down within popover and releases outside of popover
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay-trigger

### Expected behavior

If user clicks on PopOver content area and accidentally move the mouse and released outside of the content area, we should keep the overlay Popover content open.

Would be ideal if the mouse down any where within the popover and if the mouse release is outside of the popover we should NOT dismiss. Only dismiss if mouse down and mouse up outside of the popover content

### Actual behavior

If user clicks on PopOver content area and accidentally move the mouse and released outside of the content area, the overlay Popover content closes.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

1. Go to: https://studio.webcomponents.dev/edit/O14Lbov4E3GdKUoYALDJ/src/index.ts?p=stories
2. Click on open PopOver button
3. Click and hold the click on Input field and drag the mouse cursor out of the Popover content
4. Release the mouse

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Update the Overlay API to leverage `<dialog>` elements and the `popover` API as outlined in [this discussion](https://github.com/adobe/spectrum-web-components/discussions/2764).

### To do:
- [ ] Update VRTs, I've left this off, for now, in case there are any visual effective code review items
- [x] include the removal of `active-overlay` in the migration docs
- [x] figure out how to get the API table filled for `sp-overlay`
- [x] add test for streaming `Enter` in Picker
- [x] add test for `delayed` in the imperative API
- [x] review the Floating UI bug that pushed multiple updates on open to Safari
- [x] test Action Menu change event value presence when no `selects` is provided
- [x] correct open on load of submenu story

There are a lot of changes herein. To help focus review, I've sequestered specific packages/functional areas into each of the commits in this branch:
- [overlay](https://github.com/adobe/spectrum-web-components/pull/3456/commits/32b10bd8b090716cf78b5b38c463089caaff97ae)
- [dialog](https://github.com/adobe/spectrum-web-components/pull/3456/commits/3db900b4ac4d0d7b5a5a74ad2245288eed807df8)
- [tooltip](https://github.com/adobe/spectrum-web-components/pull/3456/commits/a0732dc4733bb1c4448748323f4e1b9213e5e4dd)
- [docs](https://github.com/adobe/spectrum-web-components/pull/3456/commits/c91a01dd2874d1622d5c797888a0c522f35821cf)
- [menu](https://github.com/adobe/spectrum-web-components/pull/3456/commits/8ee44068878f58ab1ff3b505572dbfd0b10de256)
- [popover](https://github.com/adobe/spectrum-web-components/pull/3456/commits/af168509f2f88892612e462ff5b315bd57fbbe3b)
- [picker, et al](https://github.com/adobe/spectrum-web-components/pull/3456/commits/03f79f07b382f47035eceed81e38dad44d2a41fa)

### Specific feature areas for deeper thought
- **[Imperative APIs](https://github.com/adobe/spectrum-web-components/pull/3456/files#diff-a376d688fa156af7bbe68bc98fb00da987f022d7ed0a6d337d74716225aaed07R59-R155)**: We're trying to warn away from them as there will always be a little bit of unexpected behavior there.
  - should they be more feature rich? less?
  - are their Dev Mode messages that we could send these users to point them away from this API
  - a little but of the code path is "left up to fate", is that OK?
- **[Overlay `[type="page"]`](https://github.com/adobe/spectrum-web-components/pull/3456/files#diff-24e59764316c5bc315377fc78e10d4d9bb641d0e392a5eec0e97e0bc4c7259acR93-R98)**
  - small feature, but it's 100% net new, so we want to make sure that we're surfacing this productively
- **[Menu system](https://github.com/adobe/spectrum-web-components/pull/3456/commits/8ee44068878f58ab1ff3b505572dbfd0b10de256)**
  - this was a massive refactor from a system that relied on having Menu Items taken on and off of the DOM to work correctly, be on the look out for Menus that fail to capture all of the Items that are provided to them, fail to capture their selection state, or fail to appropriately bind their content to keyboard navigations

## Related issue(s)
- fixes #3453
- fixes #3418
- fixes #3325
- fixes #3199
- fixes #3184
- fixes #3079
- fixes #2662
- fixes #2625
- fixes #2359
- fixes #2282
- fixes #2086
- fixes #2026
- fixes #1876
- fixes #1853
- refs #3398 
- refs #3368 
- refs #3367 
- refs #3343 
- refs #3257 
- refs #3160 
- refs #3157 
- refs #3117 
- refs #3111 
- refs #3044 
- refs #2966 
- refs #2941 
- refs #2939 
- refs #2916 
- refs #2904 
- refs #2791 
- refs #2695 
- refs #2568 
- refs #1975 
- refs #478 

## Motivation and context
Overlays are hard, we want to make it easier through the magic of browsers.

## How has this been tested?
Rigorously, extensively, but still with the need of your help!

-   [ ] _Test case 1_
    1. In the documentation side, visit the following pages
        - [Action Menu](https://overlay-mixins--spectrum-web-components.netlify.app/components/action-menu/)
        - [Dialog](https://overlay-mixins--spectrum-web-components.netlify.app/components/dialog/)
        - [Dialog Base](https://overlay-mixins--spectrum-web-components.netlify.app/components/dialog-base/)
        - [Dialog Wrapper](https://overlay-mixins--spectrum-web-components.netlify.app/components/dialog-wrapper/)
        - [Menu](https://overlay-mixins--spectrum-web-components.netlify.app/components/menu/)
        - [Menu Group](https://overlay-mixins--spectrum-web-components.netlify.app/components/menu-group/)
        - [Menu Item](https://overlay-mixins--spectrum-web-components.netlify.app/components/menu-item/)
        - [Overlay](https://overlay-mixins--spectrum-web-components.netlify.app/components/overlay/)
        - [Overlay Imperative API](https://overlay-mixins--spectrum-web-components.netlify.app/components/imperative-api/)
        - [Overlay Trigger](https://overlay-mixins--spectrum-web-components.netlify.app/components/overlay-trigger/)
        - [Picker](https://overlay-mixins--spectrum-web-components.netlify.app/components/picker/)
        - [Split Button](https://overlay-mixins--spectrum-web-components.netlify.app/components/split-button/)
        - [Tooltip](https://overlay-mixins--spectrum-web-components.netlify.app/components/tooltip/) 
    3. Experiment with the various demos and ensure that the attributes outlined therein work as expected
-   [ ] _Test case 2_
    1. In the Storybook, visit the following sections:
        - [Action Menu](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/action-menu--default)
        - [Dialog Base](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/dialog-base--slotted)
        - [Dialog Wrapped](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/dialog-wrapped--wrapper-labeled-hero)
        - [Dialog](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/dialog--small)
        - [Menu](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/menu--default) especially [Sub Menu](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/menu-submenu--submenu)
        - [Overlay Element](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/overlay-element--modal)
        - [Overlay](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/overlay--default)
        - [Picker](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/picker--default)
        - [Split Button](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/split-button-accent-field--s)
        - [Tooltip](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/tooltip--self-managed)
    3. Ensure that the stories and their customization via the UI and navigation all work as expected

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to change)
-   [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

### CODE REVIEW

File: packages/overlay/src/Overlay.ts [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+                    restored = true;
+                }
+                requestAnimationFrame(() => {
+                    overlay.remove();
+                });
+            });
+            overlay.open = false;
+            overlay.dispose = noop;
+        };
+        let restored = false;
```
Comment (hunterloftis) [inline packages/overlay/src/Overlay.ts:94]: Can we move this line up to line 81, so `restored` is defined before it's used? Hoisting will technically take care of that for us but it makes it harder to read.

File: packages/overlay/imperative-api.md [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+Primarily, this class gives you access to the `open` method that will allow you to open an overlay:
+
+```js
+Overlay.open(
+    (overlayElement: HTMLElement), // the element that will be projected into the overlay, "content",
+    (options?: OverlayOptions)
+);
+```
+
+`Overlay.open()` is an asynchronous method that returns an `<sp-overlay>` element that wraps the `HTMLElement` provided as the `overlayElement`. While this process will set the `<sp-overlay>` element to `open`, consumers of this API will need to chose where to append this element to the DOM in order for the content to be made available in the browser.
```
Comment (hunterloftis) [inline packages/overlay/imperative-api.md:29]:
```suggestion
`Overlay.open()` is an asynchronous method that returns an `<sp-overlay>` element that wraps the `HTMLElement` provided as the `overlayElement`. While this process will set the `<sp-overlay>` element to `open`, consumers of this API will need to choose where to append this element to the DOM in order for the content to be made available in the browser.
```

File: packages/overlay/imperative-api.md [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+        placement: 'bottom',
+        trigger: document.querySelector('#trigger'),
+        type: 'auto',
+    };
+    const overlay = await Overlay.open(content, options);
+    document.body.append(overlay);
+})();
+```
+
+Keep in mind that a changing DOM tree can update the relationship between existing content and the CSS that you have applied to it when appending the `<sp-overlay>` element to your existing DOM.
```
Comment (hunterloftis) [inline packages/overlay/imperative-api.md:45]: Should we also warn about the other things that break like event bubbling & query selectors?

File: packages/overlay/imperative-api.md [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+    placement?: Placement;
+    receivesFocus?: 'auto' | 'true' | 'false';
+    trigger?: HTMLElement | VirtualTrigger;
+    type?: 'modal' | 'page' | 'hint' | 'auto' | 'manual';
+};
+```
+
+### delayed
+
+An Overlay that is `delayed` will wait until a warm-up period has completed before opening. Once the warmup period has completed, all subsequent Overlays will open immediately. When no Overlays are opened, a cooldown period will begin. Once the cooldown has completed, the next Overlay to be opened will be subject to the warm-up period if provided that option.
```
Comment (hunterloftis) [inline packages/overlay/imperative-api.md:65]: Are the warmup & cooldown periods fixed, & specified by SWC / Spectrum? If so, we should note that here.

File: packages/overlay/imperative-api.md [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+
+### notImmediatelyCloseable
+
+When an Overlay is `notImmediatelyCloseable` that means that the first interaction that would lead to the closure of the Overlay in question will be ignored. This is useful when working with non-"click" mouse interactions, like `contextmenu`, where the trigger event (e.g. `contextmenu`) occurs _before_ an event that would close said overlay (e.g. `pointerup`).
```
Comment (hunterloftis) [inline packages/overlay/imperative-api.md:69]: 👍 good example, otherwise I'd be scratching my head about the motivation

File: packages/overlay/imperative-api.md [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+
+A `placement` of `"auto" | "auto-start" | "auto-end" | "top" | "bottom" | "right" | "left" | "top-start" | "top-end" | "bottom-start" | "bottom-end" | "right-start" | "right-end" | "left-start" | "left-end"` will instruct the Overlay where to place itself in relationship to the trigger element.
+
+### receivesFocus
+
+Some Overlays will always be passed focus (e.g. modal or page Overlays). When this is not true, the `receivesFocus` option will inform the API whether to attempt to pass focus into the Overlay once it is open. `'true'` will pass focus, `'false'` will not (when possible), and `"auto"` (the default), will make a decision based on the `type` of the Overlay.
+
+### trigger
+
+The `trigger` option accepts an `HTMLElement` or a `VirtualTrigger` from which to position the Overlay.
```
Comment (hunterloftis) [inline packages/overlay/imperative-api.md:85]: Several of these options reference a trigger. Should we specify here the side-effects of not providing a trigger, with an example of why you'd use or not use one?

File: packages/overlay/imperative-api.md [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+
+### type
+
+The `type` of an Overlay outlines a number of things about the interaction model within which is works.
+
+-   `'modal'` Overlays are opened with the `showModal()` method on a `<dialog>` element, which causes the Overlay to accept focus and trap the tab stop within the content of said Overlay.
+-   `'page'` Overlays will act in a similar manner to a `'modal'` Overlay, however they will not be allowed to close via the "light dismiss" algorithm (e.g. the Escape key).
+-   `'hint'` Overlays are much like tooltips so they are not just ephemeral, but they are delivered primarily as a visual helper and exist outside of the tab order. In this way, be sure _not_ be palce interactive content within this type of Overlay.
```
Comment (hunterloftis) [inline packages/overlay/imperative-api.md:93]:
```suggestion
-   `'hint'` Overlays are much like tooltips so they are not just ephemeral, but they are delivered primarily as a visual helper and exist outside of the tab order. In this way, be sure _not_ to place interactive content within this type of Overlay.
```

File: packages/overlay/src/Overlay.ts [hunk 8]
```diff
@@ -0,0 +1,156 @@
...
+        const restoreContent = reparentChildren([overlayContent], overlay, {
+            position: 'beforeend',
+            prepareCallback: (el) => {
+                const slot = el.slot;
+                el.removeAttribute('slot');
+                return () => {
+                    el.slot = slot;
+                };
+            },
```
Comment (hunterloftis) [inline packages/overlay/src/Overlay.ts:103]: My naive assumption was that only the v2 branch would reparent nodes - this (or the top of this file) might be a good place for a 1-paragraph overview of the mechanisms of how Overlay works under the hood.

Is the purpose of this to make sure that if overlaid content is projected into a light DOM slot, that it's not projected when it's in the overlay container (so it's visible outside of its "normal" slot environment), and then restored afterwards?

**Comment by hunterloftis** [comment]
Some early clarification questions as I start to review -

> We're trying to warn away from them as there will always be a little bit of unexpected behavior there.

What kind of unexpected behavior?

> a little but of the code path is "left up to fate"

What does this mean exactly?

File: packages/overlay/src/Overlay.ts [hunk 9]
```diff
@@ -0,0 +1,156 @@
...
+        });
+        if (v2) {
+            const options = interactionOrOptions as OverlayOptions;
+            overlay.append(overlayContent);
+            overlay.receivesFocus = options.receivesFocus ?? 'auto';
+            overlay.triggerElement = options.trigger || null;
+            overlay.type = options.type || 'modal';
+            overlay.offset = options.offset || 6;
```
Comment (hunterloftis) [inline packages/overlay/src/Overlay.ts:111]: Unless we want to disallow `offset === 0`:

```suggestion
            overlay.offset = options.offset ?? 6;
```

File: packages/overlay/src/Overlay.ts [hunk 10]
```diff
@@ -0,0 +1,156 @@
...
+            overlay.placement = options.placement;
+            overlay.willPreventClose = !!options.notImmediatelyClosable;
+            requestAnimationFrame(() => {
+                requestAnimationFrame(() => {
+                    // Do we want to "open" this path, or leave that to the consumer?
+                    overlay.open = true;
+                });
+            });
```
Comment (hunterloftis) [inline packages/overlay/src/Overlay.ts:119]: Are there guarantees we've made so we can rely on 2 frames always being perfect timing for this?

Is there an event we could listen for instead of timing this out by frame?

File: packages/overlay/src/Overlay.ts [hunk 11]
```diff
@@ -0,0 +1,156 @@
...
+            return overlay;
+        } else if (overlayContent && options) {
```
Comment (hunterloftis) [inline packages/overlay/src/Overlay.ts:121]: Do we expect this to run anytime we're exiting early via "v2" mode? If so, maybe we should delete the branch & satisfy TS that the required values exist like:
 
```suggestion
const v1 = !v2 && overlayContent && options;
if (!v1) {
  // good place for a dev mode warning about satisfying neither V1 nor V2 overlay argument requirements
  return;
}
```

Comment (hunterloftis) [reply packages/overlay/src/Overlay.ts:121]: Edit: I see sometimes we `return overlay` and sometimes `return overlay.dispose`, so maybe this *is* an optional branch and not just the v1 fallback.

File: packages/overlay/src/Overlay.ts [hunk 12]
```diff
@@ -0,0 +1,156 @@
...
+                }
+                requestAnimationFrame(() => {
+                    overlay.remove();
+                });
+            });
+            overlay.open = false;
+            overlay.dispose = noop;
+        };
+        let restored = false;
+        const restoreContent = reparentChildren([overlayContent], overlay, {
```
Comment (hunterloftis) [inline packages/overlay/src/Overlay.ts:95]:
```suggestion
        // Since content must exist in an <sp-overlay>, we need a way to get it there.
        // The best & most-direct way is to declaratively use an <sp-overlay> element,
        // but for imperative users, we'll reparent content into an overlay that we've created for them.
        const restoreContent = reparentChildren([overlayContent], overlay, {
```

File: packages/overlay/src/Overlay.ts [hunk 13]
```diff
@@ -0,0 +1,156 @@
...
+            // Having an option is likely useful.
+            // Make imperative overlays less useful?
+            // Delete the imperative approach to an overlay?
+            // Possibly the giving all of the responsiblities to the user is the best path.
+            const parent = target.getRootNode() as Document;
+            if (parent === document) {
+                target.insertAdjacentElement('afterend', overlay);
+            } else {
+                parent.append(overlay);
+            }
```
Comment (hunterloftis) [inline packages/overlay/src/Overlay.ts:146]: Using the root (either body or the shadow root) minimizes the chance of stray CSS impacting overlay content, and of our injected elements breaking DOM requirements for the user. But we should note that in *imperative* API usage, overlays are added to the *bottom* of their document's root, which is not naturally the next tab stop after their trigger... so it's on the user to ensure accessible tab behavior.

```suggestion
            const parent = target.getRootNode() as Document;
            const root = parent === document ? document.body : parent;
            root.append(overlay);
```

File: packages/overlay/src/Overlay.ts (hunk 10 above)
Comment (Westbrook) [reply packages/overlay/src/Overlay.ts:119]: This makes the assumption that the API consumer is immediately attaching the element to the DOM, so as to complete the `.open()` workflow. Two rAFs is the required timing to ensure that the append has occurred and the initial styling has been painted so that the open animation can occur as expected.

Possible alternative:
- `overlay.updateComplete.then(...)`, it _is_ a LitElement after all. not sure this fully accounts for the _next frame_ of the double rAF approach
- not opening the overlay and letting the consumer do it
- thoughts?

File: packages/overlay/src/OverlayBase.ts [hunk 14]
```diff
@@ -0,0 +1,891 @@
...
+
+export type LongpressEvent = {
+    source: 'pointer' | 'keyboard';
+};
+
+export const LONGPRESS_INSTRUCTIONS = {
+    touch: 'Double tap and long press for additional options',
+    keyboard: 'Press Space or Alt+Down Arrow for additional options',
+    mouse: 'Click and hold for additional options',
+};
```
[the remark this answers is not in the document]
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts:64]: Like so many things: https://github.com/adobe/spectrum-web-components/issues/1975

This content is not currently localizable, so this is amounts to a 1:1 conversion from the previous API.

File: packages/overlay/src/Overlay.ts (hunk 13 above)
Comment (Westbrook) [reply packages/overlay/src/Overlay.ts:146]: I take this back, for right now, as it caused test to fail. The following fits better to the tests that have already been written, and to the expected tab order, even if it is more likely to cause issues as it interacts with CSS rules.
```ts
target.insertAdjacentElement('afterend', overlay);
```

We're just about ready for a new RC and then we can test this new assumption against consuming application before locking it down.

File: packages/overlay/src/Overlay.ts (hunk 10 above)
Comment (hunterloftis) [reply packages/overlay/src/Overlay.ts]: If tests pass with it, I'd go for `overlay.updateComplete.then(...)`.

If that causes tests to fail, then we could put a pin in this for now. Using RAFs feels brittle, but other than your example of not appending immediately, I can't prove that this would break in any way.

File: packages/overlay/src/fullSizePlugin.ts [hunk 15]
```diff
@@ -0,0 +1,62 @@
...
+*/
+import {
+    detectOverflow,
+    MiddlewareArguments,
+    MiddlewareReturn,
+} from '@floating-ui/dom';
+
+export const fullSize = (options: { padding: number } = { padding: 0 }) => ({
+    name: 'fullSize',
+    async fn(middlewareArguments: MiddlewareArguments): Promise<
```
Comment (nickschaap) [inline packages/overlay/src/fullSizePlugin.ts:20]:
```suggestion
    async fn(middlewareArguments: MiddlewareState): Promise<
```

File: packages/overlay/src/OverlayBase.ts [hunk 16]
```diff
@@ -0,0 +1,891 @@
...
+            guarantee3 = requestAnimationFrame(() => {
+                cleanup();
+            });
+        });
+    });
+    const handleTransitionend = (event: TransitionEvent): void => {
+        if (event.propertyName === 'visibility') {
+            // Ignore "visibility" transitions because they often happen before/after a
+            // larger transition and don't represent the overall transition duration.
+            return;
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:126]: Should we document this exception, or are visibility-only transitions rare enough to assume they don't happen?

File: packages/overlay/src/OverlayBase.ts [hunk 17]
```diff
@@ -0,0 +1,891 @@
...
+        }
+        cancelAnimationFrame(guarantee1);
+        cancelAnimationFrame(guarantee2);
+        cancelAnimationFrame(guarantee3);
+        el.removeEventListener('transitionrun', handleTransitionrun);
+        el.addEventListener('transitionend', handleTransitionend);
+    };
+    el.addEventListener('transitionrun', handleTransitionrun);
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:142]: Would this work, & also allow us to delete `cleanup` in favor of calling `cb()` directly?

```suggestion
        el.addEventListener('transitionend', handleTransitionend, { once: true });
    };
    el.addEventListener('transitionrun', handleTransitionrun, { once: true });
```

File: packages/overlay/src/OverlayBase.ts (hunk 16 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts:126]: Often what happens in this:
```
    transition: transform 0.5s ease-in-out,
        opacity 0.5s ease-in-out,
        visibility 0s linear;
```
The goal is to go from "invisible" to "visible" _immediately_, while transitioning other values at a slower rate. At it is matched with the following:
```
    transition: transform 0.5s ease-in-out,
        opacity 0.5s ease-in-out,
        visibility 0s linear 0.5s;
```
Where the goal is to transition over values at a slower rate and then at the very edit of the transition switch form "visible" to "invisible" _immediately_.

The other path I thought of here was to count up the `transitionrun` events, and then count down the `transitionend` events, so we could know 100% that _ALL_ of the transitions had completed. Let me know if you think that would be better here than the `visibility` caveats that currently are leveraged.

File: packages/overlay/src/OverlayBase.ts [hunk 18]
```diff
@@ -0,0 +1,891 @@
...
+    set disabled(disabled: boolean) {
+        this._disabled = disabled;
+        if (disabled) {
+            if (this.hasNonVirtualTrigger) {
+                this.unbindEvents(this.triggerElement as HTMLElement);
+            }
+            this.wasOpen = this.open;
+            this.open = false;
+        } else {
+            this.bindEvents();
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:172]: totally a nit, but it would be nice if `bindEvents` and `unbindEvents` could be symmetrical - either binding based on internal state like `this.triggerElement`, or binding arbitrarily based on an element passed in as an argument.

File: packages/overlay/src/OverlayBase.ts [hunk 19]
```diff
@@ -0,0 +1,891 @@
...
+            this.wasOpen = false;
+        }
+    }
+
+    private _disabled = false;
+
+    protected dispose = noop;
+
+    @queryAssignedElements({
+        selector: ':not([slot="longpress-describedby-descriptor"])',
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:183]: For posterity, maybe a single line comment explaining this? Pure guess here:

```suggestion
        // the one type of child that we expect an overlay to have that can't be opened & presented is slotted
        // into the longpress-describedby-descriptior slot for accessibility
        selector: ':not([slot="longpress-describedby-descriptor"])',
```

File: packages/overlay/src/OverlayBase.ts [hunk 20]
```diff
@@ -0,0 +1,890 @@
...
+    }
+
+    protected async managePopoverOpen(): Promise<void> {
+        console.warn(
+            'Implement the `managePopoverOpen` method in a class extension.'
+        );
+    }
+
+    protected get requiresPosition(): boolean {
+        // Do no position "page" overlays as they should block the entrie UI.
```
Comment (najikahalsema) [inline packages/overlay/src/OverlayBase.ts:283]: `// Do not position "page" overlays as they should block the entire UI.`

File: packages/menu/src/Menu.ts [hunk 21]
```diff
@@ -190,35 +213,33 @@ export class Menu extends SpectrumElement {
...
+        );
         if (
             (selects || (!this.selects && this.resolvedSelects !== 'ignore')) &&
             !event.item.menuData.selectionRoot
         ) {
             event.item.setRole(this.childRole);
-            event.selectionRoot = this;
+            event.item.menuData.selectionRoot =
+                event.item.menuData.selectionRoot || this;
+            if (event.item.selected) {
```
Comment (najikahalsema) [inline packages/menu/src/Menu.ts:237]: I noticed that the submenu items aren't maintaining their selection state once the menu is reopened, like in [this example](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/menu-submenu--submenu). Is this logic potentially not saving the selection state, or is the expected behaviour supposed to be that the selection doesn't persist? This is how it worked in the previous version, if I recall, though, so it's not a huge deal if it isn't fixed. Just wanted to mention it. It seems like unexpected behaviour to me.

Comment (najikahalsema) [reply packages/menu/src/Menu.ts:237]: Or, I guess my question would be, if we want the selected item to persist, does this put us on a good path forward to address that in the future?

File: packages/overlay/src/OverlayBase.ts (hunk 19 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts:183]: Seems we might not actually need that. 🤞🏼

File: packages/menu/src/Menu.ts (hunk 21 above)
Comment (Westbrook) [reply packages/menu/src/Menu.ts:237]: The story you linked here does not _ever_ have selection state, as it's an Action Menu.

[This story](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/menu-submenu--context-menu) has selection state, but the story is not written in such a way as to persist it (previously, too). I'll look into what would be needed so we could do that as a proof case.

File: packages/overlay/src/OverlayBase.ts (hunk 17 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts:142]: Address via:

> The other path I thought of here was to count up the transitionrun events, and then count down the transitionend events, so we could know 100% that ALL of the transitions had completed. Let me know if you think that would be better here than the visibility caveats that currently are leveraged.

File: packages/overlay/README.md [hunk 22]
```diff
@@ -11,190 +11,265 @@ Overlays in Spectrum Web Components are created via the `Overlay` class system,
...
+    ?open=${boolean}
+    ?delayed=${boolean}
+    offset=${Number | [Number, Number]}
+    placement=${Placement}
+    receives-focus=${'true' | 'false' | 'auto' (default)
+    trigger=${string | ${string}@${string}}
+    .triggerElement=${HTMLElement}
+    .triggerInteraction=${'click' | 'longpress' | 'hover'}
+    type=${'auto' | 'hint' | 'manual' | 'modal' | 'page'}
+></sp-overlay>
```
[the remark this answers is not in the document]
Comment (najikahalsema) [reply packages/overlay/README.md:156]: Ah, that looks better. I saw it on the overlay commit, I believe.

File: packages/menu/src/MenuItem.ts
Comment (najikahalsema) [inline packages/menu/src/MenuItem.ts:1]: These changes look good to me. Much cleaner and robust. Thank you for your hard work here!

File: projects/documentation/content/migrations/2023-6-11.md [hunk 23]
```diff
@@ -0,0 +1,97 @@
+---
+layout: guide.njk
+title: 'Migration Guide: Spectrum Web Components'
+displayName: 2023/6/11
+slug: migration-guide
+---
+
+## Migration: 2023/6/11
+
+As of the 0.33.0 release of the Spectrum Web Components library, we will be leveraging a new version of our Overlay API. We've done our best to ensure a smooth transition from one version of the API to the next, including adding extended support for the argument signature from the previous version. In this way, consumption of elements from the library (e.g. `<overlay-trigger>`, `<sp-picker>`, `<sp-tooltip>`, et al.) or the imperative Overlay API (e.g. `Overlay.open()`) should continue to afford as close to the same functionality as the provided you in the past. Under the covers, many important changes have been made and there are several things you can do in preparation for those changes in your application's lifecycle.
```
Comment (najikahalsema) [inline projects/documentation/content/migrations/2023-6-11.md]: As of the 0.33.0 release of the Spectrum Web Components library, we will be leveraging a new version of our Overlay API. We've done our best to ensure a smooth transition from one version of the API to the next, including adding extended support for the argument signature from the previous version. In this way, consumption of elements from the library (e.g. `<overlay-trigger>`, `<sp-picker>`, `<sp-tooltip>`, et al.) or the imperative Overlay API (e.g. `Overlay.open()`) should continue affording the closest functionality as what was provided to you in the past. Under the covers, many important changes have been made and there are several things you can do to prepare within your application's lifecycle.

File: projects/documentation/content/migrations/2023-6-11.md [hunk 24]
```diff
@@ -0,0 +1,97 @@
...
+    <sp-tooltip slot="hover-content" placement="right">
+        Tooltip for the trigger
+    </sp-tooltip>
+    <!-- etc. -->
+</overlay-trigger>
+```
+
+### Remove usage of `placement="none"` in both declarative and imperative API usages
+
+`placement="none"` or `placement: 'none'` was previously leveraged to outline an overlay that would take the full size of the viewport, this responsibility is now fulfilled by assigning this value as `undefined`, or, better yet, not including it at all.
```
Comment (najikahalsema) [inline projects/documentation/content/migrations/2023-6-11.md]: > `placement="none"` or `placement: 'none'` was previously leveraged to outline an overlay that would take the full size of the viewport. This responsibility is now fulfilled by assigning this value as `undefined`, or, better yet, by not including it at all.`

Grammar nits

File: projects/documentation/content/migrations/2023-6-11.md [hunk 25]
```diff
@@ -0,0 +1,97 @@
...
+                // Do something when the event was dispatched for an overlay with type "modal".
+            }
+        }}
+    ></element-containing-an-overlay>
+`;
+```
+
+### Prepare for descendant overlays to exist in the same DOM tree
+
+Previously, the reparenting of overlay content prevented `sp-opened` and `sp-closed` events from bubbling as would normally be the default. This means you will have the opportunity to hear and respond to these events ALL in a centralized location, but your listeners may hear more of these events than you expect and/or had previously.
```
Comment (najikahalsema) [inline projects/documentation/content/migrations/2023-6-11.md]: > Previously, the reparenting of overlay content prevented `sp-opened` and `sp-closed` events from bubbling, which would normally be the default. This means you will have the opportunity to hear and respond to ALL these events in a singular location, but your listeners may hear more of these events than you expect and/or had previously.

I don't know if "ALL these events" is accurate as opposed to they ALL are responded to in a single location, but I think saying singular rather than centralised makes more sense.

File: projects/documentation/content/migrations/2023-6-11.md [hunk 26]
```diff
@@ -0,0 +1,97 @@
...
...ping and stacking. While this approach was good at overcoming these realities, the reparenting of the overlaid content required to apply this technique had high-performance costs for constantly reorienting elements to a new parent and broke encapsulation, making it difficult to take full control of the delivery of that content as far as styling. In exchange, the new API will leverage `<dialog>` elements and the `showModal()` method for modal overlays and the `popover` attribute along with the `showPopover()` method they add to elements to which they are applied. Both of these APIs lift content onto the [top layer](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer) of the browser which provides a full guarantee against CSS clipping and stacking interrupting the content addressed to this layer. Be aware that content on this layer is managed as a strict stack, so the last added will always be "on top" regardless of any additional CSS you may apply. [A discussion](https://github.com/adobe/spectrum-web-components/discussions/2764#discussioncomment-5327797) around additional features that could address this reality is ongoing, please jump in with your thoughts if you have them.
```
Comment (najikahalsema) [inline projects/documentation/content/migrations/2023-6-11.md]: > The new version of the Overlay API no longer relies on portalling (moving content to the end of the `<body>` element) to defeat CSS clipping and stacking. While this approach was good at overcoming those realities, the reparenting of the overlaid content required to apply this technique had high performance costs, because it was constantly reorienting elements to a new parent and broke encapsulation. This made it difficult to take full control of styling and delivering overlaid content. In exchange, the new API will leverage `<dialog>` elements and the `showModal()` method for modal overlays, and the `popover` attribute along with the `showPopover()` method added to elements to which they are applied. Both of these APIs lift content onto the [top layer](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer) of the browser, which provides a full guarantee against CSS clipping and stacking interrupting the content addressed to this layer. Be aware that content on this layer is managed as a strict stack, so the element added last will always be "on top", regardless of any additional CSS you may apply. [A discussion](https://github.com/adobe/spectrum-web-components/discussions/2764#discussioncomment-5327797) around additional features that could address this reality is ongoing; please jump in with your thoughts if you have them.

Comment (najikahalsema) [reply projects/documentation/content/migrations/2023-6-11.md]: I think these changes make the content here clearer to understand.

**Review by najikahalsema — COMMENTED** [review]
Just some teeny comments on the documentation for migrating

File: packages/overlay/src/OverlayBase.ts (hunk 16 above)
Comment (hunterloftis) [reply packages/overlay/src/OverlayBase.ts:126]: > The other path I thought of here was to count up the transitionrun events, and then count down the transitionend events, so we could know 100% that ALL of the transitions had completed. Let me know if you think that would be better here than the visibility caveats that currently are leveraged.

❤️  perfect

File: packages/overlay/src/OverlayBase.ts [hunk 27]
```diff
@@ -0,0 +1,893 @@
...
+
+    @property({ type: Boolean, reflect: true })
+    get open(): boolean {
+        return this._open;
+    }
+
+    set open(open: boolean) {
+        if (open && this.disabled) return;
+        if (open === this.open) return;
+        this._open = open;
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:214]: Would this be a better place to put `OverlayBase.openCount += 1` than `manageOpen`, in that it's a more reliable place to track the ultimate opening & closing of overlays?

(unless I misunderstand what `openCount` is for)

**Review by najikahalsema — CHANGES_REQUESTED** [review]
I went through all the files. While the actual overlay stuff is a leeeeedle more complex than I'm used to, the changes all look super great and in line with what we've discussed as a team over the last year. In particular, I think the dialogue refactor is going to be so important for our consumers in solving their design challenges and the stories really make that clear in a way they weren't before. I think all the stories got a great bump to their visual/interactive usefulness for which I am grateful. This is no small feat and I'M SO GLAD THAT THIS IS SO CLOSE TO BEING DONE!!!! I think if you are able to find and fix that visual bug and make a few changes to the documentation that I said in my comments, it should be good to go!!!!!

File: packages/overlay/README.md [hunk 28]
```diff
@@ -11,190 +11,274 @@ Overlays in Spectrum Web Components are created via the `Overlay` class system,
...
 
-`hover` will close the overlay as soon as the pointer leaves the trigger to which the overlay is connected.
+-   `transition*` events bubble; this means that while transition events on light DOM content of those direct children will be heard, those events will not be taken into account
+-   `transition*` events are not composed; this means that transition events on shadow DOM content of the direct children will not propagate to a level in the DOM where they can be heard
 
-`inline` places the overlay after the trigger but before the next element in the logical tab order. This means the `shift + tab` keyboard stroke will return to the trigger.
+This means that in both cases, if the transition is meant to be a part of the opening or closing of the overlay in question you will need to redispatch the `transitionrun` and `transitionend` events from that transition from the closest direct child of the `<sp-overlay>`.
```
Comment (Westbrook) [inline packages/overlay/README.md:167]: @hunterloftis, added this section in association with the API changes we discussed this morning for `guaranteedAllTransitionend`.

File: packages/overlay/src/OverlayBase.ts (hunk 16 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts]: Please checkout the additional docs to go with this.

File: projects/documentation/content/migrations/2023-6-11.md (hunk 25 above)
Comment (Westbrook) [reply projects/documentation/content/migrations/2023-6-11.md]: Edited again to try to get your suggestions and the meaning here:
> Previously, the reparenting of overlay content prevented `sp-opened` and `sp-closed` events from propagating through the overlay's ancestor DOM tree. Going forward these events will propagate in a more native manner meaning that an ancestor will have the opportunity to hear and respond to ALL `sp-opened` and `sp-closed` events for all of its descendant overlays.

File: packages/overlay/README.md (hunk 28 above)
Comment (hunterloftis) [reply packages/overlay/README.md:167]: I didn't even consider composition and bubbling, TIL

File: packages/overlay/README.md [hunk 29]
```diff
@@ -27,7 +27,7 @@ import {
...
+Leverage the `trigger` attribute to pass an ID reference to another element with in the same DOM tree, your overlay will be positioned in relation to this element. When the ID reference is followed by an `@` symbol and interaction type, like `click`, `hover`, or `longpress`, the overlay will bind itself to the referenced element via the DOM events associated with that interaction. For example, the `<sp-button>` below has an id of `trigger`, and the `<sp-overlay>` is provided the `trigger` attribute with the value `trigger@click`. This creates an association between the overlay and the `<sp-button>` that opens the overlay when the button is clicked.
```
Comment (najikahalsema) [inline packages/overlay/README.md:30]: Maybe "By leveraging" ? 
This is much clearer to me. Thank you!

**Review by najikahalsema — DISMISSED** [review]
Looks good to me !!!

File: packages/overlay/src/OverlayBase.ts [hunk 30]
```diff
@@ -0,0 +1,908 @@
...
+        console.warn(
+            'Implement the `manageDialogOpen` method in a class extension.'
+        );
+    }
+
+    protected async managePopoverOpen(): Promise<void> {
+        console.warn(
+            'Implement the `managePopoverOpen` method in a class extension.'
+        );
+    }
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:295]: Should we guard these console warnings behind dev mode?

File: packages/overlay/src/OverlayBase.ts [hunk 31]
```diff
@@ -0,0 +1,908 @@
...
+
+    protected get requiresPosition(): boolean {
+        // Do not position "page" overlays as they should block the entire UI.
+        if (this.type === 'page' || !this.open) return false;
+        // Do not position content without a trigger element, what would you position it in relation to?
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:300]: Seems like this is one of the things to document for https://github.com/adobe/spectrum-web-components/pull/3456#discussion_r1268611639

File: packages/overlay/src/OverlayBase.ts [hunk 32]
```diff
@@ -0,0 +1,908 @@
...
+        // Do not automaticallyu position contnent, unless it is a "hint".
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:301]:
```suggestion
        // Do not automatically position contnent, unless it is a "hint".
```

File: packages/overlay/src/OverlayBase.ts [hunk 33]
```diff
@@ -0,0 +1,908 @@
...
+            offset,
+            placement,
+            tipPadding,
+            trigger,
+            type: this.type,
+        });
+    }
+
+    protected async manageOpen(oldOpen: boolean): Promise<void> {
+        if (!this.isConnected && this.open) return;
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:325]: A comment here could be handy - it's not immediately clear to me why nodes that are both disconnected and open don't need to `manageOpen`, but all others do.

File: packages/overlay/src/OverlayBase.ts [hunk 34]
```diff
@@ -0,0 +1,908 @@
...
+                        currentNode.assignedSlot ||
+                        currentNode.parentElement ||
+                        (currentNode.getRootNode() as ShadowRoot)?.host;
+                    if (ancestor) {
+                        ancestors.push(ancestor as HTMLElement);
+                    }
+                    currentNode = ancestor;
+                }
+                return ancestors;
+            };
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:387]: Looks like it could be a great helper utility (`getComposedAncestors`?)

File: packages/overlay/src/OverlayBase.ts [hunk 35]
```diff
@@ -0,0 +1,908 @@
...
+            if (
+                (this.triggerElement as HTMLElement)?.focus &&
+                (this.contains(
+                    (this.getRootNode() as Document).activeElement
+                ) ||
+                    !!getAncestors().find((el) => el === this))
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:393]: Is this equivalent?

```suggestion
                    getAncestors().includes(this)
```

File: packages/overlay/src/OverlayBase.ts [hunk 36]
```diff
@@ -0,0 +1,908 @@
...
+            ) {
+                (this.triggerElement as HTMLElement).focus();
+            }
+        }
+    }
+
+    protected unbindEvents(triggerElement: HTMLElement): void {
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:400]: There's a lot of bookkeeping here... if there are discrete, logically-related groups of listeners, it might make sense to cancel them via one or more [AbortControllers](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

File: packages/overlay/src/OverlayBase.ts [hunk 37]
```diff
@@ -0,0 +1,908 @@
...
+            this.handlePointerenter
+        );
+        triggerElement.addEventListener(
+            'pointerleave',
+            this.handlePointerleave
+        );
+        this.addEventListener('pointerleave', this.handleOverlayPointerleave);
+        if (this.receivesFocus === 'true') return;
+
+        this.prepareAriaDescribedby(triggerElement);
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:475]: nit: it feels like this doesn't fit into the function `bindHoverEvents`. Since `prepareAriaDescribedby` starts with guards for proper usage, maybe it should be called from a general initialization function like `connectedCallback` (single setup) or `updated` (if we want it to dynamically respond to changes)?

(no need for action, just a note to consider)

File: packages/overlay/src/OverlayBase.ts [hunk 38]
```diff
@@ -0,0 +1,908 @@
...
+            this.releaseAriaDescribedby();
+        }
+        if (
+            !this.triggerElement ||
+            !!(this.triggerElement as VirtualTrigger).updateBoundingClientRect
+        ) {
+            return;
+        }
+        this.bindEvents(this.triggerElement);
+    }
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:490]: Do these annotations capture the goal of the function accurately?

```suggestion
    protected manageTriggerElement(triggerElement: HTMLElement | null): void {
        if (triggerElement) {
            this.unbindEvents(triggerElement);
            this.releaseAriaDescribedby();
        }
        const missingOrVirtual = !this.triggerElement || this.triggerElement instanceof VirtualTrigger;
        if (missingOrVirtual) {
            return;
        }
        this.bindEvents(this.triggerElement);
    }
```

File: packages/overlay/src/OverlayBase.ts [hunk 39]
```diff
@@ -0,0 +1,908 @@
...
+            // require "longpress content" to apply relationship
+            !this.elements.length
+        ) {
+            return;
+        }
+
+        const longpressDescription = document.createElement('div');
+        longpressDescription.id = `longpress-describedby-descriptor-${crypto
+            .randomUUID()
+            .slice(0, 8)}`;
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:509]: On some browsers, `crypto.randomUUID()` will fail outside of a secure context.

File: packages/overlay/src/OverlayBase.ts [hunk 40]
```diff
@@ -0,0 +1,908 @@
...
+                releaseAriaDescribedby();
+                this.releaseAriaDescribedby = noop;
+            };
+        } else if (triggerRoot === contentRoot) {
+            this.elementIds = this.elements.map((el) => el.id);
+            const appliedIds = this.elements.map((el) => {
+                if (!el.id) {
+                    el.id = `${this.tagName.toLowerCase()}-helper-${crypto
+                        .randomUUID()
+                        .slice(0, 8)}`;
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:558]: Another `crypto.randomUUID()` here - ok as long as we never expect to execute this in HTTP (vs HTTPS)

File: packages/overlay/src/OverlayBase.ts [hunk 41]
```diff
@@ -0,0 +1,908 @@
...
+                class="dialog"
+                part="dialog"
+                @close=${this.handleBrowserClose}
+                @cancel=${this.handleBrowserClose}
+                @beforetoggle=${this.handleBeforetoggle}
+                style=${styleMap({
+                    '--swc-overlay-open-count':
+                        OverlayBase.openCount.toString(),
+                    translate: this.hasUpdated ? null : '-999em -999em',
+                })}
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:852]: As long as this is only ever computed once, at first render, I get how it will capture the global `openCount` when it's opened, and use the correct z-index.

But if `renderDialog` is recomputed later, for example after `openCount` has incremented, would it not update this value (& this its z-index) to be at the wrong level?

File: packages/overlay/src/OverlayBase.ts [hunk 42]
```diff
@@ -0,0 +1,908 @@
...
+            <div
+                class="dialog"
+                part="dialog"
+                popover=${ifDefined(popoverValue)}
+                @beforetoggle=${this.handleBeforetoggle}
+                @close=${this.handleBrowserClose}
+                style=${styleMap({
+                    '--swc-overlay-z-index': (
+                        1000 + OverlayBase.openCount
+                    ).toString(),
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:874]: FMI, could you share why  Dialog & Popover use similar but slightly-different mechanisms for setting z-index?

File: packages/overlay/src/OverlayDialog.ts [hunk 43]
```diff
@@ -0,0 +1,207 @@
...
+            }
+            await this.dialogApplyFocus(targetOpenState, focusEl);
+        }
+
+        protected async dialogEnsureOnDOM(): Promise<void> {
+            await nextFrame();
+            await nextFrame();
+            await nextFrame();
+            await nextFrame();
+        }
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayDialog.ts:63]: Is there a more deterministic way to ensure it's on the DOM?

File: packages/overlay/src/OverlayDialog.ts [hunk 44]
```diff
@@ -0,0 +1,207 @@
...
+
+        protected async dialogApplyFocus(
+            targetOpenState: boolean,
+            focusEl: HTMLElement | null
+        ): Promise<void> {
+            /**
+             * Focus should handled natively in `<dialog>` elements when leveraging `.showModal()`, but it's NOT.
+             * - webkit bug: https://bugs.webkit.org/show_bug.cgi?id=255507
+             * - firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1828398
+             **/
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayDialog.ts:177]: 👍

**Comment by hunterloftis** [comment]
Verifying this is expected closing behavior for https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/action-menu--submenu

- Clicking to select/deselect closes all overlays
- Pressing enter to select/deselect closes the top overlay
- Pressing space to select/deselect closes all overlays

https://github.com/adobe/spectrum-web-components/assets/364501/522251a7-f3bb-4339-ae0b-e89fb7301892

**Comment by hunterloftis** [comment]
The very first time I interact at https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/dialog-base--slotted, I get weird (instant open-close) behavior. Based on the cursor not turning into a pointer, and the fact that I can initially click anywhere, there seems to be something between my mouse and the button. Devtools shows it as just the `<html>` of the story, which I don't trust - maybe it's something in the top-layer?

https://github.com/adobe/spectrum-web-components/assets/364501/2e0805a3-e828-492a-bfe4-12c0e918ecdf

**Comment by hunterloftis** [comment]
Also a first-click behavior, the menu at https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/menu-submenu--submenu fully opens into a deep item initially. Subsequently, it behaves as expected:


https://github.com/adobe/spectrum-web-components/assets/364501/4e54a506-6be1-4333-a2b0-2f22be72341d

**Comment by hunterloftis** [comment]
More first-interaction stuff 🙃 

Closing https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/overlay-element--modal the first time leads to a minor visual stutter:

https://github.com/adobe/spectrum-web-components/assets/364501/27b8d2ad-66c0-4c73-8582-f6cfdfa366ab

**Comment by hunterloftis** [comment]
At https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/picker--default I see a small focus-visible flash when selecting via keyboard (but not when selecting via mouse):

https://github.com/adobe/spectrum-web-components/assets/364501/35b222d8-62d9-4f86-9410-87a894da8e55

**Review by hunterloftis — DISMISSED** [review]
I read through the code & tested each component. That led to lots of suggestions and questions, but few blocking issues. LGTM whenever these are resolved:

- [X] [randomUUID restricting to secure contexts?](https://github.com/adobe/spectrum-web-components/pull/3456#discussion_r1274059485)
- [ ] [initial dialog flash](https://github.com/adobe/spectrum-web-components/pull/3456#issuecomment-1650531678)
- [x] [sub-menu opening consistency](https://github.com/adobe/spectrum-web-components/pull/3456#issuecomment-1650538075)

File: packages/menu/src/Menu.ts [hunk 45]
```diff
@@ -460,30 +523,41 @@ export class Menu extends SpectrumElement {
...
             (this.isLTR && code === 'ArrowLeft') ||
             (!this.isLTR && code === 'ArrowRight');
         if (shouldOpenSubmenu) {
+            event.stopPropagation();
             const lastFocusedItem = this.childItems[this.focusedItemIndex];
             if (lastFocusedItem?.hasSubmenu) {
                 // Remove focus while opening overlay from keyboard or the visible focus
                 // will slip back to the first item in the menu.
-                this.blur();
+                // this.blur();
```
Comment (spdev3000) [inline packages/menu/src/Menu.ts:544]: NIT: can be removed?

File: packages/overlay/imperative-api.md [hunk 46]
```diff
@@ -0,0 +1,95 @@
...
+
+When an Overlay is `notImmediatelyCloseable` that means that the first interaction that would lead to the closure of the Overlay in question will be ignored. This is useful when working with non-"click" mouse interactions, like `contextmenu`, where the trigger event (e.g. `contextmenu`) occurs _before_ an event that would close said overlay (e.g. `pointerup`).
+
+### offset
+
+The `offset` property accepts either a single number, to define the offset of the Overlay along the main axis from the trigger, or 2-tuple, to define the offset along the main axis and the cross axis. This option has no effect when there is no trigger element.
+
+### placement
+
+A `placement` of `"auto" | "auto-start" | "auto-end" | "top" | "bottom" | "right" | "left" | "top-start" | "top-end" | "bottom-start" | "bottom-end" | "right-start" | "right-end" | "left-start" | "left-end"` will instruct the Overlay where to place itself in relationship to the trigger element.
```
Comment (spdev3000) [inline packages/overlay/imperative-api.md:77]: Just a side note - can you pls either link to the explanation of placement options or add some details here? I am personally interested in more details about those "auto*" options. Thx!

File: packages/overlay/imperative-api.md [hunk 47]
```diff
@@ -0,0 +1,95 @@
...
+
+### type
+
+The `type` of an Overlay outlines a number of things about the interaction model within which is works.
+
+-   `'modal'` Overlays are opened with the `showModal()` method on a `<dialog>` element, which causes the Overlay to accept focus and trap the tab stop within the content of said Overlay.
+-   `'page'` Overlays will act in a similar manner to a `'modal'` Overlay, however they will not be allowed to close via the "light dismiss" algorithm (e.g. the Escape key).
+-   `'hint'` Overlays are much like tooltips so they are not just ephemeral, but they are delivered primarily as a visual helper and exist outside of the tab order. In this way, be sure _not_ to place interactive content within this type of Overlay.
+-   `'auto'` Overlays provide a place for content that is ephemeral _and_ interactive. These Overlays can accept focus but will close when losing that focus, or when interacting with other parts of the page.
+-   `'manual'` Overlays act much like `"auto"` Overlays, but do not close when losing focus or interacting with other parts of the page. When a `"manual"` Overlay is at the top of the "overlay stack", it will still respond to the Escape key and close.
```
Comment (spdev3000) [inline packages/overlay/imperative-api.md:95]: I really like that detailed explanation here, makes it easier to distinguish then before.

File: packages/overlay/src/OverlayBase.ts [hunk 48]
```diff
@@ -0,0 +1,908 @@
...
+        triggerElement.removeEventListener('pointerup', this.handlePointerup);
+        triggerElement.removeEventListener(
+            'pointercancel',
+            this.handlePointerup
+        );
+    };
+
+    /**
+     * @private
+     */
```
Comment (spdev3000) [inline packages/overlay/src/OverlayBase.ts:617]: NIT: Why doc marking it as @private here when it's protected?

File: packages/overlay/src/OverlayBase.ts (hunk 30 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts:295]: You can't _technically_ ever get to these messages. I may need to invert the mixin order for the API table to build correctly, which might remove these "abstract" methods all together.

File: packages/overlay/src/OverlayBase.ts (hunk 36 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts:400]: And here I just change the signature of these methods to be reciprocal for you 😉

File: packages/overlay/src/OverlayBase.ts (hunk 40 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts:558]: We'll cross that bridge if we ever get to it.

File: packages/overlay/src/OverlayBase.ts (hunk 41 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts:852]: The intent here is for the last opened Overlay to always have the highest value as a corollary to top layer being a single stack in fallback browsers. I'll add a comment.

File: packages/overlay/src/OverlayBase.ts (hunk 42 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts:874]: Error!

File: packages/overlay/src/OverlayDialog.ts (hunk 43 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayDialog.ts:63]: I'll test some options...but it's quite weird x-browser, if I remember correctly.

File: packages/overlay/src/OverlayBase.ts (hunk 48 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts:619]: Generally, we've done this to prevent these methods from surfacing in the API table, I'll double check that's the case here and add a comment.

File: packages/overlay/imperative-api.md (hunk 46 above)
Comment (Westbrook) [reply packages/overlay/imperative-api.md:77]: `auto` may not be a part of the default API anymore, but I'll get a link to https://floating-ui.com/docs/computePosition#placement somewhere in there.

**Comment by Westbrook** [comment]
> At https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/picker--default I see a small focus-visible flash when selecting via keyboard (but not when selecting via mouse):

You are pressing `Enter` here, right? If so, this seems like it's related to https://github.com/adobe/spectrum-web-components/pull/3456#issuecomment-1650519456, as the Menu should close on selection there... 🤔

File: packages/overlay/src/OverlayBase.ts (hunk 30 above)
Comment (hunterloftis) [inline packages/overlay/src/OverlayBase.ts:298]:
```suggestion
    protected async manageDialogOpen(): Promise<void> {
        // abstract method overridden by subclasses
    }

    protected async managePopoverOpen(): Promise<void> {
        // abstract method overridden by subclasses
    }
```

Comment (hunterloftis) [reply packages/overlay/src/OverlayBase.ts:298]: Gotcha! I just left an alternate suggestion to make that more clear.

File: packages/overlay/src/OverlayBase.ts (hunk 36 above)
Comment (hunterloftis) [reply packages/overlay/src/OverlayBase.ts]: I did see that!

File: packages/overlay/src/OverlayDialog.ts (hunk 43 above)
Comment (hunterloftis) [reply packages/overlay/src/OverlayDialog.ts:63]: Unimportant for now then, just a nit.

**Comment by hunterloftis** [comment]
> You are pressing `Enter` here, right? If so, this seems like it's related to [#3456 (comment)](https://github.com/adobe/spectrum-web-components/pull/3456#issuecomment-1650519456), as the Menu should close on selection there... 🤔

Yep, pressing enter -> flash & select (no close), pressing space -> select & close (working as expected)

File: packages/overlay/src/OverlayBase.ts (hunk 30 above)
Comment (Westbrook) [reply packages/overlay/src/OverlayBase.ts]: I inverted the extension order so that this is not longer a thing.

**Comment by hunterloftis** [comment]
@Westbrook I re-tested these, nice progress!

✅ [fixed](https://github.com/adobe/spectrum-web-components/pull/3456#issuecomment-1650519456)
✅ [fixed](https://github.com/adobe/spectrum-web-components/pull/3456#issuecomment-1650531678)
❓ [still weird first open](https://github.com/adobe/spectrum-web-components/pull/3456#issuecomment-1650538075)
✅ [fixed](https://github.com/adobe/spectrum-web-components/pull/3456#issuecomment-1650577916)
✅ [fixed](https://github.com/adobe/spectrum-web-components/pull/3456#issuecomment-1650582598)

**Comment by hunterloftis** [comment]
Running through the stories once more after all of these updates. Looking very good! So far I've only seen one thing that I think is a regression - some positioning weirdness at https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/overlay--default

https://github.com/adobe/spectrum-web-components/assets/364501/3944a3e5-591c-4df7-a016-1e330bbec4c5

I only see this behavior in Chrome, not in Safari, so it seems related to the new APIs.

**Comment by hunterloftis** [comment]
This may just be a storybook side-effect, since several of these demos have tooltips and I don't see this behavior in them. But when I refresh https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/tooltip--self-managed a few times:

https://github.com/adobe/spectrum-web-components/assets/364501/e9e909ce-878c-416e-924b-0d12239288a3

**Comment by hunterloftis** [comment]
I'm sorry if this is hard to reproduce - I can only trigger this behavior intermittently - but occasionally closing a fullscreen or fullscreen-takeover dialog at https://overlay-mixins--spectrum-web-components.netlify.app/components/dialog-wrapper/ will leave my page non-interactive (with either mouse or keyboard). Example around 0:20:

https://github.com/adobe/spectrum-web-components/assets/364501/da7e1e86-ea89-4243-a30f-7d042f4ce203

Once in this state, I can't inspect elements, sort of like the browser's top-layer is getting in the way of all of my clicks.

**Comment by hunterloftis** [comment]
Again only in Chrome with the new APIs, seeing a little positioning confusing with the action bar at https://overlay-mixins--spectrum-web-components.netlify.app/components/overlay/#action-bar:

https://github.com/adobe/spectrum-web-components/assets/364501/606cfe9a-b946-41fa-acf7-380569b376b7

Safari positions correctly but doesn't show tooltips. I'm also not sure if this is in or out of spec, but either way it's super minor - the action bar items depend on a pointerup before the user moves on to the next item, or they'll stack:

https://github.com/adobe/spectrum-web-components/assets/364501/571914e3-58d8-4345-b2cb-d093f64d5fd0

**Comment by hunterloftis** [comment]
The overlay trigger example at https://overlay-mixins--spectrum-web-components.netlify.app/components/overlay-trigger/#examples seems to pick up the click events from the slider as being outside, and closing:

https://github.com/adobe/spectrum-web-components/assets/364501/b99067f1-8af5-49d1-a548-a2cc7e6cd1a9

**Comment by hunterloftis** [comment]
Just verifying the styling here for arbitrary text in the split button menu at https://overlay-mixins--spectrum-web-components.netlify.app/components/split-button/#sizes:

image

**Comment by hunterloftis** [comment]
That's all the issues I could find - only one of them (positioning confusion in Chrome) seems like a functionality blocker.

**Review by hunterloftis — DISMISSED** [review]
lgtm, all the "handled" issues, are!

While testing [this](https://overlay-mixins--spectrum-web-components.netlify.app/storybook/index.html?path=/story/dialog-base--slotted) and [this](https://overlay-mixins--spectrum-web-components.netlify.app/components/dialog-wrapper/) I saw the "something unselectable in top-layer is capturing input" thing again. I don't think there's any action-item there other than to be aware... given that you can't reproduce it locally, it may even be a browser issue.

File: packages/menu/src/MenuItem.ts [hunk 49]
```diff
@@ -211,24 +172,15 @@ export class MenuItem extends LikeAnchor(
...
-            : contentSlot.assignedNodes().map((node) => node.cloneNode(true));
+        const icon = this.iconSlot.assignedElements().map((element) => {
+            const newElement = element.cloneNode(true) as HTMLElement;
+            newElement.removeAttribute('slot');
+            newElement.classList.toggle('icon');
+            return newElement;
+        });
+        const content = this.contentSlot
+            .assignedNodes()
+            .map((node) => node.cloneNode(true));
```
Comment (charlessuh) [inline packages/menu/src/MenuItem.ts:183]: Isn't it possible for `contentSlot` or `iconSlot` to be undefined / null?

Comment (Westbrook) [reply packages/menu/src/MenuItem.ts:183]: In the frame before the first call to `render()`, sure there is a moment in which these are not yet defined. There's likely harder to define issues that arise in that moment than this, but we'd love to hear if you happen to have a use case where that arises! Then we can make sure it's covered in our unit test suite and resilient to any subsequent changes that may come to this part of the library.

Comment (charlessuh) [reply packages/menu/src/MenuItem.ts:183]: Thanks! I created #3626.
