### PR TITLE
fix: allow for Picker element to be reparented

### LINKED ISSUE #2175: Reparenting an sp-picker while open leads to its losing some state
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-picker

### Expected behavior

Reparenting `<sp-picker>` maintains the list of options as well as the currently-active option.

### Actual behavior

Reparenting `<sp-picker>` while it's open loses the currently-active option.

Additionally, while writing the reproduction, I noticed that the picker's styling changes each time it's reparented (replicate by clicking "reparent before" repeatedly).

### Screenshots

https://user-images.githubusercontent.com/364501/159538574-12ff8ecb-0126-4a62-9fec-3ec5aca138b5.mov

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

Reproduced here: https://webcomponents.dev/edit/NyO89LhEIfJnZJMNeR3m/src/index.ts?p=stories

1. Select an option from the picker
2. Click on "reparent after"
3. Click on the picker to open it
4. Observe that the selected option is cleared when the picker is reparented

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
- ensure that the `dir` attribute is managed correctly in all elements when reparenting them
- allow for `value` property in `sp-picker` and derivative elements to be managed correctly when reparenting the element
- ensure Picker passes "selection" to the Menu Items it holds before reparenting them into a Menu, this allows no 0th indexed Menu Items to be "focused" when the overlay opens with a "selection"

## Related issue(s)
- fixes #2175

## Motivation and context
Elements should be resilient to varying use cases

## How has this been tested?
I've added unit tests for the use case in the issue, you could recreate this manually in the browser if you'd like, as well.

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hunterloftis** [comment]
Manually testing here: https://picker-reparenting-2--spectrum-web-components.netlify.app/storybook/?path=/story/picker--default

In the console, via:

```
document.getElementsByTagName('p')[2].append(document.getElementsByTagName('sp-picker')[0])
```

Works in this PR, fails in prod, so 👍

File: packages/split-button/src/SplitButton.ts [hunk 1]
```diff
@@ -186,26 +186,26 @@ export class SplitButton extends SizedMixin(PickerBase) {
         }
     }
 
-    protected manageSelection(): void {
+    protected async manageSelection(): Promise<void> {
         super.manageSelection();
```
Comment (hunterloftis) [inline packages/split-button/src/SplitButton.ts:190]: If changing the signature to be async, should this also await its super call to be sure order is preserved? (1. whatever super does, 2. this.manageSplitButtonItems())

```suggestion
        await super.manageSelection();
```

**Review by hunterloftis — DISMISSED** [review]
Thanks for sorting this out!

@spdev3000 once this is released, I think you'll be able to simplify/delete some picker refs & close handlers in your recent work.

File: packages/split-button/src/SplitButton.ts (hunk 1 above)
Comment (Westbrook) [reply packages/split-button/src/SplitButton.ts:190]: Actually 👎🏼 ... I tried this and then it fails VRT because it updates the timing of the open/select/highlight code. It _likely_ points to some lucky timing vs intentional timing, but I'd like to skip digging into it while it doesn't show as broken in any of our tests/demos.

Comment (hunterloftis) [reply packages/split-button/src/SplitButton.ts:190]: Interesting, then I think we're running `super.manageSelection()` and `this.manageSplitButtonItems()` concurrently, and relying on some relative timing between the two.

Not changing while things pass works for me.

I'm curious what happens with this, just to complete all the different ways they could be ordered:

```ts
await this.manageSplitButtonItems()
await this.manageSelection()
```

Comment (Westbrook) [reply packages/split-button/src/SplitButton.ts]: Trying in CI now. Having `manageSplitButtonItems` should encapsulate it in the asynchrony of `manageSelection` 🤞🏼 Hopefully, there's not other side effects here...
