### PR TITLE
fix(menu): menuitem focus and hover styles 

### LINKED ISSUE #5269: [Bug]: Menu Item hover is overriding `focused` styles
### Code of conduct

- [x] I agree to follow this project's code of conduct.

### Impacted component(s)

menu, menuitem, action-menu, picker

### Expected behavior

See SWC-762

### Actual behavior

Menu Item bug is overrding the styles of focus attribute.
Currently when we focusin/mouseenter and do focusout/mouseout we add hover styles which is adding additional styling due to focused attribute not updating

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code or abstract reproduction which illustrates the problem

_No response_

### Severity

None

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by nikkimk**
## Related issue(s)

- fixes #5269 
## How has this been tested?

-   [x] Hover styling
1. Go to the [submenu storybook example](https://nikkimk-menu-focus-hover--spectrum-w-c.netlify.app/storybook/?path=/story/menu-submenu--submenu).
2. Close the menu.
3. Use your mouse to click and reopen it.
4. Use you mouse to hover over a menuitem with submenu.
5. Submenu should open. 
6. Menuitems under your pointer should have hover styling and _not_ the focus outline.

-   [x] Focus styling
1. Go to the [submenu storybook example](https://nikkimk-menu-focus-hover--spectrum-w-c.netlify.app/storybook/?path=/story/menu-submenu--submenu).
2. Close the menu.
3. Use your mouse to click and reopen it.
4. Use you mouse to hover over the second menuitem
5. Press <kbd>&darr;</kbd>
6. The third item should have focus styling.
7. Press <kbd>&rarr;</kbd>
8. The the third item's submenu should be open and focus should be on one of its menuitems.

-   [ ] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

File: packages/menu/src/MenuItem.ts [hunk 1]
```diff
@@ -369,6 +379,7 @@ export class MenuItem extends LikeAnchor(
         import('@spectrum-web-components/popover/sp-popover.js');
         return html`
             <sp-overlay
+                receives-focus="false"
```
Comment (nikkimk) [inline packages/menu/src/MenuItem.ts:382]: We don't want focus automatically set or the focus indicator would be one step ahead of mouse hover.

File: packages/menu/src/Menu.ts [hunk 2]
```diff
@@ -678,7 +665,7 @@ export class Menu extends SizedMixin(SpectrumElement, { noDefaultSize: true }) {
             if (lastFocusedItem?.hasSubmenu) {
                 //open submenu and set focus
                 event.stopPropagation();
-                lastFocusedItem.openOverlay();
+                lastFocusedItem.openOverlay(true);
```
Comment (nikkimk) [inline packages/menu/src/Menu.ts:668]: Added to distinguish between deliberate events, like clicking and keyboard opening and casual events like hovering. We don't want focus automatically set or the focus indicator would be one step ahead of mouse hover.

File: packages/menu/src/MenuItem.ts [hunk 3]
```diff
@@ -460,13 +471,21 @@ export class MenuItem extends LikeAnchor(
...
         this.addEventListener('keydown', this.handleKeydown);
+        this.addEventListener('mouseover', this.handleMouseover);
         this.addEventListener('pointerdown', this.handlePointerdown);
         this.addEventListener('pointerenter', this.closeOverlaysForRoot);
         if (!this.hasAttribute('id')) {
             this.id = `sp-menu-item-${randomID()}`;
         }
     }
 
+    handleMouseover(event: MouseEvent): void {
```
Comment (nikkimk) [inline packages/menu/src/MenuItem.ts:482]: Removes focus styling from hovered menuitem. Stlye would return if keyboard moved elsewhere and then came back to the item.

File: .circleci/config.yml [hunk 4]
```diff
@@ -14,7 +14,7 @@ parameters:
     # 3. Commit this change to the PR branch where the changes exist.
     current_golden_images_hash:
         type: string
-        default: 9995fe6e5347d0dfd21b6ef153068c4004fb1987
+        default: 6e76c8fd1c26c6b191215ba4a405ec3149c85b46
```
Comment (nikkimk) [inline .circleci/config.yml:17]: Obvi, since this is a fix to styling issues, the current hash needed to be updated

File: packages/menu/test/menu.test.ts [hunk 5]
```diff
@@ -313,56 +313,6 @@ describe('Menu', () => {
         );
     });
 
-    it('handles hover and keyboard input', async () => {
```
Comment (nikkimk) [inline packages/menu/test/menu.test.ts:316]: hover and keyboard test moved to submenu where it actually take effect

File: test/testing-helpers.ts [hunk 6]
```diff
@@ -26,6 +26,48 @@ import { TemplateResult } from '@spectrum-web-components/base';
 
 import { sendMouse } from './plugins/browser.js';
 
+export async function sendMouseTo(
```
Comment (nikkimk) [inline test/testing-helpers.ts:29]: I found the tests hard to read with all the `SendMouse` code that basically does the same thing, so I added this

File: packages/menu/test/submenu.test.ts [hunk 7]
```diff
@@ -106,6 +84,44 @@ describe('Submenu', () => {
             ).to.be.true;
         });
     }
+    function selectsWithBoth(testData: SelectsWithKeyboardTest): void {
```
Comment (nikkimk) [inline packages/menu/test/submenu.test.ts:87]: Replaces the test I removed from menu

**Comment by rubencarvalho** [comment]
I can consistently get 2 menu items with hover styles applied: 
Screenshot 2025-04-01 at 09 29 04

To reproduce, visit the [Submenu story](https://nikkimk-menu-focus-hover--spectrum-w-c.netlify.app/storybook/?path=/story/menu-submenu--submenu), hover over Brooklyn -> Ft. Greene -> Williamsburg.

**Comment by caseyisonit** [comment]
I confirmed that I'm seeing the same as Ruben. The focus leaves the main menu item that has a submenu, but the submenu with a second submenu stays focused.

File: packages/menu/src/Menu.ts [hunk 8]
```diff
@@ -449,17 +447,6 @@ export class Menu extends SizedMixin(SpectrumElement, { noDefaultSize: true }) {
     // handle the click event.
     private pointerUpTarget = null as EventTarget | null;
 
-    private handleMouseover(event: MouseEvent): void {
```
Comment (nikkimk) [inline packages/menu/src/Menu.ts:452]: this is not needed

**Review by caseyisonit — APPROVED** [review]
so when in a submenu theres a slight delay when hovering on an item with another submenu and then hovering a non submenu item. i dont know if thats related to the overlay issue but wanted to call it out but for me that might be out of scope of this ticket. the focus hover issue is resolved so I am approving

**Comment by nikkimk** [comment]
> so when in a submenu theres a slight delay when hovering on an item with another submenu and then hovering a non submenu item. i dont know if thats related to the overlay issue but wanted to call it out but for me that might be out of scope of this ticket. the focus hover issue is resolved so I am approving

@caseyisonit This is a separate issue which I am guessing is related to the timing of overlay

File: .changeset/spicy-papers-fold.md [hunk 9]
```diff
@@ -0,0 +1,5 @@
+---
+'@spectrum-web-components/menu': patch
+---
+
+resolves issue with mouseover and focus styling
```
Comment (castastrophe) [inline .changeset/spicy-papers-fold.md:5]: I think the changesets can benefit from being formatted more like formal documentation than commit logs. This is a great opportunity to outline the updates being made just like in the pull request description and highlight specifically any changes consumers need to make adjustments for or be aware of during their validation of the update.

File: packages/menu/src/Menu.ts (hunk 8 above)
Comment (castastrophe) [reply packages/menu/src/Menu.ts:452]: nice clean up!

File: packages/menu/src/Menu.ts (hunk 2 above)
Comment (castastrophe) [reply packages/menu/src/Menu.ts:686]: great point!

File: packages/menu/src/MenuItem.ts [hunk 10]
```diff
@@ -460,13 +472,20 @@ export class MenuItem extends LikeAnchor(
...
         if (!this.hasAttribute('id')) {
             this.id = `sp-menu-item-${randomID()}`;
         }
     }
-
+    handleMouseover(event: MouseEvent): void {
+        const target = event.target as HTMLElement;
+        if (target === this) {
+            this.focus();
+            this.focused = false;
```
Comment (castastrophe) [inline packages/menu/src/MenuItem.ts:486]: Can you clarify this pattern for me? We run the focus to set focus on the menu item but then why is the local focused attribute being set to false?

File: packages/menu/src/MenuItem.ts [hunk 11]
```diff
@@ -570,38 +592,37 @@ export class MenuItem extends LikeAnchor(
     }
 
     protected async handleSubmenuPointerleave(): Promise<void> {
-        requestAnimationFrame(() => {
-            this.recentlyLeftChild = false;
-        });
+        this.recentlyLeftChild = false;
```
Comment (castastrophe) [inline packages/menu/src/MenuItem.ts:595]: Does removing the requestAnimationFrame here cause the state to be updated more immediately? What the goal of the animation frame being present initially?

File: packages/menu/src/MenuItem.ts [hunk 12]
```diff
@@ -570,38 +592,37 @@ export class MenuItem extends LikeAnchor(
...
 
     protected cleanup(): void {
+        this._closedViaPointer = false;
         this.setAttribute('aria-expanded', 'false');
         this.open = false;
         this.active = false;
     }
 
-    public async openOverlay(): Promise<void> {
+    public async openOverlay(shouldFocus: boolean = false): Promise<void> {
```
Comment (castastrophe) [inline packages/menu/src/MenuItem.ts:618]: nice addition! I love the clarity here of opting into focus on overlay open instead of defaulting it.

File: packages/menu/test/menu.test.ts [hunk 13]
```diff
@@ -338,29 +338,25 @@ describe('Menu', () => {
...
-                    position: [
-                        rect.left + rect.width / 2,
-                        rect.top + rect.height / 2,
-                    ],
-                    type: 'move',
-                },
-            ],
-        });
+
+        await sendMouseTo(secondItem);
```
Comment (castastrophe) [inline packages/menu/test/menu.test.ts:342]: Love the improvement here - much more robust way to validate this action.

File: packages/menu/test/menu.test.ts [hunk 14]
```diff
@@ -338,29 +338,25 @@ describe('Menu', () => {
...
+            'second item should not have focus styling on hover'
+        ).to.be.false;
 
         await sendKeys({ press: 'ArrowUp' });
 
         expect(document.activeElement).to.equal(firstItem);
-        expect(firstItem.focused, 'first item focused').to.be.true;
+        expect(
+            firstItem.focused,
+            'first item shoudl have focus styling after keyboard'
```
Comment (castastrophe) [inline packages/menu/test/menu.test.ts:358]:
```suggestion
            'first item should have focus styling after keyboard'
```

small typo

File: packages/menu/test/submenu.test.ts [hunk 15]
```diff
@@ -278,108 +294,34 @@ describe('Submenu', () => {
...
-                        position: [
-                            rootItemBoundingRect.left +
-                                rootItemBoundingRect.width / 2,
-                            rootItemBoundingRect.top +
-                                rootItemBoundingRect.height / 2,
-                        ],
-                    },
-                ],
-            });
+            await sendMouseTo(this.rootItem);
```
Comment (castastrophe) [inline packages/menu/test/submenu.test.ts:317]: So succinct and specific!

File: packages/menu/test/submenu.test.ts [hunk 16]
```diff
@@ -879,6 +695,7 @@ describe('Submenu', () => {
         it('closes back to the first overlay without a `root` when clicking away', async function () {
             const rootMenu1 = this.el.querySelector('#submenu-item-1') as Menu;
             const childMenu2 = this.el.querySelector('#submenu-item-2') as Menu;
+            document.body.style.setProperty('padding', '50px');
```
Comment (castastrophe) [inline packages/menu/test/submenu.test.ts:698]: Just for me to learn - what purpose does the padding serve here? Is it to have a space to mouse to when removing focus?

**Review by castastrophe — APPROVED** [review]
A few questions/clarifications but nothing blocking. Thanks! This is a nice robust update, loved the new sendMouse utilities!

File: packages/menu/src/MenuItem.ts (hunk 11 above)
Comment (nikkimk) [reply packages/menu/src/MenuItem.ts:595]: @castastrophe it was causing a delay that left two menu items with hover styling.

File: packages/menu/test/submenu.test.ts (hunk 16 above)
Comment (nikkimk) [reply packages/menu/test/submenu.test.ts:698]: Yep

File: .changeset/spicy-papers-fold.md (hunk 9 above)
Comment (nikkimk) [reply .changeset/spicy-papers-fold.md]: Thanks, @castastrophe!
