### PR TITLE
fix(tabs): add "tablist" part to manage list styles

### LINKED ISSUE #2460: [Feat]: Expose CSS Part on sp-tabs #list
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tabs

### Description of the requested feature

We need a way to scroll tabs when they overflow. Short of this being addressed in upstream projects and then implemented, adding a CSS Part on the #list element in shadow DOM would provide an escape hatch.

### Mockups or screenshots

_No response_

### Implementation notes or ideas

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Add a `tablist` part to the "tab list" container in the `<sp-tabs>` element.

Add this to the Custom Elements Manifest for future documentation and IED consumptions, but do not actively document this as we don't have a good path to documenting part _AND_ I'd like to keep parts sort of secret until they feel like a wholistic part of the library.

Comes with some slightly related updates to spacing, colors and WHCM delivery of the Tabs and Top Nav elements.

## Related issue(s)
- fixes #2460

## How has this been tested?
-   [ ] _Test case 1_
    1. Go [here](https://tabs-list--spectrum-web-components.netlify.app/storybook/index.html?path=/story/tabs--vertical-right)
    2. Inspect the `<style>` tag in the story DOM
    3. Add `sp-tabs::part(tablist) { background: red; }` to see that the part is available.

## Types of changes
-   [x] New feature (non-breaking change which adds functionality)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

### CODE REVIEW

**Review by pinkhominid — APPROVED** [review]
LGTM!

File: packages/top-nav/src/TopNav.ts [hunk 1]
```diff
@@ -169,17 +169,11 @@ export class TopNav extends SizedMixin(SpectrumElement) {
...
         const width = itemBoundingClientRect.width;
-        const offset =
-            this.dir === 'ltr'
-                ? itemBoundingClientRect.left - parentBoundingClientRect.left
-                : itemBoundingClientRect.right - parentBoundingClientRect.right;
-
-        this.selectionIndicatorStyle = `transform: translateX(${offset}px) scaleX(${
-            this.dir === 'ltr' ? width : -1 * width
-        });`;
+        const offset = selectedItem.offsetLeft;
```
Comment (hunterloftis) [inline packages/top-nav/src/TopNav.ts:174]: I dig the simplification. Does `offsetLeft` inherently measure from the right in `rtl` contexts?

**Review by hunterloftis — APPROVED** [review]
Good first ::part experiment!

File: packages/top-nav/src/TopNav.ts (hunk 1 above)
Comment (Westbrook) [reply packages/top-nav/src/TopNav.ts:174]: I actually hoped that there would be an `offsetRight` and I could just swap, but `offsetLeft` [_always_ measuring from left](https://codepen.io/Westbrook/pen/abYYvMe), meant that all of this logic could be simplified. A kind of crazy side effect of the whole deal!
