### PR TITLE
fix: ensure "wheel" interactions lead to a "change" event

### LINKED ISSUE #2867: [Bug]:  Change event is not getting triggered at the end of mouse scroll on sp-number-field
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-number-field

### Expected behavior

Mouse scroll  on <sp-number-field> changes its value. It emits input events when the value is changing but at at the end of the scroll, no change event is triggered. 

### Actual behavior

It is expected to emit change event at the end of scroll operation. 

### Screenshots

_No response_

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Use the below code sample to create `<sp-number-field>`
2. Click and scroll.
3. Observe the values getting increase/decreased.
4. Stop scrolling and move the focus out if need.
5. Observe the change event not getting triggered at the end of scroll operation.

### Sample code that illustrates the problem

```
 <sp-number-field 
                hide-stepper
                title="sample"
                value=720
                @change=<some function which should get triggered on change event>
></sp-number-field>
```

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
When interacting with a Number Field via the `wheel` event, ensure that a `change` event is dispatched, to ensure batched listening is successful. Do so by waiting 100ms after the last `input` event is fired to fire a `change` event. Timing here seems pretty flexible, and I could be convinced of a shorter debounce, but this feels like a good balance between firing the `change` and not firing it all the time, as the `wheel` event could be stop and start and allows for breaks in the interaction.

## Related issue(s)

- fixes #2867 

## How has this been tested?

-   [ ] _Test case 1_
    1. Go [here](https://number-field-change--spectrum-web-components.netlify.app/storybook/index.html?path=/story/number-field--default)
    2. Interact with the Number Field with the `wheel` event
    3. Check the "Actions" Tab in the Storybook interface
    4. See that a large number of `onInput` events are being handled and a smaller number of `onChange` events are being handled.

## Types of changes
-   [x] New feature (non-breaking change which adds functionality)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: packages/number-field/src/NumberField.ts [hunk 1]
```diff
@@ -318,6 +320,13 @@ export class NumberField extends TextfieldBase {
             : event.deltaY / Math.abs(event.deltaY);
         if (direction !== 0 && !isNaN(direction)) {
             this.stepBy(direction * (event.shiftKey ? this.stepModifier : 1));
+            // Dispatch a change event after no new `input` events are queued by `wheel` interactions for 100ms.
+            clearTimeout(this.queuedChangeEvent);
+            this.queuedChangeEvent = setTimeout(() => {
+                this.dispatchEvent(
+                    new Event('change', { bubbles: true, composed: true })
+                );
+            }, 100) as unknown as number;
```
Comment (hunterloftis) [inline packages/number-field/src/NumberField.ts:329]: The comment above addresses this number, but just to present an alternative, we could also consider something like:

```ts
const CHANGE_DEBOUNCE_MS = 100;
```

**Review by hunterloftis — DISMISSED** [review]

File: packages/number-field/src/NumberField.ts (hunk 1 above)
Comment (Westbrook) [reply packages/number-field/src/NumberField.ts:329]: Kind of like _both_ as it allows me to export this and leverage it in the test as well...
