### PR TITLE
fix(menu): prevent infinite loop when focus()

### LINKED ISSUE #1009: Focusing a sp-menu with no enabled sp-menu-item causes infinate loop
### Expected Behaviour
A sp-menu with no enabled sp-menu-item can be focused normally, or can't obtain a focus.

### Actual Behaviour
Call focus on such a sp-menu causes infinate loop, makes the browser stop responding.
### Reproduce Scenario (including but not limited to)
For example, a dropdown will try to focus its menu when opened.
```html
<sp-dropdown label="Select a Country with a very long label, too long in fact">
    <sp-menu>
        <sp-menu-item disabled>
            Deselect
        </sp-menu-item>
        <sp-menu-item disabled>
            Select inverse
        </sp-menu-item>
        <sp-menu-item disabled>
            Feather...
        </sp-menu-item>
        <sp-menu-item disabled>
            Select and mask...
        </sp-menu-item>
        <sp-menu-divider></sp-menu-divider>
        <sp-menu-item disabled>
            Save selection
        </sp-menu-item>
        <sp-menu-item disabled>
            Make work path
        </sp-menu-item>
    </sp-menu>
</sp-dropdown>
```
#### Platform and Version
Latest Edge & Firefox
@spectrum-web-components/bundle:  0.15.5

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Make sure there are active menu items available when focusing items within an `<sp-menu>` element.

## Related Issue
fixes #1009 

## Motivation and Context
Prevent infinite loops.

## How Has This Been Tested?
Unit tests.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/menu/src/Menu.ts [hunk 1]
```diff
@@ -63,7 +63,10 @@ export class Menu extends SpectrumElement {
     }
 
     public focus(): void {
-        if (!this.menuItems.length) {
+        if (
+            !this.menuItems.length ||
+            !this.menuItems.filter((item) => !item.disabled).length
```
Comment (kaiortmanns) [inline packages/menu/src/Menu.ts:68]: You maybe could use menuItems.every(..) here to make it more obvious what you are testing.

**Review by kaiortmanns — APPROVED** [review]

File: packages/menu/src/Menu.ts (hunk 1 above)
Comment (Westbrook) [reply packages/menu/src/Menu.ts:68]: Good idea. Is `!this.menuItem.some((item) => !item.disabled)` similarly clear, or no? It has the possibility of not having to traverse the entire array.

Comment (kaiortmanns) [reply packages/menu/src/Menu.ts:68]: Well. `every` returns a boolean and you don´t have to test for length again. And `every` would break immediately if the condition is not met. So you don´t iterate over the whole array if you don´t need to.
So `this.menuItem.every((item) => item.disabled)` would test if all items are disabled.
