### PR TITLE
fix(slider): update "value" default to match browser native range input

### LINKED ISSUE #1788: [Slider]: why does value default to 10?
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

The value of a slider [defaults to 10](https://github.com/adobe/spectrum-web-components/blob/de3151b9e940121f518f1d94d2601cb87ba95ddb/packages/slider/src/SliderHandle.ts#L88). Is there a reason for this, or is it arbitrary? It surprised me as a user, since I would expect the [defaultValue from input type="range"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#value).

Changing the default `value` of `sp-slider` and `sp-slider-handle` would be a breaking change. Is v1.0 a good opportunity for this?

### PR DESCRIPTION
**Pull request by Westbrook**
BREAKING CHANGE: When not supplied value will now be set to halfway between min and max.

## Description
Update default `value` when no applied by the application. Update tests to match.

## Related issue(s)

- fixes #1788

## Motivation and context
Be more like native elements.

## How has this been tested?

-   [ ] _Test case 1_
    1. With unit tests...

## Types of changes
-   [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: packages/slider/src/SliderHandle.ts [hunk 1]
```diff
@@ -131,6 +135,16 @@ export class SliderHandle extends Focusable {
         super.update(changes);
     }
 
+    protected firstUpdated(changedProperties: PropertyValues<this>): void {
+        super.firstUpdated(changedProperties);
+        const { max, min } = this as { max: number; min: number };
+        if (!this.value) {
```
Comment (hunterloftis) [inline packages/slider/src/SliderHandle.ts:141]: We should specifically check for missing value, since `!0` is `true`:

```suggestion
        if (this.value == null) {
```

**Review by hunterloftis — APPROVED** [review]
