### PR TITLE
fix(search): ensure "reset" surfaces "input" and "change" events

### LINKED ISSUE #313: Clearing search field does not generate event or clear value
### Expected Behaviour

When you click on the 'x' the search field should send out some sort of event, either `input` or `change` to notify that it has happened. And, accessing the `.value` property on the search field should give you and empty string.

### Actual Behaviour

No event is generated and the `.value` remains as it was before the field was cleared.

#### Steps to Reproduce

- Run the documentation site from pull #312
- Type in a search such as "but"
- click the 'x'

#### Sample Code that illustrates the problem

Documentation site from #312

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Manual dispatch `input` and `change` events from the `input` element in the `Search` component so that an appropriate response can be made in implementing applications.

## Related Issue
fixes #313

## Motivation and Context
Tighter interaction loop.

## How Has This Been Tested?
- unit test

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/search/src/search.ts [hunk 1]
```diff
@@ -64,13 +64,29 @@ export class Search extends Textfield {
...
         this.form.reset();
+        await this.updateComplete;
+        this.focusElement.dispatchEvent(
+            new InputEvent('input', {
+                bubbles: true,
+                composed: true,
+            })
+        );
+        // The native `change` event on an `input` element is not composed,
+        // so this synthetic replication of a `change` event must not either
```
Comment (cuberoot) [inline packages/search/src/search.ts]: did you mean "must not *be* either"?

Comment (Westbrook) [reply packages/search/src/search.ts]: English really is the hardest part of the work we do here... corrected!
