### PR TITLE
fix: click on docs sidenav links in Edge

### LINKED ISSUE #628: Cannot select component in docs on Edge
### Expected Behaviour

Clicking on a component in the sidenav should take you to the page

### Actual Behaviour

In Edge, clicking on components in the sidenav doesn't do anything

#### Steps to Reproduce

Go to https://opensource.adobe.com/spectrum-web-components/ and click on a component in the sidenav

#### Platform and Version

Pre-chromium versions of Edge

### PR DESCRIPTION
**Pull request by cuberoot**
## Description

Make the sidenav component links work in pre-chromium Edge.

## Related Issue

fixes #628 

## Motivation and Context

I want to debug some issues in our components in pre-chromium Edge using the doc site, but I can't even navigate to the component pages

## How Has This Been Tested?

Manual testing in Edge

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: documentation/src/components/page.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ export class Page extends LayoutElement {
     }
 
     public resetScroll() {
-        if (!this.contentElement) return;
+        if (!this.contentElement || !this.contentElement.scroll) return;
```
Comment (cuberoot) [inline documentation/src/components/page.ts:33]: I have seen this with the web component polyfill before. The `scroll` method is autocompleted in the console, but evaluates to `undefined` when you call it. This works around that. I am not going to investigate more deeply at this time.

File: documentation/src/components/page.ts [hunk 2]
```diff
@@ -30,7 +30,7 @@ export class Page extends LayoutElement {
...
 
         this.contentElement.scroll(0, 0);
```
Comment (Westbrook) [inline documentation/src/components/page.ts:35]: Not worth spending much thought on, but should we use `scrollTop` here instead for broader support for returning to the top of the page?

File: documentation/src/components/page.ts [hunk 3]
```diff
@@ -32,7 +32,7 @@ export class Page extends LayoutElement {
     public resetScroll() {
         if (!this.contentElement) return;
 
-        this.contentElement.scroll(0, 0);
+        this.contentElement.scrollTop = 0;
```
Comment (cuberoot) [inline documentation/src/components/page.ts:35]: @Westbrook, good idea. This works in Edge
