### PR TITLE
[#291] Update sp-link and leverage in documentation

### LINKED ISSUE #212: Source Maps not being followed in test command.
### Expected Behaviour
Test coverage should be counted via the source file not the output file.

### Actual Behaviour
Test coverage is being made against the output file.

### `yarn upgrade`
This occurs as a side effect of unlocking the project when moving from `npm` to `yarn` and hopefully whatever dependency is causing this change will be updated remotely soon and a new `yarn upgrade` can wash this out of the system.

### LINKED ISSUE #291: `sp-link` has issues in the document site delivery
### Expected Behaviour
We should be able to use `<sp-link>` inline of text in the documentation site.

### Actual Behaviour
White space (`space` characters) before and after the element are collapsed inline of text.

### LINKED ISSUE #322: An in-range update of @open-wc/building-webpack is breaking the build 🚨
## The devDependency [@open-wc/building-webpack](https://github.com/open-wc/open-wc) was updated from `2.8.2` to `2.8.3`.

🚨 [View failing branch](https://github.com/adobe/spectrum-web-components/compare/master...adobe:greenkeeper%2F%40open-wc%2Fbuilding-webpack-2.8.3).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@open-wc/building-webpack is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ✅ **ci/circleci: build:** Your tests passed on CircleCI! ([Details](https://circleci.com/gh/adobe/spectrum-web-components/1012?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
- ❌ **ci/circleci: visual-testing:** Your tests failed on CircleCI ([Details](https://circleci.com/gh/adobe/spectrum-web-components/1013?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
- ❌ **build:** * [build](https://circleci.com/gh/adobe/spectrum-web-components/1012?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success
* [visual-testing](https://circleci.com/gh/adobe/spectrum-web-components/1013?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed 
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 7 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/199193558054fe9376c58504caf4f0459f59c6f7"><code>1991935</code></a> <code>chore: release new versions</code></li>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/d3eff0bea1f7710407db7da47f4d3bdbb959a272"><code>d3eff0b</code></a> <code>fix(building-webpack): maintain whitespace with  "conservativeCollapse"</code></li>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/354a5e635dc762807643e1ead29964c6bae6b26c"><code>354a5e6</code></a> <code>fix(building-rollup): maintain whitespace with  "conservativeCollapse"</code></li>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/745c945918760067ecb97b0785ad6eb5e9c8aba3"><code>745c945</code></a> <code>chore: release new versions</code></li>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/16910b009a8dff68346df74f676cf968d941d507"><code>16910b0</code></a> <code>chore(create): add test:update-snapshots command</code></li>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/81946cf7305ee48d92c4db8935871eb3497cfcbf"><code>81946cf</code></a> <code>chore: release new versions</code></li>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/8d2e0a89bb5b34b4abaa4c6a5f695037f8cc6f1a"><code>8d2e0a8</code></a> <code>fix(create): update building rollup version (#1039)</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/open-wc/open-wc/compare/61cfb4b15d4033c1a4640875a3672fd0d91f5ed3...199193558054fe9376c58504caf4f0459f59c6f7">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #348: An in-range update of @open-wc/testing-karma is breaking the build 🚨
## The devDependency [@open-wc/testing-karma](https://github.com/open-wc/open-wc) was updated from `3.2.13` to `3.2.14`.

🚨 [View failing branch](https://github.com/adobe/spectrum-web-components/compare/master...adobe:greenkeeper%2F%40open-wc%2Ftesting-karma-3.2.14).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@open-wc/testing-karma is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **ci/circleci: build:** Your tests failed on CircleCI ([Details](https://circleci.com/gh/adobe/spectrum-web-components/1232?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
- ❌ **build:** * [build](https://circleci.com/gh/adobe/spectrum-web-components/1232?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* visual-testing - Blocked 
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 4 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/fef2675f800d2279084aca4edebef72f62709fb6"><code>fef2675</code></a> <code>chore: release new versions</code></li>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/43a80fb91331d3a9d109343033f343e8b2b61990"><code>43a80fb</code></a> <code>chore(create): update test snapshot</code></li>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/dbb2928ddc97e567d1751b7c34bf0542036298c3"><code>dbb2928</code></a> <code>feat(es-dev-server): allow max compat on modern browsers</code></li>
<li><a href="https://urls.greenkeeper.io/open-wc/open-wc/commit/2c836039743356c0b4be02edbae7a6addbeaf8ac"><code>2c83603</code></a> <code>feat(create): update building-rollup dependency</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/open-wc/open-wc/compare/234fb6066edfa1cef2af962ab36ad42b72a92d51...fef2675f800d2279084aca4edebef72f62709fb6">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #376: Recent PR broke docs on Edge
### Expected Behaviour

Documentation site should load in Edge

### Actual Behaviour

Documentation site throws a console error about `customElement` being missing

#### Steps to Reproduce

Go to https://opensource.adobe.com/spectrum-web-components/ in Edge

#### Platform and Version

Edge (pre-chromium)

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
- correct sp-link's management of whitespace internally
- use sp-link in the documentation site
- use updated `@open-wc/building-web-pack` so that whitespace isn't incorrectly collapsed

### To-do
- [x] await merge of https://github.com/open-wc/open-wc/issues/1049

## Related Issue
fixes #291 
fixes #212 _accidentally_
fixes #322 _luckily_
fixes #348
fixes #376 _seemingly_

## Motivation and Context
Oh my, this dogfood is good!

## How Has This Been Tested?
Manally.

## Screenshots (if appropriate):
image

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Westbrook** [comment]
I realize now there are a lot more links in the docs, should I update those as well? I was mainly making sure we could use this, which wasn't possible before the fix, the mechanics of actually using `<sp-link>` over `<a>` is difficult to overcome, even when you compare `<a class="spectrum-Link">` it feels not _quite_ right.

Separately, it might be worth developing a stance of extending built-ins. Everything inside of `Link`, except the styles, is merely to overcome not having extended a built-in, so it might actually be the best call in this context. `<a is="sp-link">` is still _less_...

File: packages/link/src/link.ts [hunk 1]
```diff
@@ -57,9 +57,7 @@ export class Link extends Focusable {
                 id="anchor"
                 href=${ifDefined(this.href)}
                 target=${ifDefined(this.target)}
-            >
-                <slot></slot>
-            </a>
+            ><slot></slot></a>
```
Comment (andrewhatran) [inline packages/link/src/link.ts]: 👍

File: documentation/src/components/home.ts [hunk 2]
```diff
@@ -19,9 +19,9 @@ class HomeElement extends LayoutElement {
                 <p class="spectrum-Body3">
                     The Spectrum Web Components project is an implementation of
                     Adobe's
-                    <a class="spectrum-Link" href="https://spectrum.adobe.com/">
+                    <sp-link href="https://spectrum.adobe.com/">
```
Comment (andrewhatran) [inline documentation/src/components/home.ts]: 🐶 🐕

File: karma.conf.js [hunk 3]
```diff
@@ -29,20 +29,16 @@ module.exports = (config) => {
             esm: {
                 nodeResolve: true,
             },
-            browsers: [
-                path.resolve(path.join(__dirname, 'scripts/firefox.sh')),
-                path.resolve(path.join(__dirname, 'scripts/chrome.sh')),
-            ],
+            browsers: ['FirefoxHeadless'],
```
Comment (cuberoot) [inline karma.conf.js]: I'm curious why this change is in this PR. I wonder if you could give some background on this?

**Comment by cuberoot** [comment]
I have one question, but otherwise it looks great.

File: karma.conf.js (hunk 3 above)
Comment (Westbrook) [reply karma.conf.js]: It might not always be apparent when running `yarn test`, but until this PR we have been actually running the tests of Chrome twice and Firefox once. This is due to the fact that the `@open-wc` tooling assigned Chrome by default and then we were subsequently assigned Chrome and Firefox (on top of that) in these settings.

The custom scripts we were using were made for the project at a time when WSL stored its browsers in a non-normative location so without them, we couldn't run tests on local machines using that OS without them. More recent releases of WSL have returned access to the browsers in their expected locations so removing them has been on my list for a while.

I can't fully speak to the reason why it was needed in this specific PR, but due to some of the updates in the versions of various Babel dependencies, the tests stop running appropriately on CI when being run in the browsers that were discovered with these scripts. I wish I had a couple of levels up of CI skills and I could fully debug what was going on there, but when using the more standard browser accessors fixed the issue I decided to be OK with it. Running on two browsers, instead of these, might also give us a tiny speed benefit, though they were running mostly in parallel anyways. 

Right now, I'm doing a small test to discover which of the various configurations for acquiring Firefox is the best in that I can consistently run the tests with no trouble of CI and my personal machine, but my work machine doesn't like testing focus based interactions with it, which was one of the main reasons to move to headless to begin with.

I'm hacking through a last

Comment (cuberoot) [reply karma.conf.js]: Thanks for that. I looks like we should merge this up and follow up on the testing in a future PR.

**Comment by cuberoot** [comment]
@Westbrook We can merge this once the yarn.lock is resolved.
