### PR TITLE
Overlay fallbacks

### LINKED ISSUE #2198: [Bug]: VirtualTrigger: Overlay get cut off screen with placement "right-start"
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay, VirtualTrigger

### Expected behavior

Overlay should always be positioned and rendered at the screen that all content is visible.

### Actual behavior

When using a virtual trigger to open a context menu with placement="right-start" - it happens that the overlay content won't be correct positioned and always visible for small window sizes - and content will get cut off the screen.
This is mostly the case when the opened popover content width is >= half of the UI viewport. For example: If the popover width is 300px, this happens when viewport (body) is shrank to 600px and less. 

### Screenshots

overlay-wrong-position

### What browsers are you seeing the problem in?

Chrome Version 99.0.4844.84

### How can we reproduce this issue?

1. Go to https://webcomponents.dev/edit/ohZswGWTi4aHOb1GUd4X
2. Click on "ContextMenu Trigger"
3. Shrink page width (to about 600px or less)
4. Click again on trigger button (around phrase "Context" of ContextMenu Trigger)
5. Notify context menu content cut off page

You may try to set placement to "left-start" and there won't be a problem.

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Allow content opened from a "virtual trigger" to "flip" on both axises when looking for a place to position itself.
  - don't use `auto` because it's not predictable enough for closely related content like Pickers
  - update `size` usage to always fallback to the initial size when measuring
  - moves the Picker Menu location to above the Picker button in some Large VRTs due to their not being enough space below the picker for the content

## Related issue(s)

- fixes #2198

## How has this been tested?

-   [ ] _Test case 1_
    1. Go [here](https://overlay-fallbacks--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--virtual-element)
    2. Squeeze the preview window down to 400px wide or so
    3. Try opening the "context menu" from various places on the screen.
      - top left
      - top right
      - bottom left
      - bottom right
    4. See they the "context menu" opens in a related position that DOES NOT flow outside of the viewport.

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

### CODE REVIEW

File: packages/overlay/src/ActiveOverlay.ts [hunk 1]
```diff
@@ -446,6 +492,34 @@ export class ActiveOverlay extends SpectrumElement {
...
+        //                     : '';
+        //                 Object.assign(this.style, {
+        //                     maxWidth: `${Math.floor(width)}px`,
+        //                     maxHeight: appliedHeight,
+        //                     height: appliedHeight,
+        //                 });
+        //             },
+        //         })
+        //     );
+        // }
```
Comment (hunterloftis) [inline packages/overlay/src/ActiveOverlay.ts:522]:
```suggestion
```

**Review by hunterloftis — APPROVED** [review]

File: packages/overlay/src/ActiveOverlay.ts [hunk 2]
```diff
@@ -116,6 +117,43 @@ const parentOverlayOf = (el: Element): ActiveOverlay | null => {
...
+    } else if (placement.startsWith('bottom')) {
+        fallbacks.push('left');
+        fallbacks.push('right');
+        fallbacks[0] = fallbacks[0].replace(
+            'bottom',
+            'top'
+        ) as FloatingUIPlacement;
+    }
+    return fallbacks;
+};
```
[the remark this answers is not in the document]
Comment (Westbrook) [reply packages/overlay/src/ActiveOverlay.ts]: Great call on the dictionary. `auto` continues to not be an acceptable value for `FloatingUIPlacement` so while it might do what you are saying it _shouldn't_ ever do that...

File: packages/overlay/src/ActiveOverlay.ts (hunk 1 above)
Comment (Westbrook) [reply packages/overlay/src/ActiveOverlay.ts]: 😓

**Comment by spdev3000** [comment]
Thx @Westbrook for that quick solution!
