### PR TITLE
fix(top-nav): match indicator management strategy from Tabs

### LINKED ISSUE #2500: [Bug]: Selection indicator in Tab and TopNav should be updated when content size changes
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Tabs, TopNav

### Expected behavior

`Tabs` and `TopNav` should always update its selection indicator when its content size changes such as each child element changes in its size due to any dynamic updates.

### Actual behavior

The selection indicator does not update when the `Tabs` and `TopNav` change in their content size.

### Screenshots

selection indicator does not update

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Go to this [reduced test case](https://jsbin.com/mehidizuda/edit?html,css,output)
2. Run the demo and you should see the rendered `TopNav` with long text in each children
3. Wait for 3 seconds to see each children of `TopNav` changes its content with a shorter text
4. You should see the selection indicator does not update when the content changes

### Sample code that illustrates the problem

Simple reduced test can be found at https://jsbin.com/mehidizuda/edit?html,css,output.

### Logs taken while reproducing problem

N/A

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Add label recalculation in Top Nav Item to match Tab so that indicator can be updated as needed.

## Related issue(s)

- fixes #2500

## How has this been tested?

-   [ ] _Test case 1_
    1. Go [here](https://top-nav--spectrum-web-components.netlify.app/storybook/?path=/story/top-nav--selected)
    2. Inspect the Top Nav Item with the content "Page 3"
    3. Change its `innerHTML`
    4. See that the indicator is updated.
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: packages/top-nav/src/TopNavItem.ts [hunk 1]
```diff
@@ -73,10 +85,22 @@ export class TopNavItem extends LikeAnchor(Focusable) {
 
     protected override firstUpdated(changes: PropertyValues): void {
         super.firstUpdated(changes);
+        // @TODO - refactor this as a ResizeObserver up to `sp-tabs` so that it can be more
```
Comment (Westbrook) [inline packages/top-nav/src/TopNavItem.ts:88]: This TODO, copied from the same workflow in the Tab element, depends on feedback to https://github.com/lit/lit/issues/3237. Depending on which way that convo goes, we'll either move forward with the Resize Controller or need to do something custom with our own Resize Observer.

**Review by najikahalsema — APPROVED** [review]
