### PR TITLE
fix: abstract "hasVisibleFocusInTree" functionality and return trigger focus after close

### LINKED ISSUE #1894: [Bug]: split-button stops showing its menu after an open->close
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

split-button

### Expected behavior

Clicking the down arrow on an `<sp-split-button>` repeatedly should open and close its menu.

### Actual behavior

Clicking the down arrow on an `<sp-split-button>` opens and closes its menu once, then never again.

Clicking the down arrow, then selecting a new option from the menu each time, works as expected.

### Screenshots

https://user-images.githubusercontent.com/364501/139466363-bcff516b-4c2e-487c-80ff-8890ed3b35ac.mov

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/split-button/
2. Click on a split button's down arrow repeatedly

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
- correct extension from Picker so that both `<sp-action-menu>` and `<sp-split-button>` can now toggle
- abstract "hasVisibleFocusInTree" functionality to base with extra protection
- update `focusElement` on `sp-split-button[left]` elements

## Related issue(s)

- fixes #1894

## Motivation and context
Was broken

## How has this been tested?
-   [ ] _Test case 1_
    1. Go to https://splitter-toggle--spectrum-web-components.netlify.app/components/action-menu/#sizes
    2. Toggle the menu open/closed a few times
-   [ ] _Test case 2_
    1. Go to https://splitter-toggle--spectrum-web-components.netlify.app/components/split-button/#sizes
    2. Toggle the menu open/closed a few times

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

File: packages/base/src/Base.ts [hunk 1]
```diff
@@ -78,6 +79,27 @@ export function SpectrumMixin<T extends Constructor<UpdatingElement>>(
...
+                // will rely on the polyfill to know whether focus is "visible" or not.
+                hasVisibleFocusInTree =
+                    activeElement.matches(':focus-visible') ||
+                    activeElement.matches('.focus-visible');
+            } catch (error) {
+                hasVisibleFocusInTree = activeElement.matches('.focus-visible');
+            }
+            return hasVisibleFocusInTree;
+        }
+
```
Comment (hunterloftis) [inline packages/base/src/Base.ts:102]: Nice! I like that outside of tests, this PR deletes more code than it adds, by consolidating this shared functionality.

Is there a benefit to storing the temporary result in a variable vs. returning from whichever case?

```suggestion
        public hasVisibleFocusInTree(): boolean {
            const activeElement = (this.getRootNode() as Document)
                .activeElement as HTMLElement;
            if (!activeElement) {
                return false;
            }
            // Browsers without support for the `:focus-visible`
            // selector will throw on the following test (Safari, older things).
            // Some won't throw, but will be focusing item rather than the menu and
            // will rely on the polyfill to know whether focus is "visible" or not.
            try {
                return activeElement.matches(':focus-visible') || activeElement.matches('.focus-visible');
            } catch (error) {
                return activeElement.matches('.focus-visible');
            }
        }
```

File: packages/color-wheel/src/ColorWheel.ts [hunk 2]
```diff
@@ -442,16 +426,16 @@ export class ColorWheel extends Focusable {
...
-                    this.requestUpdate();
+            this.observer = new (
+                window as unknown as WithSWCResizeObserver
+            ).ResizeObserver((entries: SWCResizeObserverEntry[]) => {
+                for (const entry of entries) {
+                    this.boundingClientRect = entry.contentRect;
                 }
-            );
+                this.requestUpdate();
+            });
```
Comment (hunterloftis) [inline packages/color-wheel/src/ColorWheel.ts:438]: After https://github.com/adobe/spectrum-web-components/pull/1401 we can extract this into a shared Controller.

File: packages/picker/src/Picker.ts [hunk 3]
```diff
@@ -457,8 +443,8 @@ export class PickerBase extends SizedMixin(Focusable) {
                 <sp-menu
                     id="menu"
                     role="${this.listRole}"
-                    selects="single"
                     @change=${this.handleChange}
+                    .selects=${this.selects}
```
Comment (hunterloftis) [inline packages/picker/src/Picker.ts:447]: It looks like this is intentionally setting a property rather than an attribute. Could you share the motivation?

File: packages/split-button/src/SplitButton.ts [hunk 4]
```diff
@@ -72,16 +72,14 @@ export class SplitButton extends SizedMixin(PickerBase) {
...
-        if (this.disabled) {
-            return;
+    public get focusElement(): HTMLElement {
+        if (this.open) {
+            return this.optionsMenu;
         }
         if (this.left) {
-            this.trigger.focus();
-            return;
+            this.trigger;
```
Comment (hunterloftis) [inline packages/split-button/src/SplitButton.ts:80]: Is there meant to be a return here?

```suggestion
            return this.trigger;
```

**Review by hunterloftis — CHANGES_REQUESTED** [review]
Thanks for figuring out this issue.

I made a few optional suggestions; the only thing to definitely resolve is the `left` branch of `get focusElement`.

File: packages/split-button/src/SplitButton.ts (hunk 4 above)
Comment (Westbrook) [reply packages/split-button/src/SplitButton.ts:80]: Bwah! I was just like "yeah, these tests are supposed to change..." 😞

File: packages/color-wheel/src/ColorWheel.ts (hunk 2 above)
Comment (Westbrook) [reply packages/color-wheel/src/ColorWheel.ts:438]: Totally. It also doesn't "change" as much as the linter decided it was no long on style.

File: packages/picker/src/Picker.ts (hunk 3 above)
Comment (Westbrook) [reply packages/picker/src/Picker.ts:447]: In this case the property is used to overcome the typing. Typescript likes to point out that `this.selects` can be `undefined` which is not an acceptable type for the `selects` attribute, and would prefer `ifDefined` be used here to manage that. However, `Menu.selects` is a reflecting property, so it we know that it will do the work of `ifDefined` internally when supplied `undefined` as a property, so this intends to simplify the usage.

Comment (hunterloftis) [reply packages/picker/src/Picker.ts:447]: Gotcha, thanks!

**Review by hunterloftis — APPROVED** [review]
