### PR TITLE
fix: prevent reuse of applied IDs when associating Dialogs to their content

### LINKED ISSUE #2486: [Bug]: sp-dialog: Duplicate ids on conditional rendering
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-dialog

### Expected behavior

Currently the Dialog would add ids to the description automatically. Per accessibility requirement, all ids must be unique.

### Actual behavior

When having conditional rendering (in my case starting with a dropzone and then changing to a table, ids are duplicate.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Ensure that late added content does not accidentally receive already applied IDs when associating it to its parent `sp-dialog` element.

## Related issue(s)

- fixes #2486

## How has this been tested?

-   [ ] _Test case 1_
    1. Go [here](https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/12976/workflows/25d21100-1c1d-41bb-aa2f-85f6a9f4ad6d)
    2. See that the new test passes

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

### CODE REVIEW

File: packages/dialog/src/Dialog.ts [hunk 1]
```diff
@@ -47,7 +49,7 @@ function gatherAppliedIdsFromSlottedChildren(
         if (el.id) {
             ids.push(el.id);
         } else {
-            const id = idBase + `-${i}`;
+            const id = idBase + `-${i + appliedIds++}`;
```
Comment (hunterloftis) [inline packages/dialog/src/Dialog.ts:52]: It might be simpler to understand to have just one, globally-unique source of truth for the IDs:

```suggestion
            const id = `${idBase}-${appliedIds++}`;
```

**Review by hunterloftis — APPROVED** [review]

File: packages/dialog/src/Dialog.ts (hunk 1 above)
Comment (Westbrook) [reply packages/dialog/src/Dialog.ts]: Good call.
