### PR TITLE
fix(split-button): hide "selected" item from menu

### LINKED ISSUE #1456: More variant of split button can have value change
### Expected Behaviour
It looks like the More variant of SplitButton shouldn't actually have a value. It's definitely not supposed to have the button text change when selecting a different option. Here's the contribution docs link for reference: https://spectrum-contributions.corp.adobe.com/page/split-button-beta/

### Actual Behaviour
If you click the default action and then another action, but button text / selection chagnes.

### Reproduce Scenario (including but not limited to)
Easy to repro in the docs.

### LINKED ISSUE #1642: action-menu & split-button should have sync import options like picker
### Expected Behaviour
Following up on the resolution to #801 Clients should have the option to do a sync import of action-menu & split-button, so that the menus don't open with a delay because of the async overlay import.

### Actual Behaviour
This is only available in picker now.

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
- correct delivery of `sp-split-button` variants
- surface sync imports for Action Menu and Split Button patterns

## Related Issue
fixes #1642
fixes #1456

## Motivation and Context
Correctness, options.

## How Has This Been Tested?
VRT

## Screenshots (if appropriate):
https://westbrook-split-button--spectrum-web-components.netlify.app/storybook/index.html?path=/story/split-button--more-cta

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/split-button/sync/sp-split-button.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+import '../sp-split-button.js';
+
+Picker.openOverlay = async (
+    target: HTMLElement,
+    interaction: TriggerInteractions,
+    content: HTMLElement,
+    options: OverlayOptions
+): Promise<() => void> => {
+    return await Overlay.open(target, interaction, content, options);
+};
```
Comment (adixon-adobe) [inline packages/split-button/sync/sp-split-button.ts:28]: it might be worth DRYing up the `openOverlay` overrides into a Picker import.

**Review by adixon-adobe — DISMISSED** [review]
One suggestion but overall looks great!

File: packages/split-button/sync/sp-split-button.ts (hunk 1 above)
Comment (Westbrook) [reply packages/split-button/sync/sp-split-button.ts]: Agreed!

File: web-test-runner.config.js [hunk 2]
```diff
@@ -96,21 +96,21 @@ export default {
...
+        //             'browser.shell.checkDefaultBrowser': false,
+        //             'browser.bookmarks.restore_default_bookmarks': false,
+        //             'dom.disable_open_during_load': false,
+        //             'dom.max_script_run_time': 0,
+        //             'dom.min_background_timeout_value': 10,
+        //             'extensions.autoDisableScopes': 0,
+        //             'extensions.enabledScopes': 15,
+        //         },
+        //     },
+        // }),
```
Comment (adixon-adobe) [inline web-test-runner.config.js:114]: Guessing you didn't meant to check this change in

**Review by adixon-adobe — CHANGES_REQUESTED** [review]
Looks like you had some local test config changes that accidentally got checked in.

Otherwise looks great
