### PR TITLE
fix(menu): pass current focus visibility to menu items

### LINKED ISSUE #1136: menu-item keyboard focus shouldn't show
### Expected Behaviour
Hovering over a menu item should just make that item hovered, and there shouldn't be styling on menu open.

### Actual Behaviour
When you open a dropdown or action menu, the first item has hover styling (maybe for keyboard focus? But it doesn't get the blue bar). If you hover over the second item, both show the same hover styling.

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Afford the current `:focus-visible` context from the `<sp-menu>` element to its `<sp-menu-item>` children when navigating through them.
- only show the blue edge highlighting when the `:focus-visible` heuristic has been triggered.
- persist selected and hovered visual states without alteration

## Related Issue
fixes #1136 

## Motivation and Context
Clearer interface delivery.

## How Has This Been Tested?
New unit tests for both sides of the workflow, including some _special_ Firefox conciderations.

## Screenshots (if appropriate):
https://westbrook-menu--spectrum-web-components.netlify.app/components/picker

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/menu/src/Menu.ts [hunk 1]
```diff
@@ -220,10 +220,22 @@ export class Menu extends SpectrumElement {
...
     };
 
+    private forwardFocusVisibleToitem(item: MenuItem): void {
+        let shouldFocus = false;
+        try {
+            shouldFocus =
+                this.matches(':focus-visible') ||
+                this.matches('.focus-visible');
+        } catch (error) {
+            shouldFocus = this.matches('.focus-visible');
```
Comment (adixon-adobe) [inline packages/menu/src/Menu.ts:234]: So the first check can throw in some browsers? Might be worth a comment.

File: packages/picker/src/Picker.ts [hunk 2]
```diff
@@ -253,27 +253,34 @@ export class PickerBase extends SizedMixin(Focusable) {
...
+            reparentableChildren = Array.from(
+                deprecatedMenu.children
+            ) as MenuItem[];
         } else {
             reparentableChildren = Array.from(this.children).filter(
                 (element) => {
                     return !element.hasAttribute('slot');
                 }
-            );
+            ) as MenuItem[];
```
Comment (adixon-adobe) [inline packages/picker/src/Picker.ts:268]: Won't this break re-parenting of MenuDividers? There's a separate query selector to get the menu items (which also might be problematic for sub-classing, I see).

Assuming this does break for MenuDivider though, we should add a test!

Comment (adixon-adobe) [reply packages/picker/src/Picker.ts:268]: (it does seem to work on your branch, but this code still looks wrong)

**Review by adixon-adobe — CHANGES_REQUESTED** [review]

File: packages/picker/src/Picker.ts (hunk 2 above)
Comment (Westbrook) [reply packages/picker/src/Picker.ts:268]: I think it looks wrong, because it was needed for something else, but I've backed out of it 🙈

I should be able to revert this to `Element[]`.

Comment (adixon-adobe) [reply packages/picker/src/Picker.ts:268]: this is why code reviews are good! It definitely felt like there was more to the story.

File: packages/picker/src/Picker.ts [hunk 3]
```diff
@@ -271,10 +271,15 @@ export class PickerBase extends SizedMixin(Focusable) {
             return;
         }
 
-        this.restoreChildren = reparentChildren(
-            reparentableChildren,
-            this.optionsMenu
-        );
+        this.restoreChildren = reparentChildren<
```
Comment (Westbrook) [inline packages/picker/src/Picker.ts:274]: Now with types more inline with what one might think, I hope! @adixon-adobe

**Review by adixon-adobe — APPROVED** [review]
Yep -- this looks good now. Thanks!
