### PR TITLE
fix(help-text): apply aria-live to ensure full help text is read to user

### LINKED ISSUE #3377: [Bug]: sp-help-text error message suppressed when continue typing
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-help-text

### Expected behavior

When sp-help-text is used in the negative-help-text slot it is expected that the error message will be read to the user. This works great if the user simply presses a single keypress but when the user types more info into the field the error message is supressed.

### Actual behavior

The error message doesn't get read as it its reading is suppressed by the next keypress.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

Firefox, Chrome, Microsoft Edge

### How can we reproduce this issue?

1. Start JAWS or NVDA
2. Go to https://studio.webcomponents.dev/preview/Tea8IMwcfLarfCQwSnxa/src?branch=Textfield-invalid-text@7fBWg9Y3wmUwOKofZzrLDd2SRAr2&p=stories
3. Click on the first name field
4. Type 3
5. Note the error message is read
6. Delete the number and type some letters into the field
7. Type 33 into the field
8. Note the error message is not read.

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Use `aria-live="assertive"` to ensure the Help Text content (when changing) has higher screen reader priority than Textfield input.

## Related issue(s)
- fixes #3377

## How has this been tested?
-   [ ] _Test case 1_
    1. Go [here](https://assertive-help-text--spectrum-web-components.netlify.app/components/textfield/#help-text)
    2. Turn on your screen reader
    3. Focus the `Stay "Positive"` text field
    4. Type or delete anything and then keep typing
    5. Ensure that the screen reader reads ALL of the updated help text when moving on and off of the value `Positive`

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

### CODE REVIEW

File: packages/help-text/src/HelpTextManager.ts [hunk 1]
```diff
@@ -43,7 +43,10 @@ export class HelpTextManager {
         // `pass-through-help-text-${this.instanceCount}` makes the slot effectively unreachable from
         // the outside allowing the `help-text` slot to be preferred while `negative === false`.
         return html`
-            <div id=${ifDefined(this.isInternal ? this.id : undefined)}>
+            <div
+                id=${ifDefined(this.isInternal ? this.id : undefined)}
```
Comment (Rajdeepc) [inline packages/help-text/src/HelpTextManager.ts:47]: Does a truthy `this.isInternal` always specify that an `id` will be present?

Comment (Westbrook) [reply packages/help-text/src/HelpTextManager.ts:47]: Yes it does. And, while it's _technically_ possible that a custom element consumer would _unset_ the value of ID, but that would be highly irregular. Without negative intent, the `id` as set in the constructor (note that this is a helper class and not a custom element class) would always be available for use here.

As this isn't new functionality, if there's a concern we want to address here, it would be better to track it in an issue for a later update.

**Comment by hunterloftis** [comment]
Should I expect "Tell us how you are feeling today" and/or "Please be positive?"

I get neither - instead, VoiceOver gives me:
- Test
- More content available, You are currently on a text field.
- (Tab off, then on)
- Test, text contents selected, invalid data, edit.

**Review by nikkimk — APPROVED** [review]
It worked, but we should have some examples of how to use it accessibly in the docs.

**Comment by Rajdeepc** [comment]
@nikkimk Would you like to take this up?

**Review by Rajdeepc — COMMENTED** [review]
This looks very clean now and helpful! Let me know when it will be ready for review. Thanks

**Review by Rajdeepc — APPROVED** [review]
Good work!
