### PR TITLE
fix(slider): use internal "input" for value sanitation

### LINKED ISSUE #481: The value of an "sp-slider" can display outside of it's restraints
### Expected Behaviour
The display value of an `sp-slider` should stick to its restraints.

### Actual Behaviour
image

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
- Use the `input` element internal to the slider to sanitize values to avoid JS quirks in rounding values to match `step` management.
- Reduce the number of calls to `this.getBoundingClientRect()` as it can cause unnecessary layouts.

## Related Issue
fixes #481 

## Motivation and Context
Because `12.120000000000001` doesn't conform to `step="0.01"`...

## How Has This Been Tested?
Tests run just fine.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/slider/src/slider.ts [hunk 1]
```diff
@@ -299,6 +303,7 @@ export class Slider extends Focusable {
         if (this.disabled) {
             return;
         }
+        this.boundingClientRect = this.getBoundingClientRect();
```
Comment (andrewhatran) [inline packages/slider/src/slider.ts]: Nice!
