### PR TITLE
fix: allow expanding a sidenav item that has no value

### LINKED ISSUE #410: All of the items disappeared from the doc side nav
### Expected Behaviour

You should be able to select items to navigate in the sidebar of the docs page

### Actual Behaviour

The side nav is empty in the docs

### PR DESCRIPTION
**Pull request by cuberoot**
## Description

Fix it so that an `sp-sidenav-item` that has no value can be expanded. Also, make the top level sidenav items in the docs expanded by default.

## Related Issue

fixes #410 

## Motivation and Context

We need the docs to be navigable

## How Has This Been Tested?

By running the docs locally.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/sidenav/src/sidenav-item.ts [hunk 1]
```diff
@@ -91,10 +91,10 @@ export class SideNavItem extends Focusable {
         if (!this.href && event) {
             event.preventDefault();
         }
-        if (this.value && !this.disabled) {
+        if (!this.disabled) {
             if (this.hasChildren) {
                 this.expanded = !this.expanded;
-            } else {
+            } else if (this.value) {
```
Comment (Westbrook) [inline packages/sidenav/src/sidenav-item.ts]: Is there a test for this to help ensure we don't regress on this functionality?

File: documentation/src/components/side-nav.ts [hunk 2]
```diff
@@ -76,6 +76,7 @@ class SideNav extends LitElement {
                     <sp-sidenav variant="multilevel">
```
Comment (Westbrook) [inline documentation/src/components/side-nav.ts]: I missed this, but being you are here, would you mind adding the `manage-tab-index` attribute to the `sp-sidenav`?

**Comment by cuberoot** [comment]
@Westbrook test added as well as the attribute you asked for.
