### PR TITLE
fix: #2933 by adding optional variant property to SideNav

### LINKED ISSUE #2933: [Bug]: Sidenav variant property is missing in typescript type definition
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

@spectrum-web-components/sidenav

### Expected behavior

According to the [Sidenav](https://opensource.adobe.com/spectrum-web-components/components/sidenav/#multi-level) documentation, users can this property to render multi-layers Side navigation. This property should be usable in a typescript project. 

### Actual behavior

The typescript type definition of this property is missing. https://unpkg.com/browse/@spectrum-web-components/sidenav@0.13.9/src/Sidenav.d.ts. It will lead to ts compile error in a typescript project if I use it.

### Screenshots

image

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

1. `npm i @spectrum-web-components/sidenav@latest`
2. `cd node_modules/@spectrum-web-components/sidenav`
3. `code src/sp-sidenav.d.ts`

or just go to https://unpkg.com/browse/@spectrum-web-components/sidenav@0.13.9/src/Sidenav.d.ts

### Sample code that illustrates the problem

The latest type definition for `SideNav` looks like:
```
/**
 * @element sp-sidenav
 *
 * @slot - the Sidenav Items to display
 * @fires change - Announces a change in the `value` property of the navigation element.
 * This change can be "canceled" via `event.preventDefault()`.
 */
export declare class SideNav extends Focusable {
    static get styles(): CSSResultArray;
    private items;
    startTrackingSelectionForItem(item: SideNavItem): void;
    stopTrackingSelectionForItem(item: SideNavItem): void;
    rovingTabindexController: RovingTabindexController<SideNavItem>;
    manageTabIndex: boolean;
    value: string | undefined;
    private handleSelect;
    focus(): void;
    blur(): void;
    click(): void;
    get focusElement(): SideNavItem | SideNav;
    private isDisabledChild;
    private handleSlotchange;
    protected render(): TemplateResult;
    protected willUpdate(): void;
    protected updated(changes: PropertyValues): void;
}
```

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by jianliao**
## Description

Fixed #2933 

## Related issue(s)
#2933 

-

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

File: packages/sidenav/src/Sidenav.ts [hunk 1]
```diff
@@ -74,6 +74,9 @@ export class SideNav extends Focusable {
     @property({ reflect: true })
     public value: string | undefined = undefined;
 
+    @property({ reflect: true })
```
Comment (Westbrook) [inline packages/sidenav/src/Sidenav.ts:77]: Can you add a description as to what this does so that it populates to: https://63ed2ff266722307437d351a--spectrum-web-components.netlify.app/components/sidenav/api/#attributes-and-properties

image

Local preview available via `yarn docs:start`. 

Here's an example of a property with a description: https://github.com/adobe/spectrum-web-components/blob/main/packages/accordion/src/Accordion.ts#L42

As seen in: https://63ed2ff266722307437d351a--spectrum-web-components.netlify.app/components/accordion/api/

image

Comment (jianliao) [reply packages/sidenav/src/Sidenav.ts:80]: Done.
image

Comment (jianliao) [reply packages/sidenav/src/Sidenav.ts:80]: I also set the default value as `undefined`.

Comment (Westbrook) [reply packages/sidenav/src/Sidenav.ts:80]: Interesting, does it not set a default as `undefined` by way of the `?` usage? TIL!

Thanks for this.

**Review by Westbrook — APPROVED** [review]
LGTM! Thanks for the docs addition, too.

File: packages/sidenav/src/Sidenav.ts (hunk 1 above)
Comment (jianliao) [reply packages/sidenav/src/Sidenav.ts:80]: The default column will be empty if I don't explicitly set it as undefined.
