### PR TITLE
fix(picker): stop the click events from reaching the elements below picker-tray

### LINKED ISSUE #5042: [Bug]: (iOS) Tapping on a button in the sp-menu will also tap on a button directly underneath it
### Code of conduct

- [x] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-menu, sp-picker

### Expected behavior

While using the `sp-picker` in iOS Safari, tapping on a button in the `sp-menu` should **not** also tap on a button directly underneath it. This seems related to a [previously fixed issue](https://github.com/adobe/spectrum-web-components/issues/4461); however, checking out version SWC 47.0.1 does not resolve the issue in the Express app and mobile web.

### Actual behavior

While using the `sp-picker` in iOS Safari, tapping on a button in the `sp-menu` will also tap on a button directly underneath it.

### Screenshots

Two different examples of this problem occurring:

Image

https://github.com/user-attachments/assets/9114ae2c-51ee-42e0-9df3-4f0e5971a97f

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

**On Express mobile app:**
1. Open Editor
2. Go to "Share" to share any asset. This will open up the Share Sheet dialog.
3. Input username and tap Return
4. Click on the permission dropdown [Can edit/comment].
5. Try to tap on the "Can comment" option at the same location as 'Cancel' or 'Invite to edit/comment' button text are located.
6. Observed - the click event is propagated to the buttons ["Cancel" and "invite to edit"]behind the panel.

**On mobile web, which may be easier to troubleshoot and test for developers and QE:**
1. Install xcode > Settings > Platform > Install iOS 16.4 Simulator
2. Open Simulator for iPhone 14 Pro
3. Navigate to new.express.adobe.com (prod)
4. Go to "Share" to share any asset. This will open up the Share Sheet dialog.
5. Input a username you'd like to share with, and tap return
6. Click on the permission dropdown (Can edit/comment)
7. Try to tap on the "Can comment" option at the same location as overlaying the button text, "Cancel"
8. Notice the Cancel button is clicked instead of the "Can Comment" and the overlay is closed.

Note: To reproduce the issue, the clicking of the overlaying button text needs to align directly above the button text underneath it (not the button itself, but the text within the button).

We were able to implement a temporary workaround where we addEventListener for `touchstart` and preventDefault and stopPropagation whenever the sp-menu is visible. Once it is closed, we removeEventListener.

### Sample code or abstract reproduction which illustrates the problem

_No response_

### Severity

None

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by TarunAdobe**
## Description

Stop the click events to reach the element below tray when we open a picker in iOS <17

## Related issue(s)

- fixes #5042

## Motivation and context

* Prevents the event leaking out of the dialog to the element below it.
* This is a workaround for a bug in iOS <17 where the event leaks out of the dialog to the element below it. 

## How has this been tested?

- Go [here](https://picker-background-click--spectrum-web-components.netlify.app/storybook/?path=/story/picker--background-click-test&globals=color:dark) in iOS<17 
    - [ ] Open the picker and make a selection on the tray.
    - [ ] There should not be any console log from the button getting clicked.

-   Manually Tested. See the attached Video below for before and After:

### Before
[screen-capture.webm](https://github.com/user-attachments/assets/57520995-d025-4042-8c00-988df3519ddf)

### After
[screen-capture (1).webm](https://github.com/user-attachments/assets/d5b9d014-e866-4ece-b496-f260a780247b)

-   [x] Did it pass in Desktop?
-   [x] Did it pass in Mobile?
-   [x] Did it pass in iPad?

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by TarunAdobe** [comment]
Since this issue happens only in specific version(s) of iOS combined with the fact that we don't have a good testing infrastructure setup for mobile - I couldn't figure out a way to write tests for this which won't pass always. So I attached a before and after video in the description. 
Apart from this I did test and verified manually as well as through our tests that everything else related to the menu and picker behaviour remains exactly the same!

File: packages/overlay/src/OverlayDialog.ts [hunk 1]
```diff
@@ -163,6 +163,16 @@ export function OverlayDialog<T extends Constructor<AbstractOverlay>>(
                     finish(el, index)
                 );
             });
+
+            /**
+             * Prevents the event leaking out of the dialog to the element below it.
+             * This is a workaround for a bug in iOS <17 where the event leaks out of the dialog to the element below it. 
+             * Issue - https://github.com/adobe/spectrum-web-components/issues/5042
+             */
+            this.dialogEl.addEventListener('pointerup', (event) => {
```
Comment (rubencarvalho) [inline packages/overlay/src/OverlayDialog.ts:172]: is `pointerup` enough? Have we considered adding `touchend`?

File: packages/overlay/src/OverlayDialog.ts
Comment (rubencarvalho) [inline packages/overlay/src/OverlayDialog.ts:1]: Does `OverlayDialog` only get instantiated once, or is there a chance that the dialog may be re-instantiated? If so, should we define the event handler as a class method and attach/detach it?

File: packages/overlay/src/OverlayDialog.ts (hunk 1 above)
Comment (TarunAdobe) [reply packages/overlay/src/OverlayDialog.ts:172]: Either of the two `pointerup` or `touchend` was working fine and similar to the other one in simulators... Didn't test it on a real device. Should I stop the propagation for both?

File: packages/overlay/src/OverlayDialog.ts
Comment (TarunAdobe) [reply packages/overlay/src/OverlayDialog.ts:1]: Yess! Thanks for the catch. Totally slipped my mind that we need to avoid attaching the event listener multiple times and clean it properly. Will update the code to do that. 
I was thinking of having the logic of attaching and removing the listeners abstracted out and then will call that function to attach the listener when the dialog opens and remove it when it closes?

File: packages/overlay/src/OverlayDialog.ts (hunk 1 above)
Comment (rubencarvalho) [reply packages/overlay/src/OverlayDialog.ts:172]: I’m wondering if there’s any downside to having `touchend` as a “safe fallback”... I don’t think it should be necessary, but without real device testing, it is hard for me to say 🤷

Comment (TarunAdobe) [reply packages/overlay/src/OverlayDialog.ts:172]: I don't particularly see any other downside than the fact that in the worst case we're adding 1 extra event listener....so

**Review by rubencarvalho — APPROVED** [review]
LGTM 🚢

**Comment by caseyisonit** [comment]
@TarunAdobe should we add in a test to confirm this behavior?

**Comment by TarunAdobe** [comment]
> @TarunAdobe should we add in a test to confirm this behavior? or is this a device emulation issue?

I made a comment on this PR abt this that got lost between all the bot comments but TLDR; Since this issue happens only in specific version(s) of iOS combined with the fact that we don't have a good testing infrastructure setup for mobile - I couldn't figure out a way to write tests for this which always end up passing. And so it'd be useless :(
