### PR TITLE
fix: keep parent overlays open when not closing child hover overlays

### LINKED ISSUE #2693: [Bug]: Overlayed popover with action buttons with self-managed tool-tips closes when button is clicked
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay // OverlayTrigger

### Expected behavior

Opened popover within overlay-trigger containing action buttons with self-managed tooltips should not close when user clicks on one of those containing action buttons.

### Actual behavior

When a user clicks on an action button with self-managed tooltips the popover containing those buttons will be closed.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/tz9nxXPZYJAZp4XZbZ2a
2. Click on left button to open popover with action buttons
3. Hover over buttons to verify tooltips are displaying
4. Click button
5. Overlaid popover dismisses
6. Compare with overlay triggered by second main button
7. This popover doesn't dismiss on action button clicks

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/tz9nxXPZYJAZp4XZbZ2a

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Prevent clicks within ancestor overlays from closing those ancestor overlays.

## Related issue(s)
- fixes #2693

## How has this been tested?

-   [ ] _Test case 1_
    1. Go [here](https://overlay-stack-mangement--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--deep)
    2. Click the first buttons to open the Popover
    3. Hover the first button in the Popover to open the Tooltip
    4. Click the button associated to the Tooltip
    5. See that the Popover is still open

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: packages/overlay/src/overlay-stack.ts [hunk 1]
```diff
@@ -611,9 +611,11 @@ export class OverlayStack {
         while (index && overlaysToClose.length === 0) {
             index -= 1;
             const overlay = this.overlays[index];
+            const path = event.composedPath();
```
Comment (hunterloftis) [inline packages/overlay/src/overlay-stack.ts:614]: I may not understand what's being checked here enough to label it properly, but consider something like this?

```suggestion
            const path = event.composedPath();
            const isOutsideTriggerAndContent = (!path.includes(overlay.trigger) || overlay.interaction !== 'hover') && !path.includes(overlay.overlayContent;
```

File: packages/overlay/src/overlay-stack.ts [hunk 2]
```diff
@@ -611,9 +611,11 @@ export class OverlayStack {
...
             if (
-                !event.composedPath().includes(overlay.trigger) ||
-                overlay.interaction !== 'hover'
+                (!path.includes(overlay.trigger) ||
+                    overlay.interaction !== 'hover') &&
+                !path.includes(overlay.overlayContent)
```
Comment (hunterloftis) [inline packages/overlay/src/overlay-stack.ts:618]:
```suggestion
                isOutsideTriggerAndContent
```

**Review by hunterloftis — APPROVED** [review]

File: packages/overlay/src/overlay-stack.ts (hunk 1 above)
Comment (Westbrook) [reply packages/overlay/src/overlay-stack.ts:624]: Good call. The naming here is hard, but I've paired it with an update comment from the change that broke this, so hopefully it's more understandable in the future.
