### PR TITLE
fix(table): Add aria-rowcount to virtualized tables

### LINKED ISSUE #3393: [Bug][a11y]: Virtualized Table should include aria-rowcount attribute
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Table

### Expected behavior

When a Table is virtualized it should include an [`aria-rowcount`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-rowcount) attribute to communicate the number of total rows in the table, otherwise screen readers will announce only the number of rendered rows.

### Actual behavior

Virtualized table lacks `aria-rowcount` attribute, so screen readers will announce only the number of rendered rows rather than the total rows in the table.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by blaabaer**
## Description

The `sp-table` component can be virtualized, which only renders table rows that are currently visible in the viewport, which helps with performance on large tables. However, this can trip up screenreaders, which only detect and announce the rendered rows, and not the true size of the table. `aria-rowcount` is a screenreader attribute which announces the true unvirtualized size of the table.

This PR implements the automatic application of `aria-rowcount` for virtualized tables. 

## Related issue(s)

- fixes #3393 

## Motivation and context

Accuracy and efficacy of screenreader accessibility.

## How has this been tested?

-   [x] Run storybook - Table > Virtualized > [Any of these]
    1. Inspect the `sp-table` element
    2. Observe that the `aria-rowcount` value is correct.
-   [x] Visit docs site - Table > Virtualized
    1. Inspect the `sp-table` element
    2. Observe that the `aria-rowcount` value is correct.

## Screenshots (if appropriate)

image

image

Before my changes
image

After my changes
image

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

File: packages/table/src/Table.ts [hunk 1]
```diff
@@ -507,6 +507,11 @@ export class Table extends SizedMixin(SpectrumElement, {
                 }
             );
         }
+
+        // Ensures screenreaders can announce the true size of the table
+        // despite virtualization only rendering a subset of rows.
+        this.setAttribute('aria-rowcount', `${this.items.length}`);
```
Comment (Westbrook) [inline packages/table/src/Table.ts:513]: Because this code path is only run when `items` has a `length` were this table to be used with filtering or searching and the length could conceivable become `0`, there is a change that this data would be out of date. Should we remove this attribute in the implied `else` at line 474?

**Review by Westbrook — APPROVED** [review]
LGTM! Thanks @blaabaer 🙇🏼
