### PR TITLE
fix(picker,action-menu,split- button): update interaction model

### LINKED ISSUE #2966: <sp-picker> doesn't follow established platform mouse interaction semantics
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

`<sp-picker>` is offered as a spectrum-aware replacement for  HTML's `<select>` element, but it doesn't follow the platform drop-down menu pointer semantics established on all the major platforms for many years.

Platform menu/`<select>` element

- show menu on mouse-down
- if mouse held, dragging over menu entry selects it on mouse up, menu closes
- if mouse released, menu stays up until next click
- click to select menu entry

_and_

`<sp-picker>`

- show menu on mouse-up
- menu stays up until next click
- click to chose menu entry

this turns every menu interaction into click->release->move->click->release, much more fiddly than click->move->release for a menu selection.

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Support opening the element's Menu and selecting one of its Menu Items with a single pointer button interaction.

## Related issue(s)
- fixes #2966

## How has this been tested?
-   [ ] _Test case 1_
    1. Go [here](https://picker-interaction--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--submenu)
    2. Make sure the Action Menu is closed
    3. Pointerdown on the Action Button
    4. See that the Menu opens
    5. With the pointer STILL DOWN move to a Menu Item in the _second_ fly out Menu
    6. Release the pointer
    7. See that all of the correct "selections" were made
-   [ ] _Test case 2_
    1. Go [here](https://picker-interaction--spectrum-web-components.netlify.app/storybook/?path=/story/picker--default)
    2. Pointerdown on the Picker
    3. Keep it down
    4. See that the Menu opened
    5. Move to a Menu Item
    6. Release the pointer
    7. See that the selection is made
-   [ ] _Test case 3_ For good measure
    1. Go [here](https://picker-interaction--spectrum-web-components.netlify.app/storybook/?path=/story/picker--default)
    2. Click on the Picker
    3. See that the Menu opened
    4. Move to a Menu Item
    5. Click the Menu Item
    6. See that the selection is made

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: packages/action-menu/test/index.ts [hunk 1]
```diff
@@ -566,12 +566,16 @@ export const testActionMenu = (mode: 'sync' | 'async'): void => {
 
             expect(openSpy.callCount).to.equal(1);
         });
-        it('opens, then closes, on subsequent clicks', async () => {
+        it('opens, then closes, on subsequent clicks', async function () {
```
Comment (najikahalsema) [inline packages/action-menu/test/index.ts:569]: Are we specifically testing that the action menu opens on pointer down? Because, to me, a click event feels ambiguous, like the menu could open on either pointerUp or pointerDown. 

I know that there's changes to `Picker.ts` that makes it pretty clear what we expect to happen on pointer up (to me), so why doesn't the Action Menu also need this clarification?

**Review by najikahalsema — COMMENTED** [review]
Appreciate the refinements to the existing tests. I have a question, though.

File: packages/action-menu/test/index.ts (hunk 1 above)
Comment (Westbrook) [reply packages/action-menu/test/index.ts:569]: The only _net new_ test is in Picker, but I can add a similar version to the other packages, too. Good call!

**Review by najikahalsema — APPROVED** [review]
Thank you for adding those tests! :D
