### PR TITLE
fix: normalize "event" and "error" argument names

### LINKED ISSUE #153: We should standarize on basic variable names
### Expected Behaviour

Our code should be consistent for variable names. Currently we use some various short forms for `event` and `error`. I propose that we use the full names everywhere as that is a simple rule to remember and is the easiest to read. I am open to discussion though. We at least need to be consistent.

### Actual Behaviour

We use all kinds of variable names (e.g. evt, e, etc)

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
- update existing code to meet the argument naming standard
- create and apply an eslint plugin to prevent this from happening with understood names in the future.

## Related Issue
fixes #153

## Motivation and Context
Code should be more predictable

## How Has This Been Tested?
- wrote some non-compliant code and then tried to commit it, eslist said "NO"

## Screenshots (if appropriate):
image

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: utils/eslint/index.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
+module.exports = {
```
Comment (Westbrook) [inline utils/eslint/index.js]: Just learning that there is a `linters` folder in the project 😮 

This packages should likely live there, right?

Later, we should look into moving all three, as well as the example project, into `/packages/` so that Greenkeeper and Lerna can manage them better...

Comment (cuberoot) [reply utils/eslint/index.js]: Yah, looks like there's a pattern for custom linters, so it would be good to follow it. I will defer to you on the packages thing. I'm still ramping on lerna.
