### PR TITLE
fix: use type="search" for nicer virtual keyboards

### LINKED ISSUE #1752: [Feat]: [Search] Better use of native search/form relations
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-search

### Description of the requested feature

You can use an `input[type="search"]`, `input[name="search"]`, or `input[id*="search"]` inside a `form[action]` to display the “search” action in the virtual keyboard. `sp-search` currently uses `input[type="text"]` which does not afford this interaction. Customize this internally or surface properties by which this can be customized on a case by case basis.

### Mockups or screenshots

_No response_

### Implementation notes or ideas

- this should likely just _always_ be like this
- if we surface customization, how does this interact with #926 
- should this accept/sprout an `<input>` element into the light DOM?
- supporting "Search" in the virtual keyboard will require mobile testing

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Ensure that attributes are applied correctly to deliver the "Search" button in a mobile virtual keyboard.
- add `type="search"`
- apply `action` attribute to the `<form>` even when unavailable

## Related issue(s)

- fixes #1752 

## Motivation and context
Easier use of the element in mobile.

## How has this been tested?

-   [ ] _Test case 1_
    1. Go to https://type-search--spectrum-web-components.netlify.app/ in mobile
    2. Open the nav drawer
    3. Type into the search field `Test`
    4. See a modified "Go"/"Submit" button
    5. Press it
    6. See that the focus has been moved into the search results on "submit"
-   [ ] _Test case 2_
    1. Go to https://type-search--spectrum-web-components.netlify.app/components/search
    2. Tap into one of the search fields
    3. See that the virtual keyboard surfaces a "Search" button

## Screenshots (if appropriate)
Image from iOS (1)

## Types of changes
-   [x] New feature (non-breaking change which adds functionality)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: documentation/src/components/side-nav-search.ts [hunk 1]
```diff
@@ -149,6 +149,15 @@ class SearchComponent extends LitElement {
         }
     }
 
+    preventDefault(event: Event): void {
```
Comment (hunterloftis) [inline documentation/src/components/side-nav-search.ts:152]: nit: this would be more descriptive as `handleSubmit` since it's now doing more than just preventing default actions.

**Review by hunterloftis — DISMISSED** [review]

File: documentation/src/components/side-nav-search.ts (hunk 1 above)
Comment (Westbrook) [reply documentation/src/components/side-nav-search.ts:152]: 👍🏼
