### PR TITLE
Fix Slider component scroll number-field to update the slider value

### LINKED ISSUE #2543: [Bug]: Using an editable <sp-slider> component, and changing the input value with mouse wheel scroll, the slider doesn't change it's value according to the input new value
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider

### Expected behavior

In the slider component, focus the input number field and mouse wheel scroll to change the input value.
The value of the number input changes, but the slider should also update with the number input value.

Similar behaviour: using the arrow key up and down, it updated both the input value and the slider.

### Actual behavior

In the slider component, focus the input number field and mouse wheel scroll to change the input value.
The value of the number input changes, but the slider does not update with the number input value.

### Screenshots

https://user-images.githubusercontent.com/1075995/186917934-41517ebe-6f7a-4346-bb78-60821d99170a.mov

The first 5 seconds of the video, show the interaction with the number input via mouse wheel scroll, the rest of the video by using the keyboard arrow up/down.

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Go to editable Slider component
2. Click on number field input
3. Mouse Wheel Scroll to change the number input value
4. Check that the slider to the left of the input doesn't change
5. Try to change the input value with keyboard key
6. Check that the slider to the left of the input changes according to the value of the number input value

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by danchitiga**
## Related issue(s)

- fixes #2543

## How has this been tested?

-   [ ] _Test case 1_
    1. Go to Storybook, to editable slider: https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/slider--editable
    2. Click the number input field, and mouse scroll to change the value
    3. Slider on the left of the number input is inert
-   [ ] _Test case 2_
    1. Go to Documentation site, to editable slider: https://chitiga-daniel-editable-slider-fix--spectrum-web-components.netlify.app/components/slider/
    2. Click the number input field, and mouse scroll to change the value
    3. Slider on the left of the number input is changing according to the value inside the number input

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

File: packages/slider/src/Slider.ts [hunk 1]
```diff
@@ -385,12 +385,12 @@ export class Slider extends ObserveSlotText(SliderHandle, '') {
...
     private handleNumberInput(event: Event & { target: NumberField }): void {
         const { value } = event.target;
-        if (event.target?.stepperActive && !isNaN(value)) {
+        if (event.target?.managedInput && !isNaN(value)) {
             this.value = value;
             return;
         }
         // Do not apply uncommited values to the parent element unless interacting with the stepper UI.
-        // Stop uncommited input from being annoucned to the parent application.
+        // Stop uncommited input from being annouced to the parent application.
```
Comment (Westbrook) [inline packages/slider/src/Slider.ts:393]:
```suggestion
        // Stop uncommitted input from being announced to the parent application.
```

**Review by Westbrook — APPROVED** [review]
@danchitiga, thanks so much for the fix here, it looks great!
