### PR TITLE
fix(dropdown): improve accessibility

### LINKED ISSUE #764: Dropdown does not take focus when opens w/ iOS + VO
### Expected Behaviour
opening the dropdown with iOS & VO focus should move to the dropdown entries.

### Actual Behaviour
Focus remains on the trigger when the dropdown opens. swiping right moves to the next element in the page not the dropdown entries

### Reproduce Scenario (including but not limited to)
https://opensource.adobe.com/spectrum-web-components/components/dropdown/examples

#### Steps to Reproduce
- https://opensource.adobe.com/spectrum-web-components/components/dropdown/examples
- Turn on VO
- focus onto the dropdown
- double tap to open the dropdown
on iPadOS 14 the dropdown opens but focus does not move to the choices in the dropdown.
on iOS 13 the dropdown does not even open.

#### Platform and Version
iPadOS14 - Safari - VO
iOS13 - Safari - VO

### LINKED ISSUE #908: Menu shows focus border on click in safari
### Expected Behaviour
A menu doesn't show a blue focus border on click.

### Actual Behaviour
On safari it does. Easy to repro in the doc pages for Menu, Action Menu, & Dropdown

#### Steps to Reproduce
1. Go to https://opensource.adobe.com/spectrum-web-components/components/menu
2. Click on a menu

#### Screenshots
Screen Shot 2020-09-28 at 11 16 28 AM

### PR DESCRIPTION
**Pull request by Westbrook**
## Description 
Update the accessibility tree of the `Dropdown` pattern and its derivative components (`ActionMenu` and `SplitButton`) as well as the `Menu` pattern that they leverage internally.

Preview available: https://5f6e5921adb59e0095ccb7c2--spectrum-web-components.netlify.app/

*This does:*
- correct the focus target of open "dropdowns" to ensure that VO (macOS, iOS) enters/announces their content correctly
- moves from using `:focus` to `[focused]` to ensure transient visual state
- matches tests to these patterns
- updates to the latest aXe-core release
  - adjust usage of `role="group"` as per its updated rules
- populates `MenuItems` with `id`s when missing
- differentiates functionality between `option`s and `menuitem`s
- uses `div` elements over `button`s in `<sp-menu-item>`

*This does NOT:*
- use the `role=combobox` pattern
  - will follow up in the area when we have better information on making this x-browser compliant and a path to supporting the requirement of a `textfield` as a child of this role
- handle moving backward in the tab order in iOS and leaving the overlay
- applying size and count attributes

## Related Issue
fixes #764
refs #292
fixes #908

## Motivation and Context
Components should be accessible x-browser, x-context, etc.

## How Has This Been Tested?
- aXe-core unit testing
- manually review with macOS and iOS VO features
- visual regressions

## Screenshots (if appropriate):
image
image

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/menu/src/Menu.ts [hunk 1]
```diff
@@ -63,13 +63,11 @@ export class Menu extends SpectrumElement {
     }
 
     public focus(): void {
-        if (this.menuItems.length === 0) {
+        if (!this.menuItems.length) {
```
Comment (adixon-adobe) [inline packages/menu/src/Menu.ts:66]: Why did you need this change -- is this just a code style choice, or is there something subtle I'm missing?

File: packages/menu/src/MenuItem.ts [hunk 2]
```diff
@@ -83,6 +90,41 @@ export class MenuItem extends ActionButton {
...
+            : html`
+                  <div
+                      id="button"
+                      class="button"
+                      aria-label=${ifDefined(this.label)}
+                  >
+                      ${this.buttonContent}
+                  </div>
+              `;
+    }
```
Comment (adixon-adobe) [inline packages/menu/src/MenuItem.ts:109]: Hadn't realized this extended from ActionButton -- neat. Whenever something like a core render method is overridden I try to think about maintainability. Since the only difference is the tag name, is that something you could parameterize?

**Review by adixon-adobe — COMMENTED** [review]
A couple of questions that might lead to a few more changes. Overall looks great!

File: packages/menu/src/Menu.ts (hunk 1 above)
Comment (Westbrook) [reply packages/menu/src/Menu.ts:66]: Just style, I had removed this check at one point and then re-added it not knowing the style changed. There _may_ be some slight amount of type security outside of the TS space in the small fraction of time `this.menuItems === undefined`, but I don't know enough V8/timing to confirm.

File: packages/menu/src/MenuItem.ts (hunk 2 above)
Comment (Westbrook) [reply packages/menu/src/MenuItem.ts:109]: We could make the source render method more composable so that we only have to override part of it:
```
protected render(): TemplateResult {
    return this.isAnchor ?  this.renderAnchor : this.renderButton;
}
protected get renderAnchor() {}
protected get renderButton() {}
```
That's probably nicer system wide, I'll take  swing at it.

**Comment by Westbrook** [comment]
@adixon-adobe this has been updated. It's got a couple of settings and changes that it would be good to have in #912 to speed/stabilize the CI process while we lock down the docs/visual regression cache. Let me know if you see any other good suggestions herein!

**Review by adixon-adobe — APPROVED** [review]
Looks good -- thanks!
