### PR TITLE
fix(menu): add support for submenu interactions

### LINKED ISSUE #146: Extend <sp-menu/> to support Menu Nested pattern
### Expected Behaviour
<sp-menu /> can have nested menus like https://opensource.adobe.com/spectrum-css/menu.html#nested

### Actual Behaviour
It cannot.

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Add support for submenu content in `<sp-menu-item>` elements.

### To dos:
- [x] review `<sp-menu>` width application in submenus as it relates to breaking in the middle of words
- [x] maintain "active" state on the anchor element of open submenus
- [x] ensure ALL menus are closed when clicking away after opening multiple submenus
- [x] prevent multiple sibling submenus being open at the same time
- [x] ensure submenus reopen after clicking on them the first time
- [x] expand stories
  - [x] explain eventing
  - [x] as "context menu"
- [x] add tests
- [x] fix existing tests
- [x] review file size/performance side effects
  - the perf diff seems reasonable here
  - the file size diff seems a little larger than I expected, there may be room to further optimize this, but it doesn't feel like it should be a block at this stage
- [x] add documentation

## Related issue(s)
- fixes #146

## Motivation and context
Deliver more expansive menu content accessibly.

## How has this been tested?

-   [ ] _Test case 1_
    1. Go [here](https://sub-menu--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--submenu)
    2. Expect the layout of the second submenu to be a little bit wonky to start, it's opened by default for the VRTs which account for the timing needed to make this work correctly, [see screen shot](https://c166d9d48e0a89bf135470b620d0cec6--spectrum-web-components.netlify.app/review/#SubmenuStories/submenu.png).
    3. Click away from the menus
    4. See that the ALL close
    5. Click the hamburger button
    6. Mouse in and out of the various menus and make a selection of `Brooklyn > Ft. Greene > S. Elliot Pl`
    7. See that the selection is represented in the page.
-   [ ] _Test case 2_
    1. Go [here](https://sub-menu--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--submenu)
    2. Expect the layout of the second submenu to be a little bit wonky to start, it's opened by default for the VRTs which account for the timing needed to make this work correctly, [see screen shot](https://c166d9d48e0a89bf135470b620d0cec6--spectrum-web-components.netlify.app/review/#SubmenuStories/submenu.png).
    3. Click away from the menus
    4. See that the ALL close
    5. Tab to the hamburger menu
    6. Press `Space`
    7. See the menu open
    8. Press `ArrowDown`
    9. See "Brooklyn" focused
    8. Press `ArrowDown`
    9. See "Manhattan" focused
    10. Press `ArrowRight`
    11. See the submenu open and "Union Square" focused
    12. Press `ArrowRight`
    13. See the submenu open and "14th St" focused
    14. Press `Enter`
    15. See ALL the menus close
    16. See the selection represented in the page
-   [ ] _Test case 3_
    1. Go [here](https://sub-menu--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--context-menu)
    2. Right click the page
    3. Use various selection methods (pointer or keyboard) to choose `Select Layer > Rectangle`
    4. See the selection represented in the page
-   [ ] _Test case 4_
    1. Go [here](https://sub-menu--spectrum-web-components.netlify.app/components/menu-item/#submenu)
    2. Interact with the submenu demo
    3. See that is opens/closes via expected interactions (pointer and keyboard)

## Types of changes
-   [x] New feature (non-breaking change which adds functionality)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Westbrook** [comment]
cc: @andreidinu

File: packages/menu/src/MenuItem.ts [hunk 1]
```diff
@@ -276,6 +330,110 @@ export class MenuItem extends LikeAnchor(Focusable) {
...
+                'pointerenter',
+                this.handleSubMenuPointerenter
+            );
+            this.submenu.addEventListener('change', this.handleSubMenuChange);
+            const popover = document.createElement('sp-popover');
+            popover.append(this.submenu);
+            this.submenu.tabIndex = 0;
+            this.submenu.removeAttribute('slot');
+            const closeOverlay = openOverlay(this, 'click', popover, {
+                placement: 'right-start',
```
Comment (spdev3000) [inline packages/menu/src/MenuItem.ts:393]: should this be customized to be "left-start" for dir="rtl"? and using "right-start" as default.

File: packages/menu/src/MenuItem.ts [hunk 2]
```diff
@@ -276,6 +330,110 @@ export class MenuItem extends LikeAnchor(Focusable) {
...
+
+    protected leaveTimeout?: ReturnType<typeof setTimeout>;
+
+    protected handlePointerleave(): void {
+        if (this.hasSubMenu && this.open) {
+            this.active = true;
+            this.leaveTimeout = setTimeout(() => {
+                delete this.leaveTimeout;
+                if (this.closeOverlay) this.closeOverlay(true);
+            }, 100);
```
Comment (spdev3000) [inline packages/menu/src/MenuItem.ts:356]: should this timing (100) be defined as a CONST?

Comment (Westbrook) [reply packages/menu/src/MenuItem.ts:356]: I'm also not sure that `100` is the perfect number here, but it seemed like a good start when I stole it from your implementation. 😬

File: packages/menu/src/MenuItem.ts [hunk 3]
```diff
@@ -276,6 +324,108 @@ export class MenuItem extends LikeAnchor(Focusable) {
         }
     }
 
+    public closeOverlay?: (leave?: boolean) => Promise<void>;
```
Comment (hunterloftis) [inline packages/menu/src/MenuItem.ts:327]: 👍  more readable than `isSubmenu` above.

File: packages/menu/src/MenuItem.ts [hunk 4]
```diff
@@ -276,6 +324,108 @@ export class MenuItem extends LikeAnchor(Focusable) {
...
+        this.openOverlay({ immediate: true });
+    }
+
+    protected handlePointerenter(): void {
+        if (this.leaveTimeout) {
+            clearTimeout(this.leaveTimeout);
+            delete this.leaveTimeout;
+        } else {
+            this.openOverlay();
+        }
```
Comment (hunterloftis) [inline packages/menu/src/MenuItem.ts:339]: An option for an early return in case you like it:

```suggestion
        if (this.leaveTimeout) {
            clearTimeout(this.leaveTimeout);
            delete this.leaveTimeout;
            return;
        }
        this.openOverlay();
```

File: packages/menu/src/MenuItem.ts [hunk 5]
```diff
@@ -276,6 +324,108 @@ export class MenuItem extends LikeAnchor(Focusable) {
...
+            this.active = true;
+            this.leaveTimeout = setTimeout(() => {
+                delete this.leaveTimeout;
+                if (this.closeOverlay) this.closeOverlay(true);
+            }, POINTERLEAVE_TIMEOUT);
+        }
+    }
+
+    protected handleSubmenuChange = (): void => {
+        this.click();
```
Comment (hunterloftis) [inline packages/menu/src/MenuItem.ts:355]: If this is equivalent to `this.openOverlay({ immediate: true });`, it might be clearer to call that directly instead of simulating a click. Or is a click event & bubbling necessary to be listened to higher up?

File: packages/menu/src/MenuItem.ts [hunk 6]
```diff
@@ -276,6 +324,108 @@ export class MenuItem extends LikeAnchor(Focusable) {
...
+        if (this.leaveTimeout) {
+            clearTimeout(this.leaveTimeout);
+            delete this.leaveTimeout;
+        }
+    };
+
+    public async openOverlay({
+        immediate,
+    }: { immediate?: boolean } = {}): Promise<void> {
+        if (this.hasSubmenu && !this.open) {
```
Comment (hunterloftis) [inline packages/menu/src/MenuItem.ts:368]: It looks we could drop a level of branching throughout this whole method via `if (this.open || !this.hasSubmenu) return`

File: packages/menu/src/MenuItem.ts [hunk 7]
```diff
@@ -276,6 +324,108 @@ export class MenuItem extends LikeAnchor(Focusable) {
...
+            this.open = true;
+            this.submenu = (
+                this.shadowRoot.querySelector(
+                    'slot[name="submenu"]'
+                ) as HTMLSlotElement
+            ).assignedElements()[0] as Menu;
```
Comment (hunterloftis) [inline packages/menu/src/MenuItem.ts:374]: Maybe an opportunity for https://lit.dev/docs/api/decorators/#queryAssignedElements?

File: packages/menu/src/MenuItem.ts [hunk 8]
```diff
@@ -276,6 +324,108 @@ export class MenuItem extends LikeAnchor(Focusable) {
...
+            this.submenu.addEventListener('change', this.handleSubmenuChange);
+            const popover = document.createElement('sp-popover');
+            popover.append(this.submenu);
+            this.submenu.tabIndex = 0;
+            this.submenu.removeAttribute('slot');
+            this.menuData.focusRoot?.submenuOpened(this);
+            const closeOverlay = openOverlay(this, 'click', popover, {
+                placement: this.isLTR ? 'right-start' : 'left-start',
+                receivesFocus: 'auto',
+                delayed: !immediate && false,
```
Comment (hunterloftis) [inline packages/menu/src/MenuItem.ts:388]: I'm not sure I understand what `!immediate && false` is doing here - will this not always evaluate to `delayed: false`?

File: packages/overlay/src/overlay-stack.ts [hunk 9]
```diff
@@ -307,9 +311,15 @@ export class OverlayStack {
...
-        activeOverlay.addEventListener('close', () => {
-            this.hideAndCloseOverlay(activeOverlay);
-        });
+        activeOverlay.addEventListener('close', ((
+            event: CustomEvent<OverlayCloseReasonDetail>
+        ) => {
+            this.hideAndCloseOverlay(
+                activeOverlay,
+                true,
+                !!event.detail?.reason
```
Comment (hunterloftis) [inline packages/overlay/src/overlay-stack.ts:320]: I had to look these up - might be worth a pair of comments:

```suggestion
                true,  // animated
                !!event.detail?.reason  // clickAway
```

File: packages/menu/src/MenuItem.ts [hunk 10]
```diff
@@ -276,6 +324,108 @@ export class MenuItem extends LikeAnchor(Focusable) {
...
+                            detail: { reason: 'external-click' },
+                        })
+                    );
+                }
+            };
+            this.addEventListener('sp-closed', cleanup as EventListener, {
+                once: true,
+            });
+        }
+    }
```
Comment (hunterloftis) [inline packages/menu/src/MenuItem.ts:427]: Consider breaking `openOverlay` into smaller functions, if possible.

**Review by hunterloftis — APPROVED** [review]
I ran through all the manual tests, 👍  and of course CI is 👍 

image

File: packages/menu/src/MenuItem.ts (hunk 8 above)
Comment (Westbrook) [reply packages/menu/src/MenuItem.ts]: I think I _wanted_ to use delayed, but then realized it's kind of a PITA here and turned it off, but didn't remove it. Removed it for now.

File: packages/menu/src/MenuItem.ts (hunk 10 above)
Comment (Westbrook) [reply packages/menu/src/MenuItem.ts:424]: Maybe in the future, but it closes over state for the time being.

File: packages/menu/src/MenuItem.ts (hunk 7 above)
Comment (Westbrook) [reply packages/menu/src/MenuItem.ts]: We aren't technically at that version yet, and a quick attempt ran into some TS annoyances, so punting on this.

**Review by najikahalsema — APPROVED** [review]
