### PR TITLE
fix(overlay): automatically reposition overlay when the contents resize

### LINKED ISSUE #3809: [Feat]: Adjust overlay top/left positioning to re-align with trigger when sizes change
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay

### Description of the requested feature

Currently if users open a popover with dynamical content where the height changes - and that popover is in an overlay triggered by some button (or other element) with top alignment - when the height changes it doesn't update the alignment to the trigger. Thus resulting in either covering the trigger (when the element height enlarges - or moving the bottom line of the popover away - when the height shrinks).
Same probably happens with left-positioning and dynamical width changes.

See screens:
1st example:
Popover in sp-overlay has some accordion in it, first collapsed state:
Screenshot 2023-11-16 at 10 17 49

Then the accordion-items opens and the popover fully hides the trigger:
Screenshot 2023-11-16 at 10 17 55

---------------
2nd example
Popover starts with open accordion item and aligns correctly:
Screenshot 2023-11-16 at 10 18 02

Now accordion-item is closed, trigger is not aligned anymore:
Screenshot 2023-11-16 at 10 18 07

### Mockups or screenshots
Example: https://studio.webcomponents.dev/edit/ZZkbLM8jiPFVfb7zuz9g/src/index.ts?p=stories

### Implementation notes or ideas

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Remove the need for `Overlay.update()` by binding multiple `autoUpdate` listeners with different settings.
- clean up consumption of `<sp-popover>` in Overlay Element stories

## Related issue(s)
- fixes #3809

## How has this been tested?
-   [ ] _Test case 1_
    1. Go [here](https://overlay-update--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--accordion)
    2. Open the overlay
    3. Open various Accordion Items
    4. See that through it all the size of the overlay is updated

## Types of changes
-   [x] New feature (non-breaking change which adds functionality)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: packages/overlay/src/Overlay.ts [hunk 1]
```diff
@@ -883,7 +883,6 @@ export class Overlay extends OverlayFeatures {
     }
 
     public override manuallyKeepOpen(): void {
-        super.manuallyKeepOpen();
```
Comment (najikahalsema) [inline packages/overlay/src/Overlay.ts:886]: Why was this removed? Not needed, or did it cause problems?

**Review by najikahalsema — APPROVED** [review]
lgtm!

File: packages/overlay/src/Overlay.ts (hunk 1 above)
Comment (Westbrook) [reply packages/overlay/src/Overlay.ts:886]: No needed and even ghost calls have a performance cost so 💥

**Comment by spdev3000** [comment]
Thanks Westbrook for that fix!
