### PR TITLE
fix: correct the relationship between overlayWillCloseCallback and phased animations

### LINKED ISSUE #2646: [Bug]: dismissing an overlay twice, quickly, breaks the overlay in question
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay,dialog

### Expected behavior

Pressing escape N times, or clicking on an underlay N times, no matter how fast, does not impact the future behavior of overlays.

### Actual behavior

Pressing escape twice or clicking on an underlay twice, quickly, can prevent future overlays from opening.

### Screenshots

https://user-images.githubusercontent.com/364501/194432655-23f81f5f-b8a4-457a-a716-554c877a4849.mov

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/dialog-wrapper/
2. Click "toggle dialog"
3. Double-click on its underlay quickly
4. Click "toggle dialog"
5. Notice that no dialog opens

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
- prevent N number of `Escape` pressed or "close" button clicks from breaking the overlay that is being managed by those interactions
- ensure "open" animations are being run in Firefox
  - turn tests in this are back on for Firefox
- refactor work workflows for simplicity
- remove test time workaround for multiple overlay open/closes

## Related issue(s)
- fixes #2646

## How has this been tested?
-   [ ] _Test case 1_
    1. Go [here](https://double-close--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-base--slotted)
    2. Once the dialog is open, quickly press `Escape` N number of times.
    3. See that the dialog is closed
    4. Click the "Toggle Dialog" button
    5. See that the dialog is opened.
    6. Repeat 2-5 N number of times.
-   [ ] _Test case 2_
    1. Go [here](https://double-close--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-base--slotted)
    2. Once the dialog is open, quickly click "Cancel" N number of times
    3. See that the dialog is closed
    4. Click the "Toggle Dialog" button
    5. See that the dialog is opened.
    6. Repeat 2-5 N number of times.
-   [ ] _Test case 3_
    1. Go [here](https://double-close--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-base--slotted) in FireFox
    2. Open and close the dialog N number of times by which ever method you would like
    3. See that while _opening_ there is an animated transition between the closed and opened state

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

### CODE REVIEW

File: packages/dialog/src/DialogBase.ts [hunk 1]
```diff
@@ -150,9 +148,13 @@ export class DialogBase extends FocusVisiblePolyfillMixin(SpectrumElement) {
 
     protected override update(changes: PropertyValues<this>): void {
         if (changes.has('open') && changes.get('open') !== undefined) {
-            this.transitionPromise = new Promise(
-                (res) => (this.resolveTransitionPromise = res)
-            );
+            this.animating = true;
```
Comment (hunterloftis) [inline packages/dialog/src/DialogBase.ts:151]: This sort of async bookkeeping & synchronization is what suggests that perhaps we should consider a [state machine](https://www.youtube.com/watch?v=RqTxtOXcv8Y) pattern. (/cc @najikahalsema)

File: packages/dialog/test/dialog-base.test.ts [hunk 2]
```diff
@@ -115,10 +102,6 @@ describe('dialog base', () => {
         expect(dialog.parentElement?.localName).to.equal('overlay-trigger');
     });
     it('does not close by default with interacting with buttons when recycled', async () => {
-        // There is an `sp-dialog-base` recyling issue in Firefox
```
Comment (hunterloftis) [inline packages/dialog/test/dialog-base.test.ts:118]: 🎉 also love to see test skips deleted!

File: packages/dialog/test/dialog-wrapper.test.ts [hunk 3]
```diff
@@ -105,7 +105,7 @@ describe('Dialog Wrapper', () => {
         expect(el.open).to.be.false;
         expect(closeSpy.callCount).to.equal(1);
     });
-    xit('opens and closes when element is recycled', async () => {
+    it('opens and closes when element is recycled', async () => {
         // Skip while there is an `sp-dialog-base` recyling issue in Chromium and Firefox,
         // this test passes outside of the testing context and in Safari...
```
Comment (hunterloftis) [inline packages/dialog/test/dialog-wrapper.test.ts:110]:
```suggestion
```

File: packages/overlay/src/overlay-stack.ts [hunk 4]
```diff
@@ -48,6 +48,10 @@ interface ManagedOverlayContent {
     updateComplete?: Promise<boolean>;
 }
 
+function nextFrame(): Promise<void> {
```
Comment (hunterloftis) [inline packages/overlay/src/overlay-stack.ts:51]: Any reason not to import `nextFrame` from '@open-wc/testing'?

File: packages/overlay/test/overlay-trigger-hover.test.ts [hunk 5]
```diff
@@ -53,32 +52,20 @@ async function styledFixture<T extends Element>(
...
+    //     const promises = triggers.map((trigger) => {
+    //         if (trigger.open) {
+    //             const closed = oneEvent(trigger, 'sp-closed');
+    //             trigger.open = undefined;
+    //             return closed;
+    //         }
+    //         return Promise.resolve();
+    //     });
+    //     await Promise.all(promises);
+    // });
```
Comment (hunterloftis) [inline packages/overlay/test/overlay-trigger-hover.test.ts:68]:
```suggestion
```

File: packages/shared/src/focusable.ts [hunk 6]
```diff
@@ -16,6 +16,10 @@ import { FocusVisiblePolyfillMixin } from './focus-visible.js';
 
 type DisableableElement = HTMLElement & { disabled?: boolean };
 
+function nextFrame(): Promise<void> {
+    return new Promise((res) => requestAnimationFrame(() => res()));
+}
```
Comment (hunterloftis) [inline packages/shared/src/focusable.ts:21]: Same Q here

File: packages/shared/src/focusable.ts [hunk 7]
```diff
@@ -259,12 +263,31 @@ export class Focusable extends FocusVisiblePolyfillMixin(SpectrumElement) {
...
+            // If at connect time the [autofocus] content is placed within
+            // content that needs to be "hidden" by default, it would need to wait
+            // two rAFs for animations to be triggered on that content in
+            // order for the [autofocus] to become "visisble" and have its
+            // focus() capabilities enabled.
+            //
+            // Await this with `getUpdateComplete` so that the element cannot
+            // become "ready" until `manageFocus` has occured.
+            await nextFrame();
+            await nextFrame();
```
Comment (hunterloftis) [inline packages/shared/src/focusable.ts:279]: Good encapsulation of this requirement & documentation, but painful that we're manually counting frames.

**Review by hunterloftis — APPROVED** [review]

File: packages/shared/src/focusable.ts (hunk 7 above)
Comment (Westbrook) [reply packages/shared/src/focusable.ts:279]: This definitely should become a platform API, but we're not specifically "counting" frames as much as ensuring that a full paint cycle has gone by before this happens. Cycle is one `rAF` to get to the end of _this_ fame (which is pre-paint) and one `rAF` to get to the end of the _next_ frame (which is post paint).

Maybe the abstraction shouldn't be "next frame" and should be "paintComplete" or something?

File: packages/overlay/src/overlay-stack.ts (hunk 4 above)
Comment (Westbrook) [reply packages/overlay/src/overlay-stack.ts:51]: I didn't want to set a standard for importing "test" code into the production library...but maybe that's being overly strict?

File: packages/dialog/src/DialogBase.ts (hunk 1 above)
Comment (Westbrook) [reply packages/dialog/src/DialogBase.ts:151]: An this state management might not "be cleaned up" but a new overlay approach, as it's bound deeply into the content that is being overlaid, which means we might still benefit from it...

File: packages/overlay/test/overlay-trigger-hover.test.ts (hunk 5 above)
Comment (Westbrook) [reply packages/overlay/test/overlay-trigger-hover.test.ts:68]: Whoops, I got too excited when that actually fixed the issue I was running into.

File: packages/overlay/src/overlay-stack.ts (hunk 4 above)
Comment (hunterloftis) [reply packages/overlay/src/overlay-stack.ts:51]: 👍 no worries, they're identical today but we can't expect a testing helper to always be production-ready. And it's 1 line.

File: packages/shared/src/focusable.ts (hunk 7 above)
Comment (hunterloftis) [reply packages/shared/src/focusable.ts:279]: Understood, I'm just wary of linking rafs to any kind of logic. Perhaps there aren't extreme cases here where a particular event might be skipped due to raf not firing when we expect (or not including a particular change that we expect), but I've added bugs before by relying on ${something} happening before an raf.

File: packages/dialog/src/DialogBase.ts (hunk 1 above)
Comment (nickschaap) [reply packages/dialog/src/DialogBase.ts:151]: For purposes of extensibility it might be nice to consider moving away from this lifecycle approach where the consumer is having to manage transitions or consolidating the logic into an OverlayBase element so that if a client wants to plugin to the Overlay API with their own custom component they can do so rather easily without have to rewrite a lot of this animation state management logic. #2086
