### PR TITLE
fix: allow contextmenu event passing to pierce shadow roots

### LINKED ISSUE #1790: [Feat]: [Overlay] dispatch contextmenu events to shadowDom elements
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay

### Description of the requested feature

https://github.com/adobe/spectrum-web-components/commit/9e83f3c0d2398323ebe941ba253d7a0dc0f40ba6

In this commit, a event handler was added to re-dispatch contextmenu events to underlying page.

We could find the actual element though shadow dom, as the target to dispatch the event.

### Mockups or screenshots

_No response_

### Implementation notes or ideas

https://github.com/adobe/spectrum-web-components/blob/74e2cc3d60bf669fdbe0a14a8f7967503b840452/packages/overlay/src/overlay-stack.ts#L155

```diff
-            const target = document.elementFromPoint(event.clientX, event.clientY);
+            let target = document.elementFromPoint(event.clientX, event.clientY);
+            while (target?.shadowRoot) {
+                const innerTarget = target.shadowRoot.elementFromPoint(event.clientX, event.clientY);
+                if (!innerTarget || innerTarget === target) {
+                    break;
+                }
+                target = innerTarget;
+            }
```

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Walk down shadow roots to ensure that `contextmenu` events passed to the underlying page actually hit the element at the point where the pointer interacted with the page regardless of what shadow tree it might exist in.

Thanks @OpportunityLiu for pointing this out!

## Related issue(s)
- fixes #1790

## Motivation and context
Full power `contextmenu` passing.

## How has this been tested?
-   [ ] _Test case 1_
    1. Go to https://contextmenu-piercing--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--virtual-element&args=placement:right-end;offset:0;colorStop:light
    2. Make a "context" click (right button) on the left half of the page.
    3. Ensure that the overlay says "Menu Source: Start"
    4. **While still open**, make a "context" click on the right half of the page.
    5. Ensure that the overlay says "Menu Source: End"

## Types of changes
-   [x] New feature (non-breaking change which adds functionality)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: packages/overlay/src/overlay-stack.ts [hunk 1]
```diff
@@ -152,7 +152,18 @@ export class OverlayStack {
         event.stopPropagation();
         event.preventDefault();
         await this.closeTopOverlay();
-        const target = document.elementFromPoint(event.clientX, event.clientY);
+        let target = document.elementFromPoint(event.clientX, event.clientY);
+        while (target && target.shadowRoot) {
```
Comment (hunterloftis) [inline packages/overlay/src/overlay-stack.ts:156]: Could we use optional chaining here? `while (target?.shadowRoot)`

File: packages/overlay/src/overlay-stack.ts [hunk 2]
```diff
@@ -152,7 +152,18 @@ export class OverlayStack {
...
+            const innerTarget = (
+                target.shadowRoot as unknown as {
+                    elementFromPoint: (x: number, y: number) => Element | null;
+                }
+            ).elementFromPoint(event.clientX, event.clientY);
+            if (!innerTarget || innerTarget === target) {
+                break;
+            }
+            target = innerTarget;
+        }
```
Comment (hunterloftis) [inline packages/overlay/src/overlay-stack.ts:166]: Is this something other components might need to do? If so, we could extract it into a shared function.

**Review by hunterloftis — APPROVED** [review]

File: packages/overlay/src/overlay-stack.ts (hunk 2 above)
Comment (Westbrook) [reply packages/overlay/src/overlay-stack.ts]: I'm not sure we do it anywhere else right now, but abstracting it as a helper will be useful longterm, yes!
