### PR TITLE
fix: special case the possibility of leaving an overlay trigger by entering its overlay content

### LINKED ISSUE #2573: [Bug]: Tooltip not open on slow pointer enter from the direction it opens towards
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

ActionButton, ToolTip

### Expected behavior

(Self-managed) tooltip should open (and stay open) when user enters mouse/pointer slowly into/over icon-only action-button.

### Actual behavior

There seems some area after the border of the action-button (icon-only) that triggers pointer-out or pointer-leave event to dismiss the tooltip.
This happens when the user slowly moves the mouse/pointer over the action-button.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/XrdomH5iKve4qnoNo8Vz/src/index.ts
use last row with action-button below "Self managed ToolTip"

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Due to https://bugs.chromium.org/p/chromium/issues/detail?id=1363632 we need to use JS to manage pointer events and their interaction between the trigger and the content of an overlay, particularly when that content is a tooltip.

TODO:
- [ ] confirm with reporter
- [ ] devise a test for this interaction

## Related issue(s)

- fixes #2573

## How has this been tested?

-   [ ] _Test case 1_
    1. Go [here](https://tooltip-enter--spectrum-web-components.netlify.app/storybook/index.html?path=/story/overlay--default)
    2. Slowly enter the button with your pointer device from the bottom center, see that the tooltip is opened correctly.
-   [ ] _Test case 2_
    1. Go [here](https://tooltip-enter--spectrum-web-components.netlify.app/storybook/index.html?path=/story/tooltip--self-managed&args=placement:bottom;offset:0)
    2. Close the tooltip
    3. Slowly enter the button with your pointer device from the bottom center, see that the tooltip is opened correctly.
  
## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

**Review by spdev3000 — DISMISSED** [review]
LGTM

File: packages/overlay/src/OverlayTrigger.ts [hunk 1]
```diff
@@ -266,6 +269,26 @@ export class OverlayTrigger extends SpectrumElement {
     }
 
     private onTrigger(event: CustomEvent<LongpressEvent>): void {
+        if (
+            event.type === 'mouseleave' &&
+            this.open === 'hover' &&
+            (event as unknown as MouseEvent).relatedTarget ===
+                this.overlaidContent
+        ) {
```
Comment (hunterloftis) [inline packages/overlay/src/OverlayTrigger.ts:277]: not critical, but might be appreciated by future readers:

```suggestion
        const mouseLeavingHoverContent = event.type === 'mouseleave' && this.open === 'hover' && (event as unknown as MouseEvent).relatedTarget === this.overlaidContent;
        
        if (mouseLeavingHoverContent) {
```

File: packages/tooltip/src/Tooltip.ts [hunk 2]
```diff
@@ -199,7 +199,26 @@ export class Tooltip extends SpectrumElement {
...
 
-    private closeOverlay = async (): Promise<void> => {
+    private closeOverlay = async (
+        event?: PointerEvent | FocusEvent | Event
+    ): Promise<void> => {
+        if (
+            event &&
+            event.type === 'pointerleave' &&
+            (event as PointerEvent).relatedTarget === this
+        ) {
```
Comment (hunterloftis) [inline packages/tooltip/src/Tooltip.ts:209]: Similar code-as-docs:

```suggestion
        const pointerLeavingThis = event?.type === 'pointerleave' && (event as PointerEvent).relatedTarget === this;
        
        if (pointerLeavingThis) {
```

**Review by hunterloftis — DISMISSED** [review]
lgtm! Left suggestions to consider just as alternatives.
