### PR TITLE
fix: prevent leaving multiple submenus open at a time

### LINKED ISSUE #2197: [Bug]: Submenu doesn't open on hover or remains open after hovering out, overlapping with other submenus
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-menu

### Expected behavior

When having multiple menu items that have a submenu that opens on hover, submenu should close when hovering out.  

### Actual behavior

Submenu persists open after hovering out of their area. Because of this sometimes overlaps with other submenus or doesn't open the other submenu.

### Screenshots

Screenshot 2022-03-31 at 10 45 20
Screenshot 2022-03-31 at 10 45 36

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari

### How can we reproduce this issue?

1. Go to [https://git.corp.adobe.com/pages/DIWI/uec-previews/main/?path=/story/application-menu--default](https://git.corp.adobe.com/pages/DIWI/uec-previews/main/?path=/story/application-menu--default)
2. Open menu and hover over `Edit` and then `Transform` menu items to open their submenus
3. Hover out of the menu area 
4. Then hover again over `View` to open its submenu
5. Notice that sometimes `View` menu doesn't open and other times overlaps with the previously opened `Edit` submenu

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Rather than hack the Menu/Menu Item relationship to enforce open/close rules on a Menu with multiple submenus, add a `root` concept to the overlay stack that prevents multiple overlays from the same root, even if they have different triggers.
- prevent leaving things open
- prevent passing focus back to the "root"
- reduce code needed to manage submenus
- doesn't have a test for duplicate submenus being open because while I'm "certain ™️" that the issue comes from the way `setCloseSelfAsSubmenu` and `setCloseOpenSubmenu` were being used, I could never isolate a reproduction case to base a new test on
- [x] needs a test for closing super decedent submenus when changing two+ levels up

## Related issue(s)
- fixes #2197
- closes #2218 

## Motivation and context
Things should "just work" 😉 

## How has this been tested?
-   [ ] _Test case 1_
    1. Go [here](https://submenu--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--submenu)
    2. Note: the menus open wonky by default.
    3. Mouse around in an attempt to break it and have a submenu not open or have more than one submenu for the same menu open or have sub-submenus not close, etc.
    4. Rejoice.

## Types of changes
-   [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

### CODE REVIEW

**Review by najikahalsema — APPROVED** [review]
This is so beautiful. I'm crying right now. Nice work!

**Comment by Westbrook** [comment]
Nice catch @hunterloftis! It helped me to catch another issue, as well. Added tests for both of them now that they are fixed.

File: packages/overlay/src/overlay-stack.ts [hunk 1]
```diff
@@ -478,7 +509,7 @@ export class OverlayStack {
     private async hideAndCloseOverlay(
         overlay?: ActiveOverlay,
         animated?: boolean,
-        clickAway?: boolean
+        shouldNotReceiveFocus?: boolean
```
Comment (hunterloftis) [inline packages/overlay/src/overlay-stack.ts:512]: nit: could this name be more obvious / how could we avoid negating a boolean? What do you think of `skipFocus`?

**Review by hunterloftis — APPROVED** [review]
