### PR TITLE
fix(tray): add visually hidden dismiss buttons

### LINKED ISSUE #3382: [Bug][a11y]: Tray component lacks visually hidden dismiss button to close the overlay on mobile
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Tray

### Expected behavior

Like a Picker or ActionMenu, Tray should include a Dismiss button before and after the menu or dialog content so that the overlay can be dismissed using a mobile screen reader.

See the following example from Picker:

https://github.com/adobe/spectrum-web-components/blob/8eb28c866c960b2cf27930cc1eab8f96e2c057d9/packages/picker/src/Picker.ts#L474C19-L521

### Actual behavior

Tray examples lack visually hidden dismiss button to close the overlay on mobile.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by marissahuysentruyt**
## Description

This PR implements visually hidden dismiss buttons in the `<sp-tray>` component to improve mobile screen reader accessibility, particularly for VoiceOver on iOS. The dismiss buttons are automatically rendered before and after the tray's slotted content, allowing mobile screen reader users to easily dismiss the overlay from either end without requiring manual implementation by developers.

### Changes include:

1. **Added `dismissHelper` getter** to `Tray.ts` that returns a visually hidden button template
2. **Updated render method** to wrap slotted content with dismiss helpers
3. **Enhanced CSS** to support `.visually-hidden` class for shadow DOM content
4. **Comprehensive documentation** in README with explanations and tabbed examples

The implementation follows the same pattern used in the `<sp-picker>` component, ensuring consistency across the design system.

## Motivation and context

Mobile screen reader users, particularly those using VoiceOver on iOS, navigate through interactive elements sequentially (by swiping). Without dismiss buttons at the beginning and end of tray content, users who navigate past all menu items have difficulty discovering how to close the overlay - they must either navigate backward through all items or close the app entirely.

This gap affects any tray usage with menu content that lacks a built-in dismiss mechanism.

## Related issue(s)

- fixes #3382
- SWC-274

## Screenshots (if appropriate)

Screenshot 2025-10-20 at 2 52 25 PM

---

## Author's checklist

- [x] I have read the **[CONTRIBUTING](https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)** and **[PULL_REQUESTS](https://github.com/adobe/spectrum-web-components/blob/main/PULL_REQUESTS.md)** documents.
- [x] I have reviewed the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)
- [ ] I have added automated tests to cover my changes.
- [ ] I have included a well-written changeset if my change needs to be published.
- [x] I have included updated documentation if my change required it.

---

## Reviewer's checklist

- [ ] Includes a Github Issue with appropriate flag or Jira ticket number without a link
- [ ] Includes thoughtfully written changeset if changes suggested include `patch`, `minor`, or `major` features
- [ ] Automated tests cover all use cases and follow best practices for writing
- [ ] Validated on all supported browsers
- [ ] All VRTs are approved before the author can update Golden Hash

### Manual review test cases

- [x] **Verify dismiss buttons are accessible to VoiceOver on Mac** [@cdransf]

    1. Enable VoiceOver (`Cmd + F5` or from within the Accessibility/VoiceOver menus in System Settings)
    2. Open a tray with menu content using the examples in the documentation
    3. Navigate forward with `Control + Option + Right Arrow`
    4. Expect: VoiceOver announces "Dismiss, button" before the first menu item
    5. Continue navigating through all menu items
    6. Expect: VoiceOver announces "Dismiss, button" after the last menu item
    7. Activate either dismiss button with `Control + Option + Space`
    8. Expect: Tray closes successfully

Screenshot 2025-10-17 at 4 31 18 PM

~~**Verify dismiss buttons don't interfere with keyboard navigation** [@cdransf]~~

~~1. Open a tray with menu content~~
~~2. Press Tab key to navigate through interactive elements~~
~~3. Expect: Tab navigation skips the visually hidden dismiss buttons (due to `tabindex="-1"`)~~
~~4. Expect: Tab moves directly from trigger to menu items~~

- [ ] **Verify dismiss buttons are keyboard accessible**

    1. Open a tray with menu content (e.g., using the \"Content has no buttons\" example from README)
    2. Press Tab key repeatedly to navigate through interactive elements
    3. Expect: Focus moves to the first visually hidden dismiss button
    4. Expect: Press Enter to close the tray
    5. Re-open the tray and tab through all content
    6. Expect: Focus reaches the second dismiss button after the last menu item
    7. Press Enter to close the tray from the second button

- [ ] **Verify auto-detection correctly identifies existing buttons**

    1. Open a tray with dialog content that has \`dismissable\` attribute (\"Content has buttons\" example)
    2. Inspect the tray element in DevTools
    3. Expect: No visually hidden dismiss buttons are rendered
    4. Open a tray with menu content only (\"Content has no buttons\" example)
    5. Expect: Two dismiss buttons are rendered (before and after content)

- [ ] **Verify manual override property works correctly**

    1. Open a tray with \`has-keyboard-dismiss\` attribute set (\"Manual override\" example)
    2. Inspect the tray element
    3. Expect: No visually hidden dismiss buttons are rendered, even though content lacks buttons
    4. Verify: You are responsible for providing your own dismiss mechanism

- [x] **Verify dismiss buttons work with dialog content** [@cdransf]

    1. Open a tray with dismissable dialog content
    2. Enable VoiceOver
    3. Navigate through the tray content
    4. Expect: Both the tray's dismiss helpers and dialog's close button are accessible
    6. Verify either method successfully closes the overlay

Screenshot 2025-10-17 at 4 25 46 PM

- [x] **Verify dismiss buttons are visually hidden** [@cdransf]

    1. Open a tray with menu content in a browser
    2. Inspect the tray element
    3. Expect: Dismiss button divs exist in DOM with `.visually-hidden` class
    4. Expect: No visual indication of these buttons (1px size, positioned absolutely, clipped)

### Device review

- [ ] Did it pass in Desktop?
- [ ] Did it pass in (emulated) Mobile?
- [ ] Did it pass in (emulated) iPad?

**Note**: Primary testing should be done with VoiceOver on iOS/iPadOS devices or simulators where the original accessibility issue was discovered.

### CODE REVIEW

**Comment by marissahuysentruyt** [comment]
`TODO` questions: 
- Should the visually-hidden dismiss buttons extend past just mobile trays? (like not _just_ for small screens, but at all screen sizes) `edit`: trays are intended for small screens. i think `sp-dialog-wrapper` is the large screen equivalent.
- Should the dismiss buttons be tied to any `dismissible` property? For instance, if there's a visible & accessible close button in the dialog content, do we still or should we still have visually-hidden buttons before and after the rest of the content? 
- If `DialogWrapper` also doesn't support visually-hidden dismiss buttons but it should- should those buttons go on `DialogBase` since `DialogWrapper` extends `DialogBase`? What about regular `Dialog` without the dismissible property? (`edit`: adding the `dismissHelper` to sp-dialog itself/`Dialog.ts` seems to flow how I am expecting.)

`EDIT` 10/21/25: after pairing with Nikki, reaching out to James Nurthen might be a good idea, just to validate the approach you'll see in the PR right now: 

- implemented `dismissHelper` into sp-tray, sp-dialog-base, and sp-dialog-wrapper (I'm open to feedback on where the dismissHelper needs to be defined!)
- because you can force "mobile" behavior, we opted to render the tray at all screen sizes with visually hidden buttons before and after the slot content.
- in dialog instances, there is a conditional for the _second_ visually-hidden button. If the dialog is `dismissable`, meaning it renders a visible close button, the second dismissHelper button doesn't render.

`EDIT:` 10/23/25: we do not have to render any close button with non-dismissible dialogs. That work has been reverted. 
- the tray should auto-detect if it's content has buttons
    - if the content has buttons, no visually-hidden buttons are rendered
    - if the content has no buttons, visually-hidden buttons are rendered
    - users can manually override so that no visually-hidden buttons are rendered. There's a note in the docs about then needing to do custom keyboard-accessible dismiss functionality (that's up to the consumer to do)

File: packages/dialog/src/DialogBase.ts [hunk 1]
```diff
@@ -194,6 +194,23 @@ export class DialogBase extends FocusVisiblePolyfillMixin(SpectrumElement) {
         super.update(changes);
     }
 
+    /**
+     * Returns a visually hidden dismiss button for mobile screen reader accessibility.
+     * This button is placed before and after dialog content to allow mobile screen reader
+     * users (particularly VoiceOver on iOS) to easily dismiss the overlay.
+     */
+    protected get dismissHelper(): TemplateResult {
```
Comment (marissahuysentruyt) [inline packages/dialog/src/DialogBase.ts]: Added dismissHelper here because `sp-dialog-wrapper` extends `sp-dialog-base`.

File: packages/dialog/src/DialogWrapper.ts [hunk 2]
```diff
@@ -125,6 +125,7 @@ export class DialogWrapper extends DialogBase {
         }
 
         return html`
+            ${this.dismissHelper}
```
Comment (marissahuysentruyt) [inline packages/dialog/src/DialogWrapper.ts]: The first dismissHelper is always shown, regardless of `dismissable`. 

The one at the end of this render function is conditional, so that at most a dialog would only have 2 options for dismissal- a visible close button, and a visually-hidden one for screen readers. 

Is that still too redundant for screen readers users when `dismissable` is true and there's a rendered `sp-close-button`?

File: packages/modal/src/modal.css [hunk 3]
```diff
@@ -24,3 +24,16 @@
 .modal {
     overflow: visible;
 }
+
+.visually-hidden {
```
Comment (marissahuysentruyt) [inline packages/modal/src/modal.css]: I had to add the visually hidden styles to modal because I couldn't get the styles through the shadow DOM when these were in dialog.css/spectrum-dialog.css.

File: packages/tray/README.md [hunk 4]
```diff
@@ -70,3 +70,57 @@ A tray has a single default `slot`.
 ### Accessibility
 
 `<sp-tray>` presents a page blocking experience and should be opened with the `Overlay` API using the `modal` interaction to ensure that the content appropriately manages the presence of other content in the tab order of the page and the availability of that content for a screen reader.
+
+#### Mobile screen reader support
```
Comment (marissahuysentruyt) [inline packages/tray/README.md]: If we like how this additional documentation sounds, want me to add it to the dialog-wrapper docs as well?

File: packages/tray/README.md [hunk 5]
```diff
@@ -7,19 +7,19 @@
 [![See it on NPM!](https://img.shields.io/npm/v/@spectrum-web-components/tray?style=for-the-badge)](https://www.npmjs.com/package/@spectrum-web-components/tray)
 [![How big is this package in your project?](https://img.shields.io/bundlephobia/minzip/@spectrum-web-components/tray?style=for-the-badge)](https://bundlephobia.com/result?p=@spectrum-web-components/tray)
 
-```
+```bash
```
Comment (cdransf) [inline packages/tray/README.md]: Should this be `zsh` now that it's the default on macOS? ✨

File: packages/dialog/src/DialogBase.ts (hunk 1 above)
Comment (marissahuysentruyt) [reply packages/dialog/src/DialogBase.ts]: Follow up: we might elect to change this to a full-fledged `sp-close-button` that is visually hidden, instead of a plain ol' button tag.

Comment (marissahuysentruyt) [reply packages/dialog/src/DialogBase.ts]: We do not have to add buttons to any dialog that is non-dismissible (Nikki chatted with James and confirmed), so I reverted these changes.

File: packages/tray/src/Tray.ts [hunk 6]
```diff
@@ -81,6 +86,103 @@ export class Tray extends SpectrumElement {
...
+    /**
+     * Returns a visually hidden dismiss button for mobile screen reader accessibility.
+     * This button is placed before and after tray content to allow mobile screen reader
+     * users (particularly VoiceOver on iOS) to easily dismiss the overlay.
+     */
+    protected get dismissHelper(): TemplateResult {
+        return html`
+            <div class="visually-hidden">
+                <button
+                    tabindex="-1"
```
Comment (nikkimk) [inline packages/tray/src/Tray.ts]: Screenreader users need to be able to access this via keyboard, so a tabindex should not exist here.

```suggestion
```

File: packages/tray/test/tray.test.ts [hunk 7]
```diff
@@ -100,4 +104,162 @@ describe('Tray', () => {
 
         expect(el.open).to.be.false;
     });
+
+    describe('Dismiss helpers', () => {
+        it('renders visually-hidden dismiss helpers when no buttons detected', async () => {
```
Comment (nikkimk) [inline packages/tray/test/tray.test.ts:109]: We should also text that this button can be accessed via keyboard to dismiss the tray.

File: 1st-gen/packages/tray/test/tray.test.ts [hunk 8]
```diff
@@ -100,4 +104,162 @@ describe('Tray', () => {
 
         expect(el.open).to.be.false;
     });
+
```
Comment (nikkimk) [inline 1st-gen/packages/tray/test/tray.test.ts:107]: I love all the regression tests that were added here. :chefs_kiss:

File: 1st-gen/packages/tray/src/Tray.ts [hunk 9]
```diff
@@ -131,7 +235,13 @@ export class Tray extends SpectrumElement {
                 tabindex="-1"
```
Comment (nikkimk) [inline 1st-gen/packages/tray/src/Tray.ts:235]: Because tray-modal has a `tabindex="-1"`, I still can't get to the dismiss buttons with a keyboard

Image

```suggestion
```

File: 1st-gen/packages/tray/test/tray.test.ts [hunk 10]
```diff
@@ -100,4 +104,162 @@ describe('Tray', () => {
...
+            const helpers = el.shadowRoot.querySelectorAll('.visually-hidden');
+            expect(helpers.length).to.equal(2);
+
+            const buttons = el.shadowRoot.querySelectorAll(
+                '.visually-hidden button'
+            );
+            expect(buttons.length).to.equal(2);
+            expect(buttons[0].getAttribute('aria-label')).to.equal('Dismiss');
+            expect(buttons[0].getAttribute('tabindex')).to.be.null;
```
Comment (nikkimk) [inline 1st-gen/packages/tray/test/tray.test.ts:128]: Let's test this by tabbing to the button, pressing `Enter` and checking if the tray closes. It is a more accurate way to test if this works.

In rthe PR description, we should also ask reviews to test with a keyboard as well.

Comment (marissahuysentruyt) [reply 1st-gen/packages/tray/test/tray.test.ts:128]: The PR description should be updated (sorry I missed that earlier!). 

I also have 2 more tests now- one to make sure the button is tabbable, and the other to make sure enter closes the tray once the button is tabbed to. Thanks for that!

File: 1st-gen/packages/tray/src/Tray.ts (hunk 9 above)
Comment (marissahuysentruyt) [reply 1st-gen/packages/tray/src/Tray.ts:235]: Let me know if I'm still missing anything here. Without removing the `tabindex="-1"` on the `.tray.modal`, I can still tab to the buttons. 

https://github.com/user-attachments/assets/5a89a83a-9fab-441c-b40d-eca73bdf9267

Did we want some sort of focus indicator? What's the expectation if the button is visually hidden, but keyboard accessible? 🤔 
Screenshot 2025-10-24 at 2 25 54 PM

**Review by nikkimk — APPROVED** [review]
LGTM. Worked perfectly. Thanks for taking this one on!

**Review by caseyisonit — APPROVED** [review]
:shipit:
