### PR TITLE
fix(tabs): allow bi-directional arrow key navigation in both orientations

### LINKED ISSUE #3263: [Bug][a11y]: Screen reader users perceive no distinction between horizontal and vertical orientation
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Tabs

### Expected behavior

Since we can't rely on screen readers announcing the tablist orientation to determine whether to use ArrowUp/ArrowDown instead of ArrowLeft/ArrowRight. Both ArrowUp and ArrowLeft should work to navigate to the previous tab, and both ArrowDown and ArrowRight should work to navigate to the next tab.

### Actual behavior

With focus on a Tab, a screen reader user would have to guess the orientation to figure out which arrow keys will work to navigate to the next or previous Tab.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

_No response_

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by TarunAdobe**
## Description

Updated the logic to accept event code on arrow key press in TabGroup.ts allowing users to use both ArrowLeft and ArrowUp keys interchangeably (same for ArrowDown and ArrowRight)

## Related issue(s)

fixes #3263 

## Motivation and context

Currently a screen reader user would have to guess the orientation to figure out which arrow keys will work to navigate to the next or previous Tab since we can't rely on screen readers announcing the tablist orientation.

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by Rajdeepc** [comment]
@TarunAdobe Please check the tests on Tabs. I think these are failing because of your changes.

File: tools/reactive-controllers/src/FocusGroup.ts [hunk 1]
```diff
@@ -230,9 +230,9 @@ export class FocusGroupController<T extends HTMLElement>
         }
         switch (this.direction) {
             case 'horizontal':
-                return code === 'ArrowLeft' || code === 'ArrowRight';
+                return code.startsWith('Arrow');
             case 'vertical':
-                return code === 'ArrowUp' || code === 'ArrowDown';
+                return code.startsWith('Arrow');
```
Comment (Westbrook) [inline tools/reactive-controllers/src/FocusGroup.ts:235]: Based on the conversation in the issue this stems from, I'm still not sure we want to flatten _ALL_ usage of this controller or if we want to just leverage `both` in Tabs, so that it can be accurately supported. Can you take a look at leveraging that instead?

If really _nothing_ should be `horizontal` or `vertical`, then that's another question. Do we auto fallback to both like this? And then use Dev Mode warnings to clarify why the functionality isn't what might be expected by the input, or do we leave `horizontal` and `vertical` as is, change all of our consumption to `both`, and then Dev Mode warn that `horizontal` and `vertical` may not deliver the expected screen reader/keyboard experience.

**Review by Westbrook — COMMENTED** [review]
Which ever path we take, you additional tests should help support that decision, so nice addition there!

File: tools/reactive-controllers/src/FocusGroup.ts (hunk 1 above)
Comment (TarunAdobe) [reply tools/reactive-controllers/src/FocusGroup.ts:235]: That is actually a good point to consider here... I feel though that this should apply to pretty much all the components leveraging the controller right (not just Tabs) as the functionality we are expecting should be consistent? But sure I can try to leverage the both functionality in just the tabs.

Comment (TarunAdobe) [reply tools/reactive-controllers/src/FocusGroup.ts:235]: @Westbrook  Based on the conversation in issue should I make the changes such that this functionality of using both Down/RightArrow and Up/LeftArrow works specifically with tablist only... I'd start by removing the changes from FocusGroup.ts. Let me know if that makes sense?

**Review by Westbrook — APPROVED** [review]
Thanks for simplifying this! We'll get down to the real guts of this change with the a11y team later.
