### PR TITLE
fix: add support for "padding" attribute

### LINKED ISSUE #2554: [Feat]: Support "padding" property in Grid
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Grid

### Description of the requested feature

`gap` is paired with a `padding` property and by default "matches". Ensure that `sp-grid` surfaces API for managing the `padding` property so that layouts do not require external padding when it is not desired.

### Mockups or screenshots

_No response_

### Implementation notes or ideas

See https://github.com/lit/lit/blob/main/packages/labs/virtualizer/src/layouts/shared/SizeGapPaddingBaseLayout.ts#L82-L88 for information on this usage.

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Support customization of `padding` in the Grid

Note:
The Storybook won't responsively update when the `padding` is changed in the UI due to https://github.com/lit/lit/issues/3285, but update `gap` and previously send `padding` updates will take.

## Related issue(s)

- fixes #2554

## How has this been tested?

-   [ ] _Test case 1_
    1. Go [here](https://grid-padding--spectrum-web-components.netlify.app/storybook/?path=/story/grid--sized)
    2. Update `gap` and `padding` in the Story UI
    3. See above note about responsivity...

## Types of changes
-   [x] New feature (non-breaking change which adds functionality)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: tools/grid/src/GridController.ts [hunk 1]
```diff
@@ -119,28 +131,43 @@ export class GridController<T extends HTMLElement>
...
-            (contentRect.width - gap) / (this.itemSize.width + gap)
-        );
+        const padding = this.padding ? parseFloat(this.padding) : 0;
+        let contentBoxWidth =
+            contentRect.width - padding * 2 - this.itemSize.width;
+        let directionLength = 0;
+        while (contentBoxWidth > 0) {
+            directionLength += 1;
+            contentBoxWidth = contentBoxWidth - (gap + this.itemSize.width);
+        }
```
Comment (hunterloftis) [inline tools/grid/src/GridController.ts:168]: Would this be equivalent?

```suggestion
        const directionLength = Math.floor(contentBoxWidth / (gap + this.itemSize.width));
```

**Review by hunterloftis — APPROVED** [review]

File: tools/grid/src/GridController.ts (hunk 1 above)
Comment (Westbrook) [reply tools/grid/src/GridController.ts:168]: I'm sure there's a smarter math here. This comes from the idea that if there at `n` items in a row, then there are `n - 1` gaps, so you can't just say `gap + itemWidth`.  So maybe it's clearer with:
```js
        // account for there being one less gap than items in a row
        contentBoxWidth = contentBoxWidth - this.itemSize.width;
        const directionLength = Math.floor(contentBoxWidth / (gap + this.itemSize.width)) + 1;
```
